### ISSUE TITLE
[CT-2023] [Feature] Create an append_unique incremental strategy

### ISSUE THREAD

**Issue by rileyschack** [dbt-labs/dbt-core#6848] opened 2023-02-02 22:07 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Add an `append_unique` incremental strategy (or a `unique_only: true` property on the `append` strategy) to only insert new records to the destination table.

### Describe alternatives you've considered

The current implementation of `append` requires the user to design their dbt model in a way that ensures no duplicates are included. This typically involves a join or subquery to the destination table to filter out existing records, or creating a subsequent model that calls `select distinct` or a window function to pick the 1st record.

The logic in the dbt model can be greatly simplified if we add this configuration. The resulting DML would look like:

```sql
merge into {{ destination table }} as DBT_INTERNAL_DEST
using ({{ dbt_model }}) as DBT_INTERNAL_SOURCE
on DBT_INTERNAL_DEST.{{ unique_key }} = DBT_INTERNAL_SOURCE.{{ unique_key }}
when not matched then 
    insert ({{ destination_columns }})
    values ({{ destination_columns }})
```

The only change is to the merge predicate--swapping it from `FALSE` to a unique key comparison.

You can also look at this from the point of view of the `merge` strategy. If the `merge_update_columns` property could differentiate between an empty list and not being defined, then passing an empty list could just remove the `when matched then update set` clause.

### Who will this benefit?

This will simplify append-only incremental models that need to remove duplicates. Users can design their incremental models without needing to give special care to duplicates.

This will be a slightly more expensive version than `append` because the `MERGE` statement will actually be joining the unique keys. It should be identical cost to including the deduping logic in the model, because that will also require a scan on the unique key of the destination table. The simplicity is well worth it, however.

#### Example 1

`src_table` appends new json data every day and is partitioned on `loaded_at`. Sometimes duplicate json records are included. `dst_table` should parse out the json from `src_table` but also remove duplicates. Desired implementation:

```sql
{{
    config(
        materialized="incremental",
        incremental_strategy="append_unique",
        unique_key="unique_id"
    )
}}

with src_table as (
    select *
    from {{ ref("src_table") }}
)

, step_1 as (
    select
        json_extract(json_data, '$.uniqueId') as unique_id
        , json_extract(json_data, '$.field1') as field_1
        , ...
        , loaded_at
    from src_table
    {% if is_incremental() %}
    where loaded_at > _dbt_max_partition
    {% endif %}
)

select *
from step_1
```

#### Example 2

`src_table` appends new transactions every day and is partitioned on `transaction_date`. The transactions can sometimes appear up to 2 days late. The `dst_table` should be an aggregated table that shows the first transaction date for each user.

```sql
{{
    config(
        materialized="incremental",
        incremental_strategy="append_unique",
        unique_key="unique_id"
    )
}}

with src_table as (
    select *
    from {{ ref("src_table") }}
)

, step_1 as (
    select
        user_id
        , min(transaction_date) as first_transaction_date
    from src_table
    {% if is_incremental() %}
    where date(loaded_at) between date_sub(current_date, interval 2 day) and current_date
    {% endif %}
    group by user_id
)

select *
from step_1
```

For comparison, this is what an existing model might look like:

#### Existing Solution for Example 2
  
```sql
{{
    config(
        materialized="incremental",
        incremental_strategy="append",
    )
}}

with src_table as (
    select *
    from {{ ref("src_table") }}
)

, step_1 as (
    select
        user_id
        , min(transaction_date) as first_transaction_date
    from src_table
    {% if is_incremental() %}
    where date(loaded_at) between date_sub(current_date, interval 2 day) and current_date
    {% endif %}
    group by user_id
)

{% if is_incremental() %}
/* Exclude records that already exist in the destination table */
, step_2 as (
    select
        new_records.*
    from step_1 as new_records
    left join {{ this }} as old_records
        on new_records.user_id = old_records.user_id
    where old_records.user_id is null
)
{% endif %}

select *
from {% if is_incremental() %} step_2 {% else %} step_1 {% endif %}
```

### Are you interested in contributing this feature?

Possibly

**Comment by rileyschack** [comment] 2023-02-02 22:10
In my eyes, this already has a lot of synergy with the existing `merge` and `append` strategies, and feels like a natural extension of those. On that topic, is there an ETA when `dbt-bigquery` will natively support `append`? Right now, we have to use `merge` without a `unique_key` to get the same effect.

**Comment by jtcohen6** [comment] 2023-02-09 12:10
@rileyschack Thanks for opening!

### Discussion

So the big idea is: You want to insert records with totally unique IDs, _and you don't want to update any existing rows_. Do I have that right? If so, I think this might be the same as the request in https://github.com/dbt-labs/dbt-core/issues/6320!

> It should be identical cost to including the deduping logic in the model, because that will also require a scan on the unique key of the destination table. The simplicity is well worth it, however.

I think you and I disagree here on which is the more simple—which is okay! We have strong opinions about what the sensible default behavior ought to be, but they shouldn't constraint the realm of the possible. Here's what I said in #6320:

> I see two valid ways to achieve this:
> 1. `merge` that matches on unique keys, `when matched` ignores, `when not matched` inserts
> 2. In your model SQL, filter out any records where the `unique_key` is already in `{{ this }}` (preexisting table) — leaving you with only never-before-seen rows. Then, use a simple `insert` statement to add them in.

> The second approach is less fancy, and that's a good thing! All the business logic lives in the model; the materialization logic is dead simple. It's super easy to reason through, and to see the exact rows that will be appended into the resulting table, _without actually modifying that table_, simply by previewing the model SQL (`select ...`).

So even if you and I disagree, I believe very much that _it should be possible_ for you to define your own custom incremental strategy—without needing to copy-paste-reimplement the whole entire `incremental` materialization. We unlocked this possibility with some refactoring work in dbt-core v1.3, because folks are going to keep wanting slight variations of incremental strategies (merge/upsert behavior). For example, see also the discussions in https://github.com/dbt-labs/dbt-core/issues/6415, https://github.com/dbt-labs/dbt-core/issues/6077, ...

### Implementation

Is this possible with `dbt-bigquery` today? Unfortunately, not quite yet. As it turns out, your follow-up question has the exact same answer:

> On that topic, is there an ETA when `dbt-bigquery` will natively support `append`?

Given capacity constraints at the time, we made minimal changes in `dbt-bigquery` for compatibility with the refactor in v1.3:
- https://github.com/dbt-labs/dbt-bigquery/issues/232
- https://github.com/dbt-labs/dbt-bigquery/pull/223

I've just opened a new issue (https://github.com/dbt-labs/dbt-bigquery/issues/523) for the "fuller" support, akin to the changes we made in `dbt-snowflake`:
- https://github.com/dbt-labs/dbt-snowflake/issues/195
- https://github.com/dbt-labs/dbt-snowflake/pull/196

Once that's done, not only will you be able to opt for an explicit `append` strategy — you could also define your own custom "strategy," following a macro naming convention:

```sql
-- models/my_append_unique_incremental_model.sql

{{ config(materialized = 'incremental', incremental_strategy = 'append_unique') }}

select ...
```
Then you'd define a macro named `get_incremental_X_strategy`, where `X` matches your custom strategy name (`append_unique`).

Here's some pseudo-code, intentionally simplified. No support for `incremental_predicates`, `sql_header`, multiple `unique_key`, etc. Up to you how much complexity you'd want to allow!
```sql
{% macro get_incremental_append_unique_strategy(arg_dict) %}
    
    -- {# these components are passed in as a dictionary from the incremental materialization #}
    {% set target, source, unique_key, dest_columns, predicates =
      arg_dict['target_relation'],
      arg_dict['temp_relation'],
      arg_dict['unique_key'],
      arg_dict['dest_columns'] %}
    
    {%- set dest_cols_csv = get_quoted_csv(dest_columns | map(attribute="name")) -%}

    {% if not unique_key %}
      {{ exceptions.raise_compiler_error("Need a unique key!") }}
    {% endif %}

    merge into {{ target }} as DBT_INTERNAL_DEST
        using {{ source }} as DBT_INTERNAL_SOURCE
        on DBT_INTERNAL_SOURCE.{{ key }} = DBT_INTERNAL_DEST.{{ key }}

    -- no update clause!!

    when not matched then insert
        ({{ dest_cols_csv }})
    values
        ({{ dest_cols_csv }})

{% endmacro %}
```

cc @dataders - We gotta sit down and write these docs!! https://github.com/dbt-labs/docs.getdbt.com/issues/1761

In the meantime, I'm going to close this issue as a duplicate of #6320, and as something that's better resolved by the more flexible mechanism we initially created last year (though still need to carry through for `dbt-bigquery`).

**Closed by jtcohen6** 2023-02-09 12:10 UTC
Labels: enhancement, triage, incremental, Team:Adapters

**Comment by anaghshineh** [comment] 2023-02-09 13:55
👏 I made a note to +1 this because it is essentially what I asked for in #6320. @jtcohen6, your response continues to make complete sense, and I respect that. I agree with @rileyschack, though, on the simplicity front 😉. I appreciate the `get_incremental_append_unique_strategy` macro example in this thread, thank you!
