### ISSUE TITLE
[CT-635] [Bug] dbt attempts to parse node if parent node is also disabled

### ISSUE THREAD

**Issue by azhard** [dbt-labs/dbt-core#5237] opened 2022-05-12 14:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I have a node `a` that is a parent of node `b` and both of them are disabled through my node YML file, when running any dbt command such as `list`, I would expect neither to show up. However, I instead get the following compilation error:
```Model 'b' depends on node named 'a' which was not found```

When just disabling node `b` there are no issues so it seems as though dbt is trying to parse the disabled node only when it has a disabled parent node.

Note: it appears this issue only happens when the `enabled` flag is configured in the YML file. When configuring it in SQL, the nodes do not get parsed.

### Expected Behavior

I would expect dbt to not attempt to parse node `b` because it has been marked as disabled in my YML fiile.

### Steps To Reproduce

1. Create a model `a` with SQL: 
```SELECT 1```

2. Create YML file for model `a`:
```
version: 2
models:
  - name: a
    config:
      enabled: false
```

3. Create a model `b` with SQL:  
```SELECT * FROM {{ ref('a') }}```
4. Create YML file for model `b`:
``````
version: 2
models:
  - name: b
    config:
      enabled: false
```
5. Run `dbt list` and observe error

### Relevant log output

```shell
Encountered an error:
Compilation Error in model b (models/b.sql)
  Model 'b' (models/b.sql) depends on a node named 'a' which was not found
```
```


### Environment

```markdown
- OS: MacOS 12.0.1
- Python: 3.9.1
- dbt: 1.1.0
```


### What database are you using dbt with?

bigquery

### Additional Context

_No response_

**Comment by emmyoop** [comment] 2022-05-12 19:32
@azhard Thank you so much for providing a simple and reproducible use case here!  I truly appreciate it.  

I was able to reproduce this behavior when the models have separate yaml files to define the config resource property as you describe above.  It results in the following error.

```bash
19:26:05  Encountered an error:
Compilation Error in model b (models/b.sql)
  Model 'model.basic_dbt.b' (models/b.sql) depends on a node named 'a' which was not found
```

However, if listed within a single yaml file like so:

```yml
version: 2
models:
  - name: a
    config:
      enabled: false
  - name: b
    config:
      enabled: false
```

the nodes are both disabled and do not show up in a `dbt list` command, as expected.  Resulting in

```bash
19:31:46  No nodes selected!
```

This looks to be a duplicate of #3992 so I will close this in favor of that issue to keep the conversation centralized.  Feel free to comment over there is you have anything to add!

**Closed by emmyoop** 2022-05-12 19:32 UTC
Labels: bug, triage, Team:Language

**Comment by azhard** [comment] 2022-05-12 19:33
Oh didn't see that thanks @emmyoop, happy to contribute to a solution if pointed in the right direction.
