### ISSUE TITLE
[CT-47] [Bug] Flag `execute` is set to true during the doc generation

### ISSUE THREAD

**Issue by pcasteran** [dbt-labs/dbt-core#4575] opened 2022-01-17 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not sure if it's a bug or if it's by design but the `execute` flag is set to true during the doc generation.

That means that blocks protected by `{% if execute %}...{% endif %}` are actually executed which, in my opinion, shouldn't be the case when generating the documentation.

This can (and does in my case) cause the doc generation to fail in particular conditions.

### Expected Behavior

The `execute` flag shouldn't be set to `true` during the doc generation.

The doc generation shouldn't trigger any query to be run against the database for (at least) the following reasons:
- access rights : the doc generation shouldn't need the rights to execute queries and access table data
- delays : executing queries can take some time and slow down the doc generation
- costs : executing queries on large tables can generate non-negligible costs

### Steps To Reproduce

Here is a minimal example to better understand the issue.

1. Suppose we have a model named `model_1`.
1. Suppose we have a macro `macro_1` using the [run_query](https://docs.getdbt.com/reference/dbt-jinja-functions/run_query) function to extract something from `model_1`.
1. Finally, we use this macro in another model.

Now if we generate the documentation, the macro will actually be executed and the query will be executed on the database to extract the required information from `model_1`.
If we had selected a profile+target for which the `model_1` table/view doesn't exist in the database, the doc generation will fail as the table/view is not present.

In my case, this causes the failure of the CI build that generates and publishes the dbt documentation as this pipeline is launched with it's dedicated profile/target.

### Environment

```markdown
- dbt: 0.20.0 / 1.0.1
```

### What database are you using dbt with?

bigquery

**Comment by emmyoop** [comment] 2022-01-19 19:38
Thanks for the thorough write up @pcasteran!  It always makes it easier to work out what's happening with such good examples.

Part of running `dbt docs generate` is compiling the project to `target/manifest.json` (as noted in our [docs](https://docs.getdbt.com/reference/commands/cmd-docs#dbt-docs-generate)). This ensures the docs are up to date with the current state of the project.  When we compile we are querying tables that are referenced in your macro so we can compile the sql for your second model.  We do not however materialize those queries in the database.  So a database connection is needed for `compile` to be able to query tables if needed.  Another thing to note, in case it isn’t clear, is that  `execute` is `True` during the compile command.

You can run with a flag indicating to not recompile like so `dbt docs generate --no-compile` and skip that compilation step when generating your docs.  This does assume that `target/manifest.json` already exists within your project.  

I'm going to close this issue as `execute` is true when running the `compile` command, which we do as part of `dbt docs generate`.  This is by design.  Definitely let me know if you have any questions on what I've said!

**Closed by emmyoop** 2022-01-19 19:38 UTC
Labels: bug, triage, Team:Language

**Comment by pcasteran** [comment] 2022-01-19 22:31
Thank you for your detailled answer @emmyoop.
You are absolutely right, the flag `execute` is set to `True` during the compilation phase, this is indeed stated in the [doc](https://docs.getdbt.com/reference/dbt-jinja-functions/execute).

But I think this is the core of the issue : why would the flag `execute` be `True` during compilation ? That doesn't seem logical to me, I think it should be :
- `False` during the compilation phase
- `True` only during the actual execution phase (`dbt run / test / run-operation / ...) during which the database should be accessed.

---

I'm not sure to understand what you meant by "We do not however materialize those queries in the database.".
The queries declared in a macro are indeed **actually executed in the database** during the **compilation** phase (at least with the BigQuery plug-in).

Take for example, the following files:

**_my_macro.sql_**
```sql
{% macro my_macro() %}
  {% set query %}
  SELECT MAX(<some column>) FROM <some table>
  {% endset %}

  {% if execute %}
    {# Here we want the query to actually be executed on the database. #}
    {% set result = run_query(query)[0][0] %}
    {{ return(result) }}
  {% else %}
    {# Here we do NOT want the query to be executed on the database. #}
    {# Return a default value #}
    {{ return(0) }}
  {% endif %}
{% endmacro %}
```

**_my_model.sql_**
```sql
SELECT
  {{ my_macro() }} AS foo
```

Now if I run the `dbt compile` command, I can see the `SELECT MAX ...` query being executed on BigQuery and its result present in the compiled file (`target/.../my_model.sql`).

So the compilation phase, at least with BigQuery, does actually trigger some queries to be executed on the database.

This has serious implications on several levels:

**Security**
By application of the principles of separation of concerns and least privileges, the identity used to generate the documentation should NOT have access to the tables' data, only to their metadata. This doc generation is usually performed by a dedicated CI/CD pipeline running under a dedicated identity which doesn't have access to the table data.

In my case, I even use a dedicated profile to generate the documentation, pointing to a GCP project where the tables don't even exist. In this case, the executed query fails and so does the doc generation, this is the problem I described in the first message.

**Cost controls and delays**
If some macros are used to query some big tables, the compile phase (and thus the doc generation) will generate non-negligible costs and delays.

**Data consistency**
This is the worst case. Imagine we have a macro performing DDL or DML statements. Now the compile phase (and thus the generation of the documentation), who should be a non-intrusive operation, will lead to mutate the schema and/or data in the database !!
You can modify my previous example to see that it is actually what's happening.

---

Considering all these elements, I agree to close this issue that was originally about the doc generation process. But, in my opinion, there is still a serious problem that must be addressed regarding the fact that the `execute` flag is set to `True` during the compilation phase.

**Comment by jtcohen6** [comment] 2022-01-20 09:47
Really cool conversation here @pcasteran and @emmyoop! I hope the following adds more clarity than confusion, but please let me know if it yields the opposite effect.

There are three distinct "phases" that we're discussing:
1. **Parse-time Jinja rendering.** This is when dbt first reads through your models, pulling out the values of `ref` + `source` + `config` to build its internal manifest/DAG. At this point, no database connection is required, no queries are run, and `execute` is set to `False`. (Partial parsing enables dbt to fully or partially skip this step if files/inputs are unchanged between invocations.)
2. **Model SQL compilation.** This happens only _at runtime_, and `execute` is set to `True`. A database connection is required, and any introspective queries (`statement`, `run_query`, `get_columns_in_relation`, etc) that are required as necessary inputs to template out model SQL will be run against the database.
3. **Model materialization.** Using the compiled model SQL produced in step 2, dbt will wrap that SQL in the appropriate materialization logic (`create`, `merge`, etc) and execute that logic to create/update database objects.

So:
- Tasks that _just_ parse the project and return an internal manifest, such as `dbt parse` + `dbt ls`, perform step 1 only.
- Tasks that seek to return fully compiled model SQL, such as `dbt compile` + `dbt docs generate`, perform steps 1 + 2.
- Tasks that materialize objects in the database, such as `dbt run` + `dbt build`, perform steps 1-3. (Specifically, they perform step 2-3 on a node-by-node basis, compiling-then-executing each selected resource in DAG order.)

It sounds, for good reasons, like you want your `docs generate` step to run metadata queries (required to generate `catalog.json`), but to avoid other introspective queries required to compile model SQL. I think @emmyoop's suggestion is right on: You can `dbt docs generate --no-compile`, and grab the `manifest.json` from a previous `run`/`build` invocation to use for serving docs instead. Alternatively, you could use `dbt ls` to generate that manifest _without_ running any database queries, knowing that each model's "Compiled SQL" will be missing from the resulting docs.

One final option: You can use other conditional logic, such as [`flags.WHICH`](https://docs.getdbt.com/reference/dbt-jinja-functions/flags) (returns name of current task/command), to gate statements/queries that you don't want to run during `compile` or `docs generate`. In response to your final concern:

- > Imagine we have a macro performing DDL or DML statements. Now the compile phase (and thus the generation of the documentation), who should be a non-intrusive operation, will lead to mutate the schema and/or data in the database !!

Indeed, this is an anti-pattern in dbt. All queries required for templating model SQL should be introspective _only_. All DDL/DML should be contained within the materialization logic, in order to preserve the guarantee of idempotence. The state of the database should be identical before and after `dbt compile` (from the perspective of dbt)—this is just as important as ensuring that `dbt run && dbt run` yields the same results as `dbt run`.

**Comment by pcasteran** [comment] 2022-01-26 22:44
Thank you for your detailled answer @jtcohen6. This makes a lot of sense and I know have a better understanding of the mechanisms at play during the different execution phases.

Following your final suggestion, I created the following macro to prevent some code from being executed, except when running `dbt run / test / ...`:
```python
{% macro is_actual_execution() %}
  {{ return(execute and flags.WHICH in ["run", "test", "seed", "snapshot", "run-operation"]) }}
{% endmacro %}
```

With this, I'm now able to generate the documentation in a clean environment (i.e. not relying on the artifacts of a previous execution) and using a dedicated identity with restricted privileges.

Thank again !
