### ISSUE TITLE
[Feature] Inherited column description documentation

### ISSUE THREAD

**Issue by jakemcaferty** [dbt-labs/dbt-core#4312] opened 2021-11-19 18:06 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently my company uses dbt to manage our data warehouse with data flowing from source databases to staging tables in the warehouse (staging tables are deployed in dbt) and then are ultimately combined in a series of mart level views and tables for end user's reporting and analytics.  We require all staging tables to have descriptions for every column, however we have not been able to enforce the same standards on the downstream mart tables primarily because it's just a lot of work to copy and paste descriptions multiple times.  Instead we currently rely on users tracing blank descriptions themselves if a mart level description is blank.

It would be nice if there was a setting in dbt that would allow downstream models to inherit the documentation of columns with the same names as upstream data, if the downstream description is not filled in by the user.  In the event the column is new or there is an ambiguous description (i.e. a view pulls from two tables with the same column name), dbt would simply have a blank description that would need to be filled out by the developer; otherwise it would find the last upstream table with the same column name and use that as the column description.

### Describe alternatives you've considered

Shared descriptions are an ok solution for this; we've tried migrating descriptions of staging tables into shared descriptions and using the docs function on downstream tables, but this can still be quite cumbersome and requires us to have a solid and robust naming convention for all our staged descriptions which can get confusing.  Ideally column descriptions could automatically be inherited.

Another consideration was adding a meta tag with a list of the inherited columns so users could see what columns should have inherited definitions, but this was difficult to trace and we ultimately didn't feel like it added much value in the dbt docs.

### Who will this benefit?

Anybody that uses multiple layers of data within dbt and wants to make documentation easier.

**Comment by emmyoop** [comment] 2021-12-22 16:13
Thanks for opening this up @jakemcaferty!  Having to duplicate all of the documentation is not ideal, for sure.  Inheriting column descriptions largely relates to an open discussion we're having about [Column Level Lineage](https://github.com/dbt-labs/dbt-core/discussions/4458).

Column level lineage would essentially allow dbt to know about column's properties (description, tests, meta, tags, etc) based on its upstream antecedents.  Definitely check out the discussion to get more details on what we're thinking and jump in if you have anything to add!

I'm going to close this issue as it is ultimately a duplicate of [#2995](https://github.com/dbt-labs/dbt-core/issues/2995), which is linked to [Column Level Lineage](https://github.com/dbt-labs/dbt-core/discussions/4458).

**Closed by emmyoop** 2021-12-22 16:13 UTC
Labels: enhancement, triage, Team: Language

**Comment by jakemcaferty** [comment] 2021-12-22 16:33
Thanks @emmyoop after talking to some colleagues they also mentioned that, but i kept looking for "inherit" so i missed that.  Thanks for responding and closing this out!
