### ISSUE TITLE
[CT-2177] [Regression] Version error for package fivetran/google_ads in dbt cloud 1.4.2

### ISSUE THREAD

**Issue by shaye-pearson** [dbt-labs/dbt-core#7044] opened 2023-02-24 06:58 UTC
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/29280810/221111106-139f5615-92f4-4fb9-88de-cfe647022e52.png">

### Expected/Previous Behavior

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/29280810/221111250-1f5c8e86-4212-4f65-8cf5-588bb77b591c.png">

### Steps To Reproduce

dbt deps fails in the latest release
We are currently using 1.4 (latest) so on 23 Feb 2023 with the release of 1.4.2 the failure started happening. 

### Environment

```markdown
- dbt-cloud (working version): 1.4.1
- dbt-cloud (regression version): 1.4.2
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment] 2023-02-24 08:57
@shaye-pearson Thanks for opening!

This is a duplicate of https://github.com/dbt-labs/dbt-core/issues/7039, which was reported & resolved last night. We released [v1.4.3](https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.3) with the fix. I expect that to be picked up in dbt Cloud later today.

**Closed by jtcohen6** 2023-02-24 08:57 UTC
Labels: bug, duplicate, regression
