### ISSUE TITLE
[CT-345] [Bug] dbt docs generate fail when source test present

### ISSUE THREAD

**Issue by lmmentel** [dbt-labs/dbt-core#4852] opened 2022-03-10 12:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I specify a test for a source in my `schema.yml` and run `dbt docs generate` I get 

```bash
12:07:32  Encountered an error:
Runtime Error
  Compilation Error in test source_<test_name>_<source_name>_ (models/schema.yml)
    'test_<test_name>' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```
here is my `schema.yml` (anonymized)

```yml
sources:
  - name: schema_name
    database: name
    tables:
      - name: users
        identifier: users
        tests:
          - <test_name>
        columns:
    ...
```

I have also tried to put the test at the column level but I get same result.

My test file is in `tests` folder which is added to `dbt_projects.yml` and I can run the test with `dbt test -m <test_name>`

### Expected Behavior

Documentation is generate without errors.

### Environment

```markdown
- OS:linux mint
- Python:3.9.9
- dbt:1.0.2
```

### What database are you using dbt with?

snowflake

**Comment by emmyoop** [comment] 2022-03-11 18:50
Thanks for taking the time to write this up, @lmmentel.  Is the offending test [singular](https://docs.getdbt.com/docs/building-a-dbt-project/tests#singular-tests) or [generic](https://docs.getdbt.com/docs/building-a-dbt-project/tests#generic-tests)?

I was able to reproduce this error in two ways:

1. Defining a singular tests as a property of the source in the yaml file.  Singular tests do not get defined as a property in the yaml files since they are specific, single use tests, and do not take in parameters to run.  Only generic tests are defined as a property in the yaml.
2. Putting the generic test in the `tests` directory directly instead of under `tests/generic`.  Generic tests must be inside a `generic` folder under `tests` _or_ in the `macros` directory.  If you override the `test-paths` in the `dbt_project.yml` the generic tests are expected to be nested in a `generic` directory under the directory defined as `test-paths`.

Can you confirm if either of the above cases is the reason you're running into an issue?

**Comment by lmmentel** [comment] 2022-03-11 20:04
Thanks for getting back to me on this. I believe it is scenario 1, I created a singular test in the `tests` folder and referenced it in the yaml file under the columns (I also tried table) section. What I was aiming for is documenting what tests are there and for which data source. I couldn't find a clear doc section on what to do and what not to do in this case so it seems I made some wrong assumptions. 

I understand why it might make sense to not put singular test in the yaml and I guess the recommendation is to not put sthem there :slightly_smiling_face:  However please consider that it creates an inconsistency between the different types of test.

**Comment by emmyoop** [comment] 2022-03-11 20:18
@lmmentel singular tests will show up in your generated docs as long as you use the `{{ source() }}` or `{{ ref() }}` jinja function within the test.

I'm going to close this issue since it seems to be working as intended.

**Closed by emmyoop** 2022-03-11 20:18 UTC
Labels: bug, Team:Language

**Comment by lmmentel** [comment] 2022-03-11 20:25
Thanks for the explanation.
