### ISSUE TITLE
[CT-3167] [Bug] `resource_type` selector method not returning expected results

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-core#8730] opened 2023-09-27 17:02 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

using `dbt ls -s resource_type:source` returns no results in a project with sources, while `dbt ls --resource-type source` properly returns expected results

<img width="844" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/73915542/0cc8800f-97e6-47b3-97c5-f2c4c0fc76f4">

### Expected Behavior

each method should return all sources defined in my project

### Steps To Reproduce

1. define a source
2. run `dbt ls -s resource_type:source` , see nothing
3. run `dbt ls --resource-type source` see source node

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by graciegoheen** [comment] 2023-09-27 17:12
Thanks for opening Dave! I agree, according to our [docs](https://docs.getdbt.com/reference/node-selection/methods#the-resource_type-method), this should work. 

I think the next step is to check if the `resource_type` selector is working in earlier versions - is this also not working in 1.5? 1.4?

**Comment by dbeatty10** [comment] 2023-09-27 17:26
I was able to reproduce that this doesn't work in dbt-core 1.6. Now we just need to see if it worked on 1.5 or 1.4.

**Comment by jtcohen6** [comment] 2023-09-27 17:47
I am not sure if this actually ever worked!

It looks like the code was added multiple years ago, but the docs only very recently:
- https://github.com/dbt-labs/docs.getdbt.com/issues/3549
- https://github.com/dbt-labs/docs.getdbt.com/pull/3548

I agree it would be nice if it did work, within `--select` syntax, for all commands (even ones that don't support the `--resource-type` parameter).

**Comment by graciegoheen** [comment] 2023-09-27 17:50
@jtcohen6 do you know why do we have both?

**Comment by jtcohen6** [comment] 2023-09-27 18:07
@graciegoheen I think just history, and it's worth making this more consistent. In theory we support:
```
dbt ls --select source:*
dbt ls --resource-type source
```
I don't know if we've ever actually supported:
```
dbt ls --select resource_type:source
```

**Comment by dbeatty10** [comment] 2023-09-27 19:00
Opened this issue to clarify what works currently and what doesn't:
- https://github.com/dbt-labs/docs.getdbt.com/pull/4145

**Comment by dbeatty10** [comment] 2024-02-28 02:13
Although this doesn't work in 1.5.9, it _did_ for me using 1.6.5 and 1.7.8:

```
(dbt_1.5) $ dbt ls -s resource_type:source              

02:02:21  Running with dbt=1.5.9
02:02:21  Registered adapter: postgres=1.5.9
02:02:22  Found 2 models, 1 test, 1 snapshot, 1 analysis, 310 macros, 0 operations, 1 seed file, 1 source, 1 exposure, 0 metrics, 1 group
02:02:22  The selection criterion 'resource_type:source' does not match any nodes
02:02:22  No nodes selected!

(dbt_1.6) $ dbt ls -s resource_type:source

02:02:45  Running with dbt=1.6.5
02:02:45  Registered adapter: postgres=1.6.5
02:02:45  Unable to do partial parsing because of a version mismatch
02:02:46  Found 2 models, 1 snapshot, 1 analysis, 1 seed, 1 test, 1 source, 1 exposure, 0 metrics, 352 macros, 1 group, 0 semantic models
source:my_project.my_src.my_seed

(dbt_1.7) $ dbt ls -s resource_type:source

02:03:03  Running with dbt=1.7.8
02:03:03  Registered adapter: postgres=1.7.8
02:03:03  Unable to do partial parsing because of a version mismatch
02:03:04  Found 2 models, 1 snapshot, 1 analysis, 1 seed, 1 test, 1 source, 1 exposure, 0 metrics, 401 macros, 1 group, 0 semantic models
source:my_project.my_src.my_seed
```

Quickly scanning the changelogs for [1.6](https://github.com/dbt-labs/dbt-core/blob/1.6.latest/CHANGELOG.md) and [1.7](https://github.com/dbt-labs/dbt-core/blob/1.7.latest/CHANGELOG.md), I don't know what changed to cause this to work now though.

I'm going to close this as "magically resolved". If someone knows the right PR to link this to, please share! 🙏 

Also opened https://github.com/dbt-labs/docs.getdbt.com/issues/5003 to update the docs.

**Closed by dbeatty10** 2024-02-28 02:13 UTC
Labels: bug

**Comment by graciegoheen** [comment] 2024-02-28 14:58
@dbeatty10 We should make sure we have a test in place so that this doesn't "magical break" in the future!
