### ISSUE TITLE
[CT-757] [Feature] Add a "merge_ignore_columns" config for incremental models

### ISSUE THREAD

**Issue by christoph-meier-offerup** [dbt-labs/dbt-core#5387] opened 2022-06-16 19:37 UTC
### Is this your first time opening an issue?
Yes

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Currently, the ```merge_update_columns``` config for incremental models can be used to define which columns a merge statement should update. 

The opposite behavior (to _ignore_ a column) is achieved by omitting a column in this config. I've seen bugs being introduced into models many times when their logic changes and not enough attention is paid to the config block (omission is much harder to work with than an explicit config).

It would be useful to explicitly name columns that should be ignored. This could be implemented with a config called ```merge_ignore_columns``` (or similar).

This is useful for auditing columns like ```etl_created_timestamp```. The value of this column should be determined when a record is first inserted, but should never be updated afterwards.

If both ```merge_update_columns``` and ```merge_ignore_columns``` configs are set and a column is in both, an exception should be raised.

### Describe alternatives you've considered

None

### Who will this benefit?

This feature would help make the config block more compact (especially in cases where a table has a large amount of columns), as well as add clarity by explicitly calling out the behavior of a column, instead having the behavior be determined by omission.

### Are you interested in contributing this feature?

I don't know enough about dbt core to feel comfortable contributing (yet)

**Comment by jtcohen6** [comment] 2022-06-17 13:16
@christoph-meier-offerup Totally! Thanks for opening. I'm going to close this issue only because it's a duplicate of another recent issue, asking for the same functionality: https://github.com/dbt-labs/dbt-core/issues/5260

**Closed as not planned by jtcohen6** 2022-06-17 13:16 UTC
Labels: duplicate, enhancement
