### ISSUE TITLE
[CT-448] [Bug] dbt deps does not pass the -t option to the compiler

### ISSUE THREAD

**Issue by dweaver33** [dbt-labs/dbt-core#4985] opened 2022-03-31 20:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `dbt deps -t [env]`, the command does not seem to pass the value of `[env`] to the compiler.  This results in unexptected behavior when parsing the `dbt_project.yml` file as any jinja statements using the `target` variable will not be evaluated.

### Expected Behavior

The command should send the target string to the compiler so the `target` jinja variable is properly parsed.

### Steps To Reproduce

1. Start a new dbt project
2. Edit the `dbt_project.yml` file with something like the below:
```yaml
log-path: "{{ '/blah/blah' if target.name == 'prod' else 'logs' }}"
```
3. Run the command `dbt deps -t prod`
4. Observer that the `logs` directory is created in the project root and not `/blah/blah` as expected

### Environment

```markdown
- OS: macOS 12.3 (21E230)
- Python: 3.9.10
- dbt: 

installed version: 1.0.3
   latest version: 1.0.4

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.0.0 - Up to date!
```

### What database are you using dbt with?

snowflake

**Comment by emmyoop** [comment] 2022-04-01 20:47
@dweaver33 thanks for opening this up and providing a nice slimmed down way to reproduce your issue.  This is something we are aware of and have opened an issue to resolve.  In v1.0.3 we removed the need for `deps`/`clean` commands to need a profile.  This resulted in the behavior you're experiencing with the target. 

I'm going to close this as duplicate of #4780 but feel free to comment over there if you have anything more to add!

**Closed by emmyoop** 2022-04-01 20:47 UTC
Labels: bug, triage, Team:Language

**Comment by dweaver33** [comment] 2022-04-01 22:31
Thanks for the response @emmyoop!  I guess a fix would be a way to specify on the CLI the log path.

**Comment by jtcohen6** [comment] 2022-04-04 11:04
@dweaver33 Fair! We had an issue/PR to do that, though I think it got stuck in the maelstrom of code refactor leading up to v1.0: https://github.com/dbt-labs/dbt-core/pull/3868

Another option is passing `{{ env_var() }}` to `log-path` in `dbt_project.yml`, since env vars are always available to dbt's rendering contexts, and you have full control over its value across environments.
