### ISSUE TITLE
[CT-2406] [Regression] dbt build -s 3+model_name is running ALL models upstream

### ISSUE THREAD

**Issue by Mathyoub** [dbt-labs/dbt-core#7345] opened 2023-04-12 22:42 UTC
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

`dbt run -s 2+some_model` and `dbt build -s 2+some_model` return a different number of models

Confirmed this is also happening in the other direction, ie. 

`dbt run -s some_model+2`  and `dbt build -s some_model+2` return a different number of models

### Expected/Previous Behavior

only parental models and tests within 3 nodes should run, yet all parental models and tests are running

### Steps To Reproduce

`dbt run -s 3+some_model` runs as expected with the 3 levels of upstream parents

`dbt build -s 3+some_model` runs ALL the upstream parents.

### Environment

```markdown
- OS:
- Python:
- dbt (working version):
- dbt (regression version):
```

### Additional Context

There is a loom video on the Jira card showing the issue as well.

**Comment by jtcohen6** [comment] 2023-04-12 22:45
@Mathyoub Is this the same as https://github.com/dbt-labs/dbt-core/issues/5193? I agree it's unexpected behavior, but I'm not sure that it's a regression in a new/recent version of `dbt-core`

**Comment by jtcohen6** [comment] 2023-04-21 15:55
Closing as a duplicate of #5193

**Closed by jtcohen6** 2023-04-21 15:55 UTC
Labels: bug, duplicate
