### ISSUE TITLE
[CT-2268] [Bug] dbt-core >= 1.4.2 manifests not passing v8 schema validation

### ISSUE THREAD

**Issue by dlawin** [dbt-labs/dbt-core#7119] opened 2023-03-03 21:51 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm noticing that manifests generated by dbt-core versions 1.4.2, 1.4.3, and 1.4.4 are not passing json schema validation based on the schema here: 
- https://schemas.getdbt.com/dbt/manifest/v8.json

### Expected Behavior

I would expect this validation to pass or for a v9 manifest to be available.

### Steps To Reproduce

1. Generate manifest.json for one of the mentioned versions (I used jaffle_shop)
2.
```
import json
from jsonschema import validate
import yaml
import requests
manifest_path = "/Users/dan/Desktop/manifest.json"
r = requests.get(url = "https://schemas.getdbt.com/dbt/manifest/v8.json")

schema_str = r.content

schema = json.loads(schema_str)
with open(manifest_path, "r", encoding="utf-8") as fp:
            manifest_dict = yaml.safe_load(fp)

validate(
    instance=manifest_dict
    , schema=schema
)
```

### Relevant log output

```shell
'seed' is not one of ['analysis']

Failed validating 'enum' in schema[0]['properties']['resource_type']:
    {'enum': ['analysis'], 'type': 'string'}

On instance['resource_type']:
    'seed'
```

### Environment

```markdown

- OS: OSX 13.2
- Python 3.10.9
- dbt-core: 1.4.2, 1.4.3, 1.4.4
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Noticed this with any adapter I tested: snowflake, redshift, postgres, databricks

**Comment by jtcohen6** [comment] 2023-03-03 21:59
There are some known problems with the library (`hologram`) we're currently using to auto-generate JSONSchemas from our Python dataclasses. This was a previous bug report that sounds similar:
- https://github.com/dbt-labs/dbt-core/issues/4657

More discussion:
- #6776
- https://github.com/dbt-labs/dbt-core/discussions/6915#discussioncomment-4918721

**Comment by dlawin** [comment] 2023-03-03 22:06
For context, I contribute to a couple open source tools that utilize these artifacts and their json schemas:
https://github.com/yu-iskw/dbt-artifacts-parser

Subsequently using that in:
https://github.com/datafold/data-diff

For now I think I will need to limit to a version < 1.4.2

**Comment by gshank** [comment] 2023-03-03 22:49
I suspect that the problem is not with the manifest.json or even with the jsonschema, but with the fact that the jsonschema validate function cannot distinguish between types of nodes and is validating using the wrong part of the schema. In our Python code we have to explicitly load serialized nodes by resource_type, or we end up with incorrectly instantiated nodes. Jsonschema validate with only dictionary input is probably not capable of using the right part of the schema. 

I looked at the local copies of the generated schemas, and they are correct for resource_type. From the lines included above, it looks like jsonschema is validating a seed node using the analysis node schema.

What is the goal of doing the jsonschema validate? Perhaps there's something else that can serve the same purpose.

**Comment by gshank** [comment] 2023-03-03 22:52
I think that the jsonschemas serve more as documentation of what to expect in the manifest.json. I don't think that it can be usefully used to validate the whole manifest. If you want to go through and validate the individual nodes and call out the correct nodes by resource_type, that might possibly work.

**Comment by dlawin** [comment] 2023-03-06 19:28
> What is the goal of doing the jsonschema validate? Perhaps there's something else that can serve the same purpose.

The validation is not actually the goal, the jsonschema is used to parse files to objects for manifest, run results, and sources here. (it uses https://koxudaxi.github.io/datamodel-code-generator/ to generate the object code)

https://github.com/yu-iskw/dbt-artifacts-parser

**Comment by dlawin** [comment] 2023-03-06 19:29
> I think that the jsonschemas serve more as documentation of what to expect in the manifest.json. I don't think that it can be usefully used to validate the whole manifest. If you want to go through and validate the individual nodes and call out the correct nodes by resource_type, that might possibly work.

To that end, I could probably update the generated classes here so that they handle the seeds https://github.com/yu-iskw/dbt-artifacts-parser/blob/main/dbt_artifacts_parser/parsers/manifest/manifest_v8.py

**Comment by harshach** [comment] 2023-03-08 18:27
@gshank,  How can a client depend on any schema if it's not expected to validate the resulting file based on a schema?  Are there other schemas we can rely on to parse manifest and catalog files?

**Comment by yu-iskw** [comment] 2023-03-09 13:04
@gshank BTW, can you tell me how you usually generate the JSON schemas like https://github.com/dbt-labs/dbt-core/tree/main/schemas/dbt/manifest locally?

**Comment by dlawin** [comment] 2023-03-10 22:45
Oh I see, the updated version is not hosted [here](https://schemas.getdbt.com/dbt/manifest/v8.json)

e.g. doesn't match https://raw.githubusercontent.com/dbt-labs/dbt-core/main/schemas/dbt/manifest/v8.json (accurate one)

**Comment by jtcohen6** [comment] 2023-03-17 17:56
> Oh I see, the updated version is not hosted [here](https://schemas.getdbt.com/dbt/manifest/v8.json)

> e.g. doesn't match https://raw.githubusercontent.com/dbt-labs/dbt-core/main/schemas/dbt/manifest/v8.json (accurate one)

I think this one is on me!! https://github.com/dbt-labs/schemas.getdbt.com/pull/19

Just merged :)

**Closed** 2023-03-17 17:56 UTC
Labels: bug, artifacts, Team:Language

**Comment by yu-iskw** [comment] 2023-03-17 21:08
@jtcohen6 thank you. I will check the hosted schema is updated later.

BTW, can you please tell me that, if you know? As I contributed to improving a schema before, I would like to know how to update the schema too.
https://github.com/dbt-labs/dbt-core/issues/7119#issuecomment-1464588457
