### ISSUE TITLE
[CT-1493] [Bug] Cache miss when `adapter.get_relation` is call in a loop in a macro

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#6237] opened 2022-11-10 22:56 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi all - just checking to see if we should be missing the cache when calling `adapter.get_relation` in a loop.

### Expected Behavior

No cache miss.

### Steps To Reproduce

Project setup:

```yaml
# dbt_project.yml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "snowflake"
models:
  my_dbt_project:
    +materialized: table

# models/sources.yml
version: 2
sources:
  - name: dbt_jyeo
    tables:
      - name: source_bar
      - name: source_baz
      - name: source_qux
```

```sql
-- macros/check_source.sql
{% macro check_source_simple() %}
    {% if execute %}
        {% for node in graph.sources.values() %}
          {% do log(adapter.get_relation(database=node.database, schema=node.schema, identifier=node.identifier)) %}
        {% endfor %}
    {% endif %}
{% endmacro %}

-- models/foo.sql
select 1 as id
```

Run an operation:

```
$ dbt --debug run-operation check_source | grep 'cache miss\|show terse'
```

### Relevant log output

```shell
22:32:26.333410 [debug] [MainThread]: On "macro_check_source": cache miss for schema "{self.database}.{self.schema}", this is inefficient
show terse objects in development.dbt_jyeo
22:32:28.725112 [debug] [MainThread]: On "macro_check_source": cache miss for schema "{self.database}.{self.schema}", this is inefficient
show terse objects in development.dbt_jyeo
22:32:29.124835 [debug] [MainThread]: On "macro_check_source": cache miss for schema "{self.database}.{self.schema}", this is inefficient
show terse objects in development.dbt_jyeo
```

### Environment

```markdown
- OS: macOS
- Python: 3.8.7
- dbt: 1.3
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Interestingly if we use the macro in a hook we don't get cache misses.

```yaml
# dbt_project.yml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "snowflake"
models:
  my_dbt_project:
    +materialized: table

on-run-end: "{{ check_source() }}"
```

```sh
$ dbt --debug run | grep 'cache miss\|show terse'
show terse schemas in database development
show terse objects in development.dbt_jyeo
```

**Comment by jtcohen6** [comment] 2022-11-13 08:50
Thanks for opening @jeremyyeo, and for the really clear reproduction case!

The goal of the relation cache is to provide dbt with the information it needs to efficiently and effectively **materialize models as relations**. There are two separate & related reasons why the code in the example is yielding cache misses:
1. We don't populate the cache for `run-operation` _at all_, because it doesn't execute any materializations. (`build` & company all do this. `compile` is a slightly different story, but still inherits from `RunnableTask`, which [populates the cache](https://github.com/dbt-labs/dbt-core/blob/73116fb816498c4c45a01a2498199465202ec01b/core/dbt/task/runnable.py#L416-L418) as part of task startup.)
2. We don't cache schemas containing `sources` _at all_, because dbt doesn't materialize sources. It doesn't expect to need to know whether the source table exists or not, exists as a view instead of a table, etc.

So, short answer - yes, this is expected.

---

There are two fair questions here:
- Should we cache information about source tables? Maybe, in a future where dbt were really responsible for materializing them (e.g. as external tables).
- Should the "cache miss" query update the cache, so that subsequent calls can be hits rather than misses? In other words, should we change this line:

https://github.com/dbt-labs/dbt-core/blob/ff2f1f42c394d27ff8d49ca7e285fcf2b76faa05/core/dbt/adapters/base/impl.py#L713-L735

To something like:
```python
    def list_relations(self, database: Optional[str], schema: str) -> List[BaseRelation]:
        if self._schema_is_cached(database, schema):
            return self.cache.get_relations(database, schema)

        schema_relation = self.Relation.create(
            database=database,
            schema=schema,
            identifier="",
            quote_policy=self.config.quoting,
        ).without_identifier()

        relations = self.list_relations_without_caching(schema_relation)
        
        # if the cache is already populated, add this schema in
        # otherwise, skip updating the cache and just ignore
        if self.cache:
            for relation in relations:
                self.cache.add(relation)
            if not relations:
                # it's possible that there were no relations in some schemas. We want
                # to insert the schemas we query into the cache's `.schemas` attribute
                # so we can check it later
                cache_update: Set[Tuple[Optional[str], Optional[str]]] = set()
                for relation in cache_schemas:
                    cache_update.add((database, schema))
                self.cache.update_schemas(cache_update)

        return relations
```
So that the example above yields only one miss, rather than three?
```
$ dbt --debug run-operation check_source | grep 'cache miss'
08:47:15.852512 [debug] [MainThread]: On "macro_check_source": cache miss for schema "jerco.dbt_jyeo", this is inefficient
```

I'm not totally sure. That code annotation is pretty direct ("we can't build the relations cache here"), but it's also _super_ old (https://github.com/dbt-labs/dbt-core/commit/f4afd495ad8164cdf034e36528ce3b635a2fba92), from the very PR that added the relations cache in the first place.

I'll open a separate issue for this!

--- 

Bonus bug: it looks like there's an extra set of quotes in the `message` for `CacheMiss`, such that it always prints out as:
```
cache miss for schema "{self.database}.{self.schema}", this is inefficient
```

I think this:
https://github.com/dbt-labs/dbt-core/blob/68d06d8a9cea28600ed9c3f375605c9467247316/core/dbt/events/types.py#L539-L543
Is just missing an important letter `f`:
```python
 def message(self) -> str: 
     return ( 
         f'On "{self.conn_name}": cache miss for schema ' 
         f'"{self.database}.{self.schema}", this is inefficient' 
     ) 
```

---

I'm going to close this one out, in favor of the more specific issues to come.

**Closed by jtcohen6** 2022-11-13 08:50 UTC
Labels: bug

**Comment by jtcohen6** [comment] 2022-11-13 09:02
New issues:
- https://github.com/dbt-labs/dbt-core/issues/6240
- https://github.com/dbt-labs/dbt-core/issues/6241
