### ISSUE TITLE
[CT-2665] [Regression] For the list command the path selector does not respect the --project-dir param

### ISSUE THREAD

**Issue by rudeb0y** [dbt-labs/dbt-core#7819] opened 2023-06-07 19:48 UTC
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

in dbt 1.5.1, the `path` selector does not seem to work with `--project-dir`. 

that is, given a directory structure:
- dbt_projects
  - project1
  - project2
  
from the dbt_projects root, the following works in 1.4.6 but not 1.5.1.

### Expected/Previous Behavior

I expect the path selector to work as in the previous versions of dbt.

### Steps To Reproduce

1. in a dbt-core==1.5.1 environement..
2. with a root/<dbt_projects> structure
3. from root, try to `dbt ls -s path:path/to/models/dir/ --project-dir <one of the dbt_sub_projects>`
4. it will find no nodes.

repeat this for dbt-core==1.4.6 which will find the expected nodes

### Environment

```markdown
- OS: macOS
- Python: 3.11.1
- dbt (working version): 1.4.6
- dbt (regression version): 1.5.1
```

### Which database adapter are you using with dbt?

snowflake

**Comment by rudeb0y** [comment] 2023-06-07 20:01
non-

**Comment by dbeatty10** [comment] 2023-06-08 02:29
Thanks for reporting this @rudeb0y.

This is legit, and I was able to reproduce it as you described 👍

It's possible this is similar to https://github.com/dbt-labs/dbt-core/issues/7465 (but unique).

<details>
<summary>

### Reprex</summary>

Tree structure:
```
dbt_projects
└── project1
    ├── dbt_project.yml
    └── models
        └── my_model.sql
```

`dbt_projects/project1/models/my_model.sql`
```sql
select 1 as id
```

This works with dbt 1.4:
```shell
$ dbt ls --project-dir dbt_projects/project1 -s path:models

my_project.my_model
```

But not 1.5:
```shell
$ dbt ls --project-dir dbt_projects/project1 -s path:models

02:19:46  Running with dbt=1.5.0
02:19:47  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 307 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
02:19:47  The selection criterion 'path:models' does not match any nodes
02:19:47  No nodes selected!
```

</details>

**Comment by radium226** [comment] 2023-08-14 12:33
Hello! I think this issue should be reopened: it does not work anymore with dbt 1.5.4 and dbt 1.6.0

**Comment by gshank** [comment] 2023-08-14 14:16
This happened because setting the contextvar was moved to a contextmanager on the runnable run method. The list command doesn't inherit from that, so it needs it's own contextmanager.

**Comment by jtcohen6** [comment] 2023-08-14 15:59
Closing in favor of more specific issue:
- https://github.com/dbt-labs/dbt-core/issues/8385

**Closed by jtcohen6** 2023-08-14 15:59 UTC
Labels: bug, regression
