### ISSUE TITLE
[Feature] Update error message for unit tests when there's a schema mismatch between the model and the expected output

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#10013] opened 2024-04-23 04:07 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Given the unit test spec:

```yml
unit_tests:
  - name: identical_records_compare_queries
    given:
      - input: ref('unit_test_model_a')
        rows:
          - { "id": 1, "col1": "abc", "col2": "def" }
          - { "id": 2, "col1": "hij", "col2": "klm" }
          - { "id": 3, "col1": "nop", "col2": "qrs" }
      - input: ref('unit_test_model_b')
        rows:
          - { "id": 1, "col1": "abc", "col2": "def" }
          - { "id": 2, "col1": "hij", "col2": "klm" }
          - { "id": 3, "col1": "nop", "col2": "qrs" }
        
    expect:
      rows:
        - {"id": 1, "in_a": true, "in_b": true}
```

When i ran the unit test against a model that didn't return the `id` column, I got this error: 

```
03:07:10    Runtime Error in unit_test identical_records_compare_queries (models/unit_test_wrappers/unit_tests.yml)
  An error occurred during execution of unit test 'identical_records_compare_queries'. There may be an error in the unit test definition: check the data types.
   Compilation Error in unit_test identical_records_compare_queries (models/unit_test_wrappers/unit_tests.yml)
    Invalid column name: 'id' in unit test fixture for expected output.
    Accepted columns for expected output are: ['in_a', 'in_b', 'count', 'percent_of_total']
    
    > in macro format_row (macros/unit_test_sql/get_fixture_sql.sql)
    > called by macro get_expected_sql (macros/unit_test_sql/get_fixture_sql.sql)
    > called by macro materialization_unit_default (macros/materializations/tests/unit.sql)
    > called by unit_test identical_records_compare_queries (models/unit_test_wrappers/unit_tests.yml)
```

Saying that the `id` column is invalid, and that accepted columns are the set of columns returned by the query, is completely backwards.
<img width="489" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/7335046/25870362-3d6b-442c-ae78-830a67d352c1">

### Expected Behavior

The error message to be more like "Column id was expected in results but not found. Found columns are: ['in_a', 'in_b', 'count', 'percent_of_total']"

### Steps To Reproduce

Make a unit test as described above 
Run it against a model that contains no id column 
Note the incorrect error message

### Environment

```markdown
- OS:
- Python:
- dbt: dbt-core@2edd5b3335ddea4ca5e7dd8aaa3bfe3a5d30499a (using Core on main as of about 5 days ago, roughly equivalent to the 1.8 beta)
```

**Comment by dbeatty10** [comment] 2024-04-23 12:17
Hey @joellabes !

Could you include your model definitions for the relevant models?
- `unit_test_model_a`
- `unit_test_model_b`
- `identical_records_compare_queries`

And also share more about why this seems like a bug in dbt to you?

It would be helpful if you can describe what ended up being off in your project files and what you did to resolve it.

### Error message

Here's the current error message:
```
    Invalid column name: 'id' in unit test fixture for expected output.
    Accepted columns for expected output are: ['in_a', 'in_b', 'count', 'percent_of_total']
```

And here's your proposed error message:
```
    Column id was expected in results but not found.
    Found columns are: ['in_a', 'in_b', 'count', 'percent_of_total']
```

### Two possibilities for schema mismatches

When creating a new model and an associated unit from scratch, there's two possibilities that can lead to a schema mismatch between the model and the expected output:
1. The model contains all the intended columns, but the unit test is missing one or more
2. The expected rows in the unit test contains all the intended columns, but the model is missing one or more

Maybe you're proposing that we need more inclusive language in the error message that covers both of those possibilities?

**Comment by joellabes** [comment] 2024-04-24 06:15
```
-- models/unit_test_placeholder_models/unit_test_model_a.sql
select 1 as id, 'xyz' as col1, 'tuv' as col2, 123 as col3, getdate() as created_at
```

```
-- models/unit_test_placeholder_models/unit_test_model_b.sql
select 1 as id, 'xyz' as col1, 'tuv' as col2, 123 as col3, getdate() as created_at
```

(yes, a and b are intentionally identical. These are wrappers so I can test the macro)

```
--models/unit_test_wrappers/unit_compare_queries.sql
{{ 
    audit_helper.compare_queries(
        "select * from " ~ ref('unit_test_model_a'),
        "select * from " ~ ref('unit_test_model_b'),
        summarize = var('compare_queries_summarize')
    ) 
}}
```



> It would be helpful if you can describe what ended up being off in your project files and what you did to resolve it.

It _just so happens_ that this was failing due to a misconfigured unit test (the `id` column was never meant to be in the result set), but for the sake of this discussion we can pretend that the test _was_ meant to have an id column and didn't get one.

> * The model contains all the intended columns, but the unit test is missing one or more

This doesn't throw an error, and it shouldn’t! If my unit test spec expects expects column1 and column2, and receives column1, column2 and column3, that's totally fine and aligns with unit tests' principles of not having to provide a bunch of redundant definitions for values that you don't care about testing in the context of a given test. 

> 2\. The expected rows in the unit test contains all the intended columns, but the model is missing one or more

This one is what caused my test to fail - I asked for columns id, in_a and in_b, and actually received in_a, in_b, count and percent_of_total. 

So far so good - the test failed because the id column (that I specifically named) chose not to show up for work. 

The reason I think this is a bug is the way the response is phrased. 
- It says `Invalid column name: 'id'`, but the column name isn't invalid. It's a valid expectation that wasn't met.
- It also says `Accepted columns for expected output are: ['in_a', 'in_b', 'count', 'percent_of_total']`, but the accepted columns in the output are defined by the unit test. The outputs don't define what's accepted, they define what's available for comparison against the expectations.

In image form: 

![image](https://github.com/dbt-labs/dbt-core/assets/7335046/578b2784-784d-4e93-b67c-ec91d96d268a)

**Comment by dbeatty10** [comment] 2024-04-24 12:22
Thanks for that explanation, code, and visual aid -- very helpful 💡

It looks like there's some subtle language distinctions here.

Since dbt-core isn't _behaving_ incorrectly or have a _gross_ misrepresentation in the error message, I'm going to recategorize this as a feature request and label it as refinement to determine which tweaks to make.

**Comment by graciegoheen** [comment] 2024-04-24 17:14
Just to recap and confirm my understanding. The issue is you defined mock data in `expect` for a field (`id`) that **does not actually exist** in the model you're unit testing. 

The error you get is:
```
    Invalid column name: 'id' in unit test fixture for expected output.
    Accepted columns for expected output are: ['in_a', 'in_b', 'count', 'percent_of_total']
```

This error makes sense to me. I'm going to close this for now, but if there's additional folks who find this confusing we can revisit.

**Closed by graciegoheen** 2024-04-24 17:14 UTC
Labels: enhancement, Refinement, unit tests

**Comment by joellabes** [comment] 2024-04-25 00:22
>field (id) that does not actually exist in the model you're unit testing.

It doesn't exist, but it should, and I'm testing to ensure that it does. 

When the error message says "accepted columns [...] are ['in_a', 'in_b', 'count', 'percent_of_total']", that sounds like the list of options that are valid for comparison, which is backwards. 

If I configured a test: 

```yml
models: 
  - name: my_model
    columns: 
      - order_status: 
        tests: 
          - accepted_values: 
            values: ['ordered', 'shipped', 'returned']
```

and had 

```sql
-- models/my_model.sql
select 1 as id, 'ordered' as order_status
union all 
select 2 as id, 'delivered' as order_status
```

and the `dbt test` output said "Accepted values for expected output are ['ordered', 'delivered']", that would make no sense. My objection is to calling the columns the "accepted" columns.
