### ISSUE TITLE
[CT-744] [Bug] document for test

### ISSUE THREAD

**Issue by bachng2017** [dbt-labs/dbt-core#5363] opened 2022-06-11 12:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`dbt docs generate` does not generate correct description for tests in `tests` folder.

### Expected Behavior

With current yml, dbt docs should create correct description for the test
```yaml: schema.yml
---
version: 2
tests:
  - name: a_test
    description: this is a test
```

### Steps To Reproduce

- create a sql and correspond yam in tests folder
  ```yaml: schema.yml
  ---
  version: 2
  tests:
    - name: a_test
      description: this is a test
  ```
- run `dbt docs generate`
- check the document by browser

### Relevant log output

```shell
no error just usual logs

12:38:43  Running with dbt=1.1.0
12:38:43  Found 4 models, 1 test, 0 snapshots, 0 analyses, 151 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics
12:38:43
12:38:43  Concurrency: 1 threads (target='test')
12:38:43
12:38:44  Done.
12:38:44  Building catalog
12:38:44  Catalog written to [my_path]/sample/target/catalog.json
```
```


### Environment

```
- OS: Ubuntu
- Python: 3.8
- dbt: 1.1.0
```


### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

trino/hive

**Comment by jtcohen6** [comment] 2022-06-13 10:50
Hey @bachng2017, thanks for opening!

Adding a `description` to tests actually isn't something that dbt supports today, although it's been on our minds for some time:
- https://github.com/dbt-labs/dbt-core/issues/2578
- https://github.com/dbt-labs/dbt-core/issues/3249

To clarify what you're after, are you trying to add a description to a "singular" test (one-off `.sql` file defined in `tests/`), or a "generic" test (macro-like, reused across your project)? We'd like to eventually support both, and the latter requires a bigger lift.

_Meta note:_ I'm going to close this issue as a duplicate of those two linked above, but I am still curious to hear more about your intended use case!

**Closed by jtcohen6** 2022-06-13 10:50 UTC
Labels: duplicate, enhancement, tests

**Comment by bachng2017** [comment] 2022-06-15 14:16
thanks for the comments and sorry about the duplication. I mention about the "singular" test. For the generic test, it could be document fine likes other macros.

As you mention the feature is not planned., it OK. My point is that, currently `dbt docs generate` generates the page like this for a singular test. It makes confused that somehow you are supporting the feature.
<img width="1195" alt="スクリーンショット 2022-06-15 23 10 52" src="https://user-images.githubusercontent.com/31262506/173849186-9f606166-0fca-486b-8f7a-5179e382de1b.png">

will check the tickets above but just wonder why support test document is not planned :) Because for testing, document is vital imho

**Comment by johalnes** [comment] 2022-09-26 07:43
Having used some hours, with the occasional thinking of how stupid am I to not be able to make this work, I'll second @bachng2017 in that the description is confusing. I was 100% sure this should work because of that description text. 

@jtcohen6 - Coming from financial reporting, beeing able to test is perfect. But there is a lot of filtering to be able to test a company's financial statement vs detailed reporting, and from experience this logic will be forgotten sometime early in 2023. Making this feature almost as important as describing models and macros.
