### ISSUE TITLE
[CT-1338] [Bug] generate_schema_name not available for sources

### ISSUE THREAD

**Issue by jayhale** [dbt-labs/dbt-core#6056] opened 2022-10-12 21:00 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using a source configuration like this:
```yml
version: 2
source:
  - name: source_a
    schema: "{{ generate_schema_name("BRONZE") }}"
    # ...
```

compiling the project fails:
```
dbt.exceptions.CompilationException: Compilation Error
  Could not render {{ generate_schema_name('BRONZE') }}: 'generate_schema_name' is undefined
```

and requires a workaround like:
```yml
version: 2
source:
  - name: source_a
    schema: "{{ 'bronze' if target.name.startswith('prod') else target.schema }}"
    # ...
```

### Expected Behavior

`generate_schema_name` should be available for source configuration similar to the way it can be used for model configuration.

### Steps To Reproduce

See above

### Environment

```markdown
- OS: OSX
- Python: 3.10
- dbt: 1.2.2
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Related: https://github.com/dbt-labs/dbt-core/issues/4753

**Comment by china-cse** [comment] 2022-10-16 01:18
I guess generate_schema_name is purely for target schemas where models gets created. If you want to change source schema names per environment , you could use environment variabels.

source:
  - name: source_a
  - schema: "{{ env_var('DBT_SOURCE_SCHEMA','default_schema') }}'

**Comment by jtcohen6** [comment] 2022-10-18 11:28
Thanks for opening, and linking to https://github.com/dbt-labs/dbt-core/issues/4753! That was the last thorough discussion we had about this topic.

There are two paths we could take here:
- Supporting / extending a pattern akin to `generate_schema_name` for sources — I'll be honest, I'm hesitant, as the implicit behavior of `generate_schema_name` is tricky to understand and trips up lots of users
- Supporting simple "pure" macros for configuration in `.yml` files, so that a macro like `generate_schema_name` could be supplied expicitly

I'm going to close this issue for now as a duplicate of #4753, so that we can keep the conversation centralized over there.

**Closed by jtcohen6** 2022-10-18 11:28 UTC
Labels: bug, duplicate
