### ISSUE TITLE
[CT-2823] [Feature] Run Downstream models on-schema-change

### ISSUE THREAD

**Issue by sp-tkerlavage** [dbt-labs/dbt-core#8090] opened 2023-07-13 14:22 UTC
### Is this your first time submitting a feature request?
No

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I have a project that has incremental models that have the `on_schema_change = 'append_new_columns'` config. 

Downstream of these models I have views that use the `dbt_utils.star` macro to dynamically "hard code" a list of columns for each view. We use the `dbt_utils.star` macro  this instead of just a simple `SELECT * FROM {{ ref(incremental_model') }} ` so that our views in Snowflake don't break as soon as a schema change occurs in the underlying incremental model. 

Up until a few days ago we were just running the views in our main job. So the views were always recreated right after the incremental model which means they would always include any new columns that were added to the incremental model. However, I realized that we're essentially wasting compute by doing this. We have hundreds of views and we run our job hourly. By contrast, we might only see one column added to one of the incremental model every week or so. 

I was wondering if theres a way of running downstream models only when a schema change occurs in the upstream ref?

### Describe alternatives you've considered

My first thought was to just do deferral/`state:modified comparison, but I actually haven't been able to get that to work in this scenario. I think state:modified comparison looks at the body of the sql file. Since the body of the sql file isn't actually changing (its still just calling a macro), state comparison doesn't pick it up. Forgive me if this functionality is currently possible. 

Another sort of hacky idea was to just have the views disabled by default, and actively enable them during runtime. I didn't really get too far into actually conceptualizing how this would even work because it seems not possible on the face of it:
https://github.com/dbt-labs/docs.getdbt.com/discussions/1310

Right now, we've just removed the views from our hourly job. We now just have a separate job for the views that runs every 12 hours. This is a sort of "eventually consistent" approach which is probably fine for our use case. Realistically the consumers of the views probably don't even know a new column exists, so the lag between the column being available in our incremental table to it being exposed in the view is fine.

### Who will this benefit?

People that have lots of views on top of incremental models that have fluid schemas.

**Comment by graciegoheen** [comment] 2023-07-17 18:04
Thanks for detailing this enhancement! I think there are a few potential solutions here - it would be great if you could share a basic, reproducible example so that I can understand the full details.

The way Snowflake handles `select * from ...` views is different from other warehouses, where the `select * from ...` view breaks if the underlying table's schema changes - so it makes sense that you're trying to use the `dbt_utils.star` macro here.

I think there are a few ways you can handle this with current dbt-core functionality:
1. Instead of using `state:modified` to select the models that have changed, you could use `state:modified+` which would select the models that have changed _and their downstream dependencies_. While this may occasionally over-select views (imagine you've modified the incremental model's logic, but haven't actually added any new columns... the downstream views will still be re-created), this will _always_ include all of the views you need and would be a performance improvement over running _all_ of the views in your project.
2. You could add a contract to your incremental models, and then use `state:modified.contract+` to select models with changes to their contacts _and their downstream dependencies_. This would further slim down the number of views/models that are selected, because `state:modified.contract` is limited to changes in the `name` and `data_type` of columns on a contracted model. 
3. Instead of using the `dbt_utils.star` macro, you could just hard-code the columns in your views (`select column_a, column_b, column_c from {{ ref('my_incremental_model') }}`. This way, if you add a new column to your incremental model, you _will_ also have to change the code in your downstream views to add the new columns - in that case it will be selected by `state:modified`.

I'm going to close this as not planned because I think you should be able to solve this with the current dbt-core functionality, but let me know if there's any context I'm missing or if you run into any further issues!

**Closed by graciegoheen** 2023-07-17 18:04 UTC
Labels: enhancement, triage
