### ISSUE TITLE
Add support for sql.j2

### ISSUE THREAD

**Issue by Gregory108** [dbt-labs/dbt-core#3664] opened 2021-07-30 22:17 UTC
Developing in DBT means writing in a combination of database-specific SQL dialect and jinja2. At least, VSCode with Better Jinja plugin is able to help with prompts and check syntaxis of both languages simultaneously - iff model file extension is .sql.j2. However, dbt does not recognise such files as model.

Suggestion:
- make `dbt run [-m]` work agnostic of anything after .sql extension suffix

**Comment by jtcohen6** [comment] 2021-08-03 01:05
@Gregory108 Thanks for the issue! We've got a very similar one open: https://github.com/dbt-labs/dbt/issues/3484, which is in progress in https://github.com/dbt-labs/dbt/pull/3498.

The Jinja folks have thrown their weight behind the `.jinja` file extension, though I understand that `.j2` is also a popular choice ([docs](https://jinja.palletsprojects.com/en/2.11.x/templates/#template-file-extension), [stackoverflow conversation](https://stackoverflow.com/questions/29590931/is-there-an-idiomatic-file-extension-for-jinja-templates)).

Personally, I don't have strong feelings about preferring `.jinja` vs. `.j2`. I suppose we could support any arbitrary suffix after `.sql`. dbt does name models based on their file names, and it support dots in model file names today, so I think a model file named `models/my.sql.model.sql.j2` would do some surprising things. I think we'd need to consider that an unreasonable edge case, and one we can't hope to support.

In the meantime, I'm going to close this as a duplicate of #3484, which will be doing the heavy lifting. I'd encourage you to leave a comment there if you feel strongly about supporting `.sql.j2` in particular (or other extensions in general), in addition to `.sql.jinja`.

**Closed by jtcohen6** 2021-08-03 01:05 UTC
Labels: duplicate

**Comment by gsemet** [comment] 2025-06-04 09:21
Hello,

i start using dbt, and i would like to give my +1 for this ticket, the queries in .sql extension are actually jinja templates, and most code editor support <originalext>.j2 natively, for instance vscode, you can have `my_query.sql.j2`, and the syntax highlighting, code completion, even copilot and so on, will know i am editing a sql with jinja extension. Works for yaml (dbt_project.yml.j2), python, sql, and so on.
