### ISSUE TITLE
[Bug] Cannot run unit test with duckdb as database

### ISSUE THREAD

**Issue by sogunsemi** [dbt-labs/dbt-core#10292] opened 2024-06-11 00:02 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I run the unit tests:
```
dbt test --select test_type:unit
```

I get back this error:
```
Compilation Error in model model_a (models/source_a/sources.yml)
Not able to get columns for unit test 'model_a' from relation "dev"."source_a"."model_a"

> in macro get_fixture_sql (macros/unit_test_sql/get_fixture_sql.sql)
> called by model model_a (models/source_a/source.yml)
```

Unit test:
```
unit_tests:
  - name: test_type_conversions
    description: "Check type conversion logic"
    model: model_a
    given:
      - input: source('source_a', 'model_a')
        rows:
          - {year: '2015', value: '2.9'}
    expect:
      rows:
      - {year: 2015, absence_rate_total: 2.9}
```

### Expected Behavior

The unit test runs to completion.

### Steps To Reproduce

1. Configure duckdb as the warehouse using the dbt-duckdb adapter version 1.8.1
2. Create a unit test for a model
3. Run it using the command: `dbt test --select test_type:unit`

### Environment

```markdown
- OS: MacOS Monterey 12.4
- Python: 3.11.9
- dbt: 1.8.2
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Using dbt-duckdb 1.8.1

**Comment by dbeatty10** [comment] 2024-06-11 16:31
Thanks for reaching out @sogunsemi !

Does database table/view for that source exist in your DuckDB database?

i.e., Does the following command give a result without error?

```shell
dbt show --inline 'select * from {{ source("source_a", "model_a") }}'
```

**Comment by sogunsemi** [comment] 2024-06-11 21:14
> Thanks for reaching out @sogunsemi !
> 
> Does database table/view for that source exist in your DuckDB database?
> 
> i.e., Does the following command give a result without error?
> 
> ```shell
> dbt show --inline 'select * from {{ source("source_a", "model_a") }}'
> ```

Ah thanks! I get a 403 error which is expected. The data is in a GCS bucket that I don't have local access to.

I thought I would be able to run the unit_tests without hitting the actual data?

**Comment by dbeatty10** [comment] 2024-06-11 21:28
dbt needs to access the metadata of the given inputs, specifically the column names and their data types.

Since the error message you got is expected when you don't have access to the data, I'm going to close this as not a bug.

**Closed by dbeatty10** 2024-06-11 21:28 UTC
Labels: bug, awaiting_response, unit tests
