### ISSUE TITLE
[CT-3510] [Bug] Post-hooks do not work for Python models with dbt-fal, postgres adapter

### ISSUE THREAD

**Issue by tarnpreetb123** [dbt-labs/dbt-core#9310] opened 2023-12-21 21:31 UTC
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Using **dbt-postgres: 1.5.5**
and **dbt-fal: 1.5.9**

```
-- models/input/model_a.sql
select 1 as pk
```
```
# models/base/model_b.py
def model(dbt, session):
    df = dbt.ref("model_a")
    return df
```
```
---dbt_project.yml
models:
    input:
      +materialized: table
      schema: input
    base:
      +materialized: table
      schema: base
      +post-hook:
           sql: " {{ alter_pk() }} "
           transaction: false
```
```
---alter_pk.sql
{% macro alter_pk() %}
    ALTER TABLE {{this}}
    ADD PRIMARY KEY(pk)
{% endmacro %}
```

Using a python model with the postgres adapter, the post_hook is ignored. Calling it from the model, or the dbt_project.yml results in the same behavior of it being ignored.

### Expected Behavior

I expect the post-hook to run the sql command like it would for a sql model. The current work around has been to have a sql model select the python model table and make a new duplicate table with the appropriate post-hook running on that.

```
-- models/base/model_c.sql
select * from {{ref('model_b')}}
```

This will run the post-hook from before. 

### Steps To Reproduce

dbt run the above models locally

### Environment

```markdown
- OS: Windows 10
- Python: 3.10.7
- dbt:1.5.5
- fal: 1.5.9
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

Similar issue: https://github.com/dbt-labs/dbt-core/issues/7803 from before that had the same problem with post-hooks not running.

**Comment by tarnpreetb123** [comment] 2023-12-21 21:50
@victorthevong

**Comment by dbeatty10** [comment] 2023-12-22 01:27
Thanks for reaching out @tarnpreetb123 !

Similar to what jtcohen6 described [here](https://github.com/dbt-labs/dbt-core/issues/7803#issuecomment-1606127245), I was also able to get post-hooks to work just fine. See below for full details.

Since this doesn't appear to be an issue in dbt-core, I'm going to close this issue as "can't reproduce". I'd suggest opening an issue in [dbt-fal](https://github.com/fal-ai/dbt-fal) instead -- they can ping it back to us if they really believe it is an issue in dbt-core somehow.

<details>

<summary>

## Full details</summary>

I used [dbt-duckdb==1.5.2](https://pypi.org/project/dbt-duckdb/1.5.2/) to test if this was working or not. My assumption is that `dbt-databricks`, `dbt-snowflake`, and `dbt-bigquery` would behave similarly.

```shell
python -m pip install dbt-duckdb==1.5.2
```

### Project files

`dbt_project.yml`

```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "duckdb"

models:
  my_project:
    +materialized: table
    +post-hook:
      - " {{ alter_pk(source='dbt_project.yml') }} "
      - "select 1 as id -- this is my post-hook in dbt_project.yml"
```

`macros/alter_pk.sql`

```sql
{% macro alter_pk(source="unknown") %}
    select 1 as id -- this is my post-hook called by macro alter_pk in {{ source }}
{% endmacro %}
```

`models/model_a.sql`

```sql
select 1 as id
```

`models/model_b.py`

```sql
def model(dbt, session):
    dbt.config(post_hook="select 1 as id -- this is my post-hook in model_b.py")
    df = dbt.ref("model_a")
    return df
```

### Command to run

```shell
dbt build
```

### Sample output from `logs/dbt.log`

```
        select 1 as id -- this is my post-hook called by macro alter_pk in dbt_project.yml
        select 1 as id -- this is my post-hook in dbt_project.yml
        select 1 as id -- this is my post-hook in _models.yml
        select 1 as id -- this is my post-hook in model_b.py
```

</details>

**Closed by dbeatty10** 2023-12-22 01:27 UTC
Labels: bug, triage
