### ISSUE TITLE
[CT-2294] [Feature] Seed JSON and Parquet

### ISSUE THREAD

**Issue by jpmmcneill** [dbt-labs/dbt-core#7155] opened 2023-03-10 23:19 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Right now (as far as I am aware) seed files have to be CSVs.

Using something like duckdb (which critically is dependency-less) seeds could easily be extended to json or parquet as well, by having something like:

```
seeds/
  foo.csv
  bar.csv
  foobar.json
```

-> 

```
seeds/
  foo.csv
  bar.csv
  foobar.json
  __dbt_foobar.csv (temporary file, created by duckdb)
```

From which the usual seed method could be created. Finally dbt could delete the temp file.

Possibly it's silly to widen the net of things that could be seeded 🤷

### Are you interested in contributing this feature?

Yup, if i'm pointed in the right direction! (I think it's probably `core/dbt/task/seed.py`

**Comment by dbeatty10** [comment] 2023-03-13 17:46
Hey @jpmmcneill, always good to see you again!

### JSON seeds
There's actually a pre-existing issue for the JSON part: https://github.com/dbt-labs/dbt-core/issues/2365. Specifically, the [NDJSON](http://ndjson.org/) format was proposed with one valid JSON value per line (which will most commonly be an object or array).

Since the issue you submitted is primarily concerned with JSON seeds, I'm going to close this as a duplicate of https://github.com/dbt-labs/dbt-core/issues/2365

### Parquet seeds

But it sounds like you might have a stand-alone (but related) request to be able to seed Parquet files too.

My _initial_ (and not fully refined thoughts) related to adding official support for Parquet as a seed format is: not at this time*.

The primary reasons:
1. Supporting Parquet would beg the question about support other formats like ORC, Avro, etc.
1. There are warehouse specific workarounds to ingest Parquet today (see below for dbt-duckdb)

*With that being said, I would absolutely welcome and encourage you to open a new feature request for Parquet seeds if you want to discuss further!

#### Parquet in DuckDB
Let's assume you have a valid parquet file located at `seeds/my_parquet_seed.parquet`. For DuckDB users (using dbt-duckdb), I think parquet "seeds" are possible as-is via syntax like [this](https://duckdb.org/docs/data/parquet/overview.html):
`models/my_test.sql`
```
select * from 'seeds/my_parquet_seed.parquet'
```

This syntax obviously isn't a true seed, because it wouldn't support references like `ref("my_parquet_seed")`. But you could just do `ref("my_test")` instead when that is needed/desired.

**Closed by dbeatty10** 2023-03-13 17:46 UTC
Labels: enhancement, triage

**Comment by jpmmcneill** [comment] 2023-03-13 17:57
Hey @dbeatty10, thanks for this! No problem to close.

I agree that supporting `n != 1` always begs the question of "can you support X". I agree that there are warehouse specific workarounds but they're complete pains sometimes (I'm thinking specifically of snowflake here). Really what attracted me to duckdb for this issue is that it provides a quite headless way to turn other data types into csv's in a quite lightweight method.

So I wasn't really talking about the duckdb adapter specifically! Indeed, adding duckdb as a requirement for dbt core would give josh a tonne of dependency headaches most likely! 😂

Nice that JSON stuff exists. Sorry that I missed that issue, I'll give it a read.

**Comment by dbeatty10** [comment] 2023-03-13 20:07
Yeah, that's a clever idea of using DuckDB as lightweight format converter 🧠 

Two things that would improve that approach:
1. CSV seeds in dbt rely on combination of [type inference + column_types configuration](https://docs.getdbt.com/faqs/seeds/seed-datatypes). It would be nice if converting from Parquet to a CSV seed also emitted the appropriate `column_types` configuration (either database specific or database agnostic).
1. Currently, Parquet is one of the [few file formats supported](https://duckdb.org/docs/guides/#sql-data-import--export) for importing by DuckDB. This approach would benefit if there were more export options.
