### ISSUE TITLE
[Bug] Can't use label 'X' for  metric 'Y' as it's already used for metric 'Z' (but 'Z' no longer exists)

### ISSUE THREAD

**Issue by KayakinKoder** [dbt-labs/dbt-core#9726] opened 2024-03-03 21:16 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm using DBT Cloud in conjunction with the CLI locally. After removing a metric and trying to reuse its label, you'll get this error:

```
20:55:29 Can't use label `mylabel` for  metric `y` as it's already used for metric `z`
20:55:29 Encountered an error:
Parsing Error
  Semantic Manifest validation failed.
```

### Expected Behavior

After removing a metric, you should be able to reuse its label.

### Steps To Reproduce

1. Create a metric, z, and give it a label: mylabel  Compile, then delete that metric.

2. Create another metric y, and give it the same label (mylabel). Compile, and you'll get this error

### Environment

```markdown
- OS: Debian 12
- dbt Cloud CLI - 0.36.9
```

**Comment by dbeatty10** [comment] 2024-03-06 13:10
Thanks for reaching out about this @KayakinKoder 👍

Does the problem go away if you compile with the local CLI like this?

```shell
dbt --no-partial-parse compile
```

Could you also share your "Registered adapter" that shows up near the top of your output in the local CLI? (See example output below.)

I tried reproducing the error message, but I was not able.

Here's what I tried:

I started with this file:

`models/_metrics.yml`

```yaml
metrics:

  - name: metric_z
    label: mylabel
    type: derived
    type_params:
      expr: revenue - cost
```

Then I ran `dbt compile`. Then I changed the name from `metric_z` to `metric_y` and re-ran `dbt compile` and it completed without any error messages:

```
$ dbt compile
Created task id b229fbe1-82a8-4e34-b9d8-a21fd1e7aa2b
13:02:30 Running dbt...
13:02:30 Registered adapter: redshift=1.8.0-a1
13:02:30 Found 1 model, 1 metric, 465 macros
13:02:30 
13:02:31 Concurrency: 4 threads (target='default')
13:02:31 

Invocation has finished
```

**Comment by KayakinKoder** [comment] 2024-03-07 22:09
@dbeatty10 thanks for getting back so quickly.

> Does the problem go away if you compile with the local CLI like this?
> `dbt --no-partial-parse compile`

Yes that fixed things. After running that, simple `./dbt parse` works without errors.

Registered adapter:

```
22:05:54 Running with dbt=1.7.8
22:05:55 Registered adapter: bigquery=1.7.6
```

**Comment by dbeatty10** [comment] 2024-03-09 00:26
Glad that worked for you @KayakinKoder !

I'm going to close this as "can't reproduce", but if you or anyone else is able to reproduce this, please reach out!

In the meantime, if anyone run into this and finds this issue, here is the workaround:

```shell
dbt --no-partial-parse compile
```

**Closed by dbeatty10** 2024-03-09 00:26 UTC
Labels: bug, semantic, Impact: SL
