### ISSUE TITLE
[Feature] add on_schema_change='fail' option for tables, not just incremental models.

### ISSUE THREAD

**Issue by wdieterich** [dbt-labs/dbt-core#4150] opened 2021-10-27 20:14 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would like to have the `on_schema_change='fail'` option for normal models, not just incremental models. 

This would allow developers to have some type safety checks on their models. In my use case, I would like to have the assurance that changes I make in upstream models aren't resulting in different datatypes in my downstream deliverables. 

If table deliverables are not incremental, there's no way I can find to ensure schemas aren't changing. 

I believe this could be easily accomplished if there was some control over whether dbt uses `DROP` or `TRUNCATE` on the table while generating the model. 

Maybe some workaround exists but I haven't found it.  

### Describe alternatives you've considered

On bigquery I've tried this workaround with no success: 
I thought passing `full_refresh=true` would essentially make my table not incremental, but still throw an error when the schema changes.  Unfortunately running the code below, and then changing the `text_col` to an `int` does not throw an error as I believe it should.  Might this also be a bug for those using incremental models? Why should schema changes not be detected when running a `full_refresh`?  

```{{
    config(
        materialized='incremental',
        full_refresh = true,
        on_schema_change='fail'
    )
}}

select
    "test" as text_col
```

### Who will this benefit?

Those who want type checking on non-incremental models.

### Are you interested in contributing this feature?

Potentially. need to prioritize with employer

**Comment by jtcohen6** [comment] 2021-11-18 09:49
@wdieterich Thanks for opening the issue!

> I believe this could be easily accomplished if there was some control over whether dbt uses `DROP` or `TRUNCATE` on the table while generating the model.

dbt used to support this, in the form of a `--non-destructive` flag ([docs](https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-14-0#non-destructive-runs)). The intent of that flag was not schema enforcement, however—it was a workaround for bound views being cascade-dropped in Redshift. With the advent and increasing reliability of late-binding views, the run mode (and its many wonky limitations) was no longer needed.

> I thought passing full_refresh=true would essentially make my table not incremental, but still throw an error when the schema changes.

I see why you expected that, given that you've configured the model with both `full_refresh = true` and `on_schema_change = 'fail'`. The `on_schema_change` config is really _just_ for incremental (that is, partial refresh) runs. It's by design that "full refreshing" an incremental model completely replaces its column schema. In older versions of dbt, this was the _only_ way to automatically update the schema of an incremental model when it changed.

---

What I hear you asking is for an alternative proposal that we've discussed in the past: strict enforcement of model schemas (https://github.com/dbt-labs/dbt-core/issues/1570), based on the column names + types defined in your `.yml` files. Following the gist of that proposal, if your model looked like:
```sql
-- models/my_model.sql
select 1 as id, "bad" as unwanted_column
```yml
# models/whatever.yml
version: 2
models:
  - name: my_model
    config:
      materialized: table
      strict: true # perhaps like this?
    columns:
      - name: id
        data_type: int
      - name: is_good_column
        data_type: bool
```

Then, there's two ways we could go:
1. On databases that support column specifications in `create table as` statements (I know Snowflake + BigQuery do), dbt could simply include it along with the model SQL. (This should fail at runtime, since a string type cannot be coerced to the expect bool type.)
```sql
create or replace table dbt_me.my_model
  (id int, is_good_column bool) -- here to enforce schema
as (
  select 1 as id, "bad" as unwanted_column
)
```

2. After fully creating the table, dbt could introspect its schema, compare it to the schema defined in your `.yml` file, and raise an error if there's any mismatch. The downside of this approach is that, on databases where we use `create or replace` statements (e.g. Snowflake + BigQuery), the new table is already in place. There could be a cleverer approach, whereby dbt first runs the query with a `where false limit 0`, just to capture its column schema ([e.g.](https://github.com/dbt-labs/dbt-core/blob/ba23395c8edfaf11fccfb136db920fd276b1d063/core/dbt/include/global_project/macros/adapters/columns.sql#L20-L34)), before creating the final table.

---

I'd be curious to hear your thoughts about "strict schema enforcement" over in https://github.com/dbt-labs/dbt-core/issues/1570. I'm going to close this issue to keep the conversation centralized over there.

In the meantime, you could look into workarounds like:
- materializing the model incrementally, with `full_refresh=false` and `on_schema_change='fail'`, and write your model SQL so as to replace all its data every time
- writing a custom materialization (adapting the `table` materialization) to add in a `truncate` + `insert` option

**Closed by jtcohen6** 2021-11-18 09:49 UTC
Labels: enhancement
