### ISSUE TITLE
[CT-2827] TestSingularTestsEphemeralSnowflake::test_singular_tests_ephemeral is flaky

### ISSUE THREAD

**Issue by mikealfare** [dbt-labs/dbt-core#8103] opened 2023-07-17 17:50 UTC
Different status types come through the test. It's not always clear which one. The test fails when trying to assert a positive status. When it gets the correct status class (RunStatus I believe), it passes, because the value is `pass`. But when it gets he wrong one (TestStatus I believe), then it fails; I think this happens because the positive status on that is `success`, hence `pass` becomes `fail` since it's not a valid value.

**Comment by MichelleArk** [comment] 2023-07-18 05:37
This test is also flaky in the base core implementation: TestSingularTestsEphemeral.test_singular_tests_ephemeral

https://github.com/dbt-labs/dbt-core/actions/runs/5583460196/jobs/10203801831?pr=6346

**Comment by jtcohen6** [comment] 2023-07-18 08:10
This is the test that is flaky since the upgrade to `sqlparse==0.4.4`. It only fails on Ubuntu. This is what motivated us to pin `sqlparse<0.4.4` previously:
- https://github.com/dbt-labs/dbt-core/issues/7396

It was also reported in the wild by a handful of users:
- https://github.com/dbt-labs/dbt-core/issues/7521
- https://github.com/dbt-labs/dbt-core/issues/7595

We weren't able to identify root cause, nor were we able to rip out `sqlparse` and replace it with something more naive.

**Comment by aosingh** [comment] 2023-07-20 21:32
As a temporary workaround for all testcases to pass in our Github Actions CI pipeline, I [reinstall sqlparse==0.4.3 ](https://github.com/oracle/dbt-oracle/blob/main/.github/workflows/oracle-xe-adapter-tests.yml#L54)

**Comment by jtcohen6** [comment] 2023-08-02 13:24
Pretty sure this should be fixed by #8215

**Closed** 2023-08-03 23:07 UTC
