### ISSUE TITLE
[CT-541] [Feature] Allow the log location to be set with a global flag

### ISSUE THREAD

**Issue by barberscott** [dbt-labs/dbt-core#5132] opened 2022-04-21 19:25 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

There may be a **really good reason™** to set dbt to log into a different location than would be set in `dbt_project.yml` -- for example, the default directory is a subfolder in their repo and then the `logs` folder ends up tracked if missing from `.gitignore`.  

This is fairly common in dbt Cloud for example, and results in users getting stuck in a loop with the IDE showing Commit... and them never being able to switch branches.  Then you fix `.gitignore` but `logs` is still tracked..and you end up with a hard cycle to break out of.

`log-path:` (and potentially `target-path` and `packages-install-path`) should be settable via command flags to alternative locations.  This, for example, would allow dbt Cloud to have the log file go to a location outside the root of the user directory (e.g. /tmp/logs) which would prevent it from being tracked.  This would also prevent someone from changing this path to an undesirable path.

**Comment by ChenyuLInx** [comment] 2022-04-21 21:28
Hey @barberscott, thanks for opening this, and I can see the frustration of the unintended behavior it causes. 
Looks like this is the place where we set the default value for the log path.
https://github.com/dbt-labs/dbt-core/blob/43e3fc22c4eae4d3d901faba05e33c40f1f1dc5a/core/dbt/config/project.py#L357
Maybe we can overwrite it similar to what we do something similar to what `--profile` does
https://github.com/dbt-labs/dbt-rpc/blob/70c1a6ba011be6a82d09b8af0b391184a288dd7e/dbt_rpc/__main__.py#L279-L286

My sense is that this feature is only needed for dbt-RPC not cli user, should we move it over there? @jtcohen6 

Note: [This](https://github.com/dbt-labs/dbt-core/blob/43e3fc22c4eae4d3d901faba05e33c40f1f1dc5a/core/dbt/config/profile.py#L427) is the place we determine which `profile_name` to use.

**Comment by jtcohen6** [comment] 2022-04-22 11:54
> `log-path`: (and potentially `target-path` and `packages-install-path`) should be settable via command flags to alternative locations

It sounds like the desire is for a pattern similar to how we handle "global" configs. The priority order for resolving those is flags > env vars > `profiles.yml` config. In this case, for all `*-path` configs, it might be flags > env vars > `dbt_project.yml` config. So e.g., `--log-path` takes precedence over `DBT_LOG_PATH` which takes precedence over the current `log-path: ...`.

> My sense is that this feature is only needed for dbt-RPC not cli user, should we move it over there?

I think we want to expose consistent functionality regardless of how `dbt-core` is invoked (which is via RPC server in the IDE, but _not_ via RPC server for scheduled runs). I could see this being useful for `dbt-core` use more generally, given that `log-path` is already settable in `dbt_project.yml`. I'd also like to keep `dbt-rpc`-specific code to a minimum.

**Comment by gtdminh** [comment] 2022-06-29 00:14
i would like this log file can be placed in target folder as well and dbt cloud api can pull this log file the same way as other artifact files.

**Comment by iknox-fa** [comment] 2022-08-01 16:23
@barberscott 
I believe this may have solved your issue: https://github.com/dbt-labs/dbt-core/pull/5402
We'll double check that the resolution order is as expected.

**Comment by jtcohen6** [comment] 2022-08-18 11:54
Closing as resolved by #5402

**Closed by jtcohen6** 2022-08-18 11:54 UTC
Labels: enhancement, Team:Execution, logging
