### ISSUE TITLE
[CT-3010] [Regression] Dbt ls failing to find models when using path selector and project-dir flag

### ISSUE THREAD

**Issue by jsteele-om1** [dbt-labs/dbt-core#8446] opened 2023-08-17 19:02 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In upgrading from 1.3 to 1.6, we've noticed an issue with running `dbt ls --select <model-path> --project_dir <project> ...`.  It only appears to be this combination that fails to find any models. It works with:
* dbt build command with project dir flag and path selector
* dbt ls with model path and no project dir flag
* dbt ls with project dir flag and specific model selected

### Expected Behavior

`dbt ls --select <model-path> --project_dir <project> ...` select models under `<project-dir>/<model-path>`

### Steps To Reproduce

1. Sample Environment:
```
parent_directory/
  sample_project/
    dbt_project.yml
    models/
      example/
        sample_model.sql
```
2. cwd = `parent_directory`: `dbt ls --select models/example --project-dir sample_project/` returns: `no nodes selected`

### Relevant log output

```shell
18:59:16  Running with dbt=1.6.0
18:59:16  Registered adapter: snowflake=1.6.0
18:59:26  Found nnnn models, nnnn tests, nnnn seeds, nnnn operations, nnnn sources, nnn exposures, nnn metrics, nnnn macros, nnnn groups, nnnn semantic models
18:59:26  The selection criterion 'models/<...>' does not match any nodes
18:59:26  No nodes selected!
```

### Environment

```markdown
- OS: `Debian GNU/Linux 10 (buster)`
- Python: `3.9.5`
- dbt: `1.6.0`
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment] 2023-08-18 18:55
Thanks for reporting this @jsteele-om1 🙏

After testing this out myself, I can verify that using [file/fqn](https://docs.getdbt.com/reference/node-selection/methods#the-file-or-fqn-method) syntax like the following works in both 1.5 and 1.6:
```shell
dbt ls --project-dir sample_project/
dbt ls --select example --project-dir sample_project/
dbt ls --select file:example.sql --project-dir sample_project/
```

But [path](https://docs.getdbt.com/reference/node-selection/methods#the-path-method)-based selection that worked in 1.5 no longer works in 1.6:
```shell
dbt ls --select models/example.sql --project-dir sample_project/
dbt ls --select path:models/example.sql --project-dir sample_project/
```

I tried using both absolute and relative paths as well as setting the `DBT_PROJECT_DIR` environment variable, but path-based selection didn't work in 1.6 regardless.

**Comment by jtcohen6** [comment] 2023-08-21 10:23
Thanks team! This is a duplicate of https://github.com/dbt-labs/dbt-core/issues/8385, and I believe it was fixed in https://github.com/dbt-labs/dbt-core/pull/8388. You can try using [v1.5.5](https://github.com/dbt-labs/dbt-core/releases/tag/v1.5.5) or [v1.6.1rc1](https://github.com/dbt-labs/dbt-core/releases/tag/v1.6.1rc1) to confirm.

**Closed by jtcohen6** 2023-08-21 10:23 UTC
Labels: bug, regression
