### ISSUE TITLE
[CT-732] [Bug] Placing custom generic test in tests/generic folder causing compilation error

### ISSUE THREAD

**Issue by ashleemtib** [dbt-labs/dbt-core#5341] opened 2022-06-07 13:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are experiencing an issue where our custom generic tests defined as {%test%} blocks are causing compilation errors when placed in the tests/generic folder, as is noted as a location for these definitions in [dbt documentation](https://docs.getdbt.com/guides/legacy/writing-custom-generic-tests).

We used to (and still currently do) define our tests as either {%test%} blocks or {%macro%} blocks and place them in our macros/tests/ folder. Tests that are defined here compile with no issue, including the test in question here.

This compilation error occurs in our containerized staging/prod environments but does not occur when the test is run locally. There is no difference between the local dbt_project.yml and the staging/production yml.

Error: 
```
Compilation Error
  'test_stable_source_count' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```
  
Test definition location: tests/generic 

Test path defined in dbt_project.yml: `test-paths: ["tests"]`

Test definition (shell): 

```
{%- test stable_source_count(model, line_of_business_field, member_field, allowed_deviation=0.1) -%}

{{- config(severity='warn') -}}

  with member_counts as (),

  comparison as (),

  deviation_calc as (),

  errors as ( )

  select * from errors

{%- endtest -%}
```

Test application/call (in source.yml): 

```
sources:
  - name: revenue
    description: Revenue data
    database: [database]
    schema: [schema]

    tables:
      - name: [table name]
        tests:
          - stable_source_count:
              line_of_business_field: data.Plan
              member_field: patient.externalId
```

### Expected Behavior

Expectation is for the test to compile and run on the source it is applied to, as it does locally and for the tests we have defined in macros/tests folder.

### Environment

```markdown
- OS: 
- Python: 3.9.10
- dbt: 1.0.3
```

### What database are you using dbt with?

bigquery

**Comment by ashleemtib** [comment] 2022-06-27 14:18
@jtcohen6 Hi, is there any update on this? Thank you!

**Comment by roslovets** [comment] 2022-07-11 07:46
Hi, move your genetic test to `tests/generic` folder.

**Comment by ashleemtib** [comment] 2022-07-11 14:10
@roslovets Hi there, it is already defined in that folder. Any reason why it wouldn't compile there? thanks.

**Comment by roslovets** [comment] 2022-07-13 06:08
@ashleemtib ah, yes, I see. I had the same error because of the generic folder.
Did you try to deploy a singular test? It is possible that in the container the tests folder is inaccessible.

**Comment by emmyoop** [comment] 2022-07-21 16:53
@ashleemtib thanks for the detailed write up!  That is always appreciated.  And thank you for jumping in with some help @roslovets!

Since this is working locally but not after you've deployed, it seems like an environment issue and not a dbt-core bug.  We generally use GitHub Issues for bug reports and feature requests. We have a very active slack community that would be a great place to ask for help. There are multiple help channels from general help to places to ask warehouse specific questions.

If you're not already a member of our slack community you can [sign up here](https://www.getdbt.com/community/join-the-community/)! It is _very_ active and someone is almost always willing to help out.

I'm going to close this for now but still feel free to comment if needed.

**Closed by emmyoop** 2022-07-21 16:53 UTC
Labels: bug, triage, Team:Language

**Comment by nprime496** [comment] 2023-12-21 23:13
Hi, I tried to do this and I get the same error. The behavior is very inconsistent though, sometimes it doesn't work then it works also when renaming the test suddenly it works.

It seems to be a consistent bug yet no attention is given to it.

Stackoverflow Question : https://stackoverflow.com/questions/77682105/test-not-recognized-in-dbt) and there's indeed something not working properly.
Dbt Forum : https://discourse.getdbt.com/t/compilation-error-while-running-custom-generic-test/8373

Can you try to reproduce steps with a fresh install of dbt ?

I am using dbt 1.1.5 on bigquery.

**Comment by ashleemtib** [comment] 2023-12-22 15:07
Hi there! I had completely forgotten about this issue since it was closed. After Emily's comment, I explored our deployment process further and learned that not all of the folders in our dbt project were being copied over into our Docker image. So, indeed, the tests/generic folder was inaccessible by dbt.

Adding that folder to our deployment resolved the issue.

**Comment by nprime496** [comment] 2023-12-23 12:47
Hi, thanks for the fast answer. I am not sure to get it. We need to update the version  ?

PS:
I am using dbt-core locally and I experience those issues.
