### ISSUE TITLE
[CT-3487] [Bug] `dbt show --inline` does not work when all models are disabled in `dbt_project.yml`

### ISSUE THREAD

**Issue by pgoslatara** [dbt-labs/dbt-core#9269] opened 2023-12-12 15:22 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I run `dbt show --inline` it works. When I add a `--target` flag it does not work.

### Expected Behavior

`dbt show` works when a target is supplied.

### Steps To Reproduce

I'm running the latest version of `dbt-biguery` with this `profiles.yml`:
```yml
dbt_docs:
    target: dev
    outputs:
        dev:
            type: bigquery
            method: oauth
            project: <PROJECT_ID>
            schema: <ENV_VAR>
            location: europe-west4
            threads: 4
        dev2:
            type: bigquery
            method: oauth
            project: <PROJECT_ID>
            schema: <ENV_VAR>
            location: europe-west4
            threads: 4
```

Note that `dev2` is an exact copy of `dev`.

Run the following commands and observe differing behaviour:
```shell
$ dbt show --inline "SELECT 1 AS id"
$ dbt show --inline "SELECT 1 AS id" --target dev
$ dbt show --inline "SELECT 1 AS id" --target dev2
```

The first 2 commands return a result, the third command does not.

### Relevant log output

```shell
$ dbt show --inline "SELECT 1 AS id"
15:13:44  Running with dbt=1.7.3
15:13:44  Registered adapter: bigquery=1.7.2
15:13:44  Unable to do partial parsing because of a version mismatch
15:13:46  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- tests
15:13:47  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 949 macros, 0 groups, 0 semantic models
15:13:47  
15:13:48  Concurrency: 4 threads (target='dev')
15:13:48  
15:13:49  Previewing inline node:
| id |
| -- |
|  1 |

$ dbt show --inline "SELECT 1 AS id" --target dev
15:13:54  Running with dbt=1.7.3
15:13:55  Registered adapter: bigquery=1.7.2
15:13:55  Unable to do partial parsing because config vars, config profile, or config target have changed
15:13:57  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- tests
15:13:57  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 949 macros, 0 groups, 0 semantic models
15:13:57  
15:13:58  Concurrency: 4 threads (target='dev')
15:13:58  
15:13:59  Previewing inline node:
| id |
| -- |
|  1 |

$ dbt show --inline "SELECT 1 AS id" --target dev2
15:14:03  Running with dbt=1.7.3
15:14:03  Registered adapter: bigquery=1.7.2
15:14:03  Unable to do partial parsing because config vars, config profile, or config target have changed
15:14:06  Found 1 seed, 0 sources, 0 exposures, 0 metrics, 949 macros, 0 groups, 0 semantic models
15:14:06  
15:14:06  Nothing to do. Try checking your model configs and model specification args
```

### Environment

```markdown
- OS:Ubuntu 22.04
- Python: Python 3.10.12
- dbt:

Core:
  - installed: 1.7.3
  - latest:    1.7.3 - Up to date!

Plugins:
  - bigquery: 1.7.2 - Up to date!
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment] 2023-12-13 19:22
Do you know what is different between your dbt project when you use different targets?

It looks like you are able to successfully use `dbt show --inline` when `--target dev`, but not able to when `--target dev2`.

This makes me think it might have something to do with target-specific logic you have within your project.

The only thing that I can see that is different in your example output is that the first two have this warning (but the last one doesn't):
```
15:13:57  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- tests
```

I tried to reproduce the same issue you are seeing, but I wasn't able. See below for the files and commands that I used.

Could you try tweaking these example files to see the same unexpected behavior that you described?

### Files

These are the only two files I put in my project (no models or anything else):

`dbt_project.yml`
```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "bigquery"

clean-targets:
  - dbt_packages
  - '{{ env_var("DBT_TARGET_PATH", "target") }}'
  - '{{ env_var("DBT_LOG_PATH", "logs") }}'
```

`profiles.yml`
```yaml
bigquery:
  target: blue

  outputs:
    dev:
      method: service-account
      keyfile: '{{ env_var(''BIGQUERY_SERVICE_KEY_PATH'') }}'
      project: '{{ env_var(''BIGQUERY_TEST_DATABASE'') }}'
      schema: dbt_dbeatty
      threads: 10
      type: bigquery

    dev2:
      method: service-account
      keyfile: '{{ env_var(''BIGQUERY_SERVICE_KEY_PATH'') }}'
      project: '{{ env_var(''BIGQUERY_TEST_DATABASE'') }}'
      schema: dbt_dbeatty
      threads: 10
      type: bigquery
```

### Commands

```shell
dbt show --inline "SELECT 1 AS id" --target dev
dbt show --inline "SELECT 1 AS id" --target dev2
```

### Output

```
(env) $ dbt show --inline "SELECT 1 AS id" --target dev
22:45:27  Running with dbt=1.7.3
22:45:28  Registered adapter: bigquery=1.7.2
22:45:28  Found 0 sources, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
22:45:28  
22:45:28  Concurrency: 10 threads (target='dev')
22:45:28  
22:45:29  Previewing inline node:
| id |
| -- |
|  1 |

(env) $ dbt show --inline "SELECT 1 AS id" --target dev2
22:45:34  Running with dbt=1.7.3
22:45:35  Registered adapter: bigquery=1.7.2
22:45:35  Unable to do partial parsing because config vars, config profile, or config target have changed
22:45:36  Found 0 sources, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
22:45:36  
22:45:36  Concurrency: 10 threads (target='dev2')
22:45:36  
22:45:37  Previewing inline node:
| id |
| -- |
|  1 |
```

**Comment by pgoslatara** [comment] 2023-12-13 20:01
@dbeatty10 Thanks for looking into this. Good idea on the project configuration, I figured out what's causing this issue. We have some jinja logic that disables our models when any target other than "dev" is used (I know, it's complex :smiley:). Essentially what's happening is that when models are disabled then `dbt show` does not return anything, as evidenced by the commands in the issue description.

To reproduce, add this to your `dbt_project.yml`:
```yml
models:
  +enabled: false
```

Regardless of what target you select, running `dbt show --inline "SELECT 1 AS id"` will not return a value.

**Comment by dbeatty10** [comment] 2023-12-13 21:51
### Reprex

Depending on the content of `dbt_project.yml`, this command either shows results (as expected) or doesn't:
```shell
dbt show --inline "select 1 as id"
```

This works:

`models/my_model.sql`

```sql
{{ config(enabled=false) }}

select 1 as id
```

But this doesn't:

`dbt_project.yml`

```yaml
models:
  +enabled: false
```

**Comment by pgoslatara** [comment] 2023-12-17 19:20
I've traced this issue to this [line](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/task/runnable.py#L151):
```python
for uid in self.job_queue.get_selected_nodes():
```

`self.job_queue.get_selected_nodes()` returns zero nodes when models are disabled. What approach to take to fix this I do not know, this feels rather nested in terms of impact.

**Comment by dbeatty10** [comment] 2024-05-22 20:40
### Acceptance criteria

dbt core should disregard [selection](https://docs.getdbt.com/reference/node-selection/syntax#shorthand) / [selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors) altogether when running in inline mode during ["interactive compile"](https://docs.getdbt.com/reference/commands/compile#interactive-compile) and [dbt show](https://docs.getdbt.com/reference/commands/compile#interactive-compile).

i.e., whenever the `--inline` flag is passed to `dbt compile` or `dbt show`, dbt should render that Jinja regardless if:

- the dbt project has 0 nodes or many
- all nodes are disabled or not
- a `--select` or `--selector` flag is passed that selects 0 nodes
- the default selector selects 0 nodes
- etc.

In the case of `dbt show,` it should also run it as a SQL query and return the result set.

**Comment by dbeatty10** [comment] 2024-05-22 20:47
We've identified a handful of edge cases where `--inline` doesn't work as desired.

### Case 1

See https://github.com/dbt-labs/dbt-core/issues/9269#issuecomment-1854755317

### Case 2

```shell
dbt compile --select something_that_doesnt_match_any_nodes --inline "select 1 as id"
dbt show --select something_that_doesnt_match_any_nodes --inline "select 1 as id"
```

### Case 3

`selectors.yml`

```yaml
selectors:
  - name: no_nodes_for_you
    description: Something that matches no nodes
    default: false
    definition:
      union:
        - method: fqn
          value: "*"
        - exclude:
          - method: fqn
            value: "*"
```

```shell
dbt compile --selector no_nodes_for_you --inline "select 1 as id"
dbt show --selector no_nodes_for_you --inline "select 1 as id"
```

### Case 4

Same `selectors.yml` as Case 3, except make it the default instead:
```yaml
    default: true
```

```shell
dbt compile --inline "select 1 as id"
dbt show --inline "select 1 as id"
```

**Comment by gshank** [comment] 2024-06-04 20:16
This is a duplicate of https://github.com/dbt-labs/dbt-core/issues/8943, so I've reassigned it to me.

**Comment by gshank** [comment] 2024-06-04 21:24
@graciegoheen When all models are disabled via dbt_project.yml, that includes the inline model node that's created with "--inline".  So it's not clear that that is actually a bug, although it is somewhat unexpected.

**Closed** 2024-06-06 20:18 UTC
Labels: bug, Impact: Exp, backport 1.8.latest
