### ISSUE TITLE
[Bug] Adding exports section to Saved query causing parse failure

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#10370] opened 2024-06-26 20:22 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In some cases, adding an exports section to an existing saved query definition would cause parsing to fail with error
```
Compilation Error
  'dbt.artifacts.resources.v1.saved_query.Export object' has no attribute 'unrendered_config'
```

Two things making this a tricky bug:
- We can not reproduce this using the example project https://github.com/dbt-labs/jaffle-sl-template.
- The traceback is swallowed so we do not know where this happening.

Community thread: https://getdbt.slack.com/archives/C046L0VTVR6/p1719218667823979

### Expected Behavior

1. dbt parse would work all the time when correct exports being defined.
2. dbt does not swallow traceback with certain flag enabled, so we can trouble shoot problems easier.

### Steps To Reproduce

I can not reproduce this right now

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dbeatty10** [comment] 2024-07-02 14:56
Thanks for trying all of that @rasmushemph!

If you start with an empty dbt project and add the minimal number of metrics, etc to the project, do you still get this error?

**Comment by rasmushemph** [comment] 2024-07-03 13:28
I now removed pretty much everything  in my project and still had the problem with only one staging model so figure the problem was on my side... Finally found this macro running silently in the background. We added it a while back to override the schema-name for dev runs but now apparently fails for this node type that does not have a unrendered_config.. 

I changed the if-logic a little bit and I hope that should clear it out. If you have a better suggestion please let me know.

Thanks for the kind help again! 

ORIGINAL
```yml
{% macro generate_alias_name(custom_alias_name=none, node=none) -%}
{# Code adapted from https://github.com/dbt-labs/dbt-bigquery/issues/1038 /rmh #}
    {%- if custom_alias_name is none -%}
        {%- set table_name = node.name -%}
    {%- else -%}
        {%- set table_name = custom_alias_name | trim -%}
    {%- endif -%}

    {%- if target.name != 'prod' -%}
        {#- Get the custom schema name -#}
        {%- if node.resource_type == 'snapshot' -%}
            {%- set schema_prefix = 'artifacts' -%}
        {%- else -%} 
            {%- set schema_prefix = node.unrendered_config.schema | trim -%}
        {%- endif -%}
        {#- Highlight if schema hasn't been assigned right -#}
        {%- if not schema_prefix -%}
            {%- set schema_prefix = 'NO_ASSIGNED_SCHEMA' %}
        {%- endif -%}
        {{ schema_prefix ~ "__" ~ table_name }}
    {%- else -%}
        {{ table_name }}
    {%- endif -%}
{%- endmacro %}

NEW:
```yml
{% macro generate_alias_name(custom_alias_name=none, node=none) -%}
{# Code adapted from https://github.com/dbt-labs/dbt-bigquery/issues/1038 /rmh #}
    {%- if custom_alias_name is none -%}
        {%- set table_name = node.name -%}
    {%- else -%}
        {%- set table_name = custom_alias_name | trim -%}
    {%- endif -%}

    {%- if target.name != 'prod' -%}
        {#- Get the custom schema name -#}
        {%- if node.resource_type == 'snapshot' -%}
            {%- set schema_prefix = 'artifacts' -%}
        {%- elif node.resource_type  in ('model','source') -%}
            {%- set schema_prefix = node.unrendered_config.schema | trim -%}
        {%- endif -%}
        {#- Highlight if schema hasn't been assigned right -#}
        {%- if not schema_prefix -%}
            {%- set schema_prefix = 'NO_ASSIGNED_SCHEMA' %}
        {%- endif -%}
        {{ schema_prefix ~ "__" ~ table_name }}
    {%- else -%}
        {{ table_name }}
    {%- endif -%}
{%- endmacro %}
```

**Comment by dbeatty10** [comment] 2024-07-03 13:49
You're welcome @rasmushemph !

Glad that you were able to isolate it to your `generate_alias_name` macro -- you should be able to modify that macro as-needed until the error message goes away.

[`raise_compiler_error`](https://docs.getdbt.com/reference/dbt-jinja-functions/exceptions) can also be handy If there's particular edge(s) you want to catch and raise an exception for (like where you are doing the `NO_ASSIGNED_SCHEMA` part).

Since it looks like we've found the root cause, I'm going to close this issue -- just let me know if that's not the case and we can re-open.

**Closed by dbeatty10** 2024-07-03 13:49 UTC
Labels: bug, triage, semantic, Impact: SL
