### ISSUE TITLE
[CT-3402] python func returning None where using in JINGA created corrupted sql

### ISSUE THREAD

**Issue by obar1** [dbt-labs/dbt-core#9113] opened 2023-11-17 15:05 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

pyhton() func returning None create issue in compiled see below

### Expected Behavior

no None

### Steps To Reproduce

![20231117_160208](https://github.com/dbt-labs/dbt-core/assets/387386/4091bab3-f0dc-49e0-870a-6997f3b40c73)

I have to write that hack to avoid to have corrupted sql

### Relevant log output

```shell
see img
```

### Environment

```markdown
- OS: win
- Python: 3.9.0
- dbt: 1.6
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

done above -  sorry I can put the code here -but it's easy to reporduce

**Comment by dbeatty10** [comment] 2023-11-17 15:23
Thanks for reaching out @obar1 !

Can you share more details of the step-by-step code that gave you a problem?

For example, please share the following so we can try to reproduce the bug that you are reporting:
1. The code in text format
2. dbt commands that you ran
3. Log output showing the error message
4. Any other relevant content to help us reproduce the bug you are reporting

**Comment by obar1** [comment] 2023-11-17 15:26
simple jinga code as in the image -  then dbt compile -  easy -  I did at work and I cannot send snippet oout so I did a super simple version you guys can type and run

**Comment by dbeatty10** [comment] 2023-11-17 16:46
From the screenshot you shared, I'm not able to see anything amiss.

Are you able and willing to create a small reproducible example as described [here](https://github.com/dbt-labs/dbt-core/issues/9113#issuecomment-1816626068)?

If not, we'll close this as "can't repro" (short for "can't reproduce").

**Comment by obar1** [comment] 2023-11-22 14:55
hi  @dbeatty10 

try this in a_model.sql

```jinja
{% set a_set = [ 'one', '2' , '333'] %}
  /* HI */

{% set appends = [] %}
{% for s in a_set  %}
  /* you should see this only */
  {{ appends.append(s)}}
  {{ appends.append(s) | replace('None','')}}
{% endfor %}

```


dbt compile and see target/compiled

it should be only ... 
  /* HI */

  /* you should see this only */
  /* you should see this only */
  /* you should see this only */

the bouch of None you see are the problem

**Comment by dbeatty10** [comment] 2023-11-27 01:40
Thanks for sharing that example @obar1 👍

I saw the `None` strings that you described when following your example.

This output is just a result of how Jinja works as a string templater rather than anything that is specific to dbt. The key insights are:
- `{{ ... }}` is used to output a string into a template.
- `{% ... %}` is used for controlling the flow and logic of the template and doesn't output strings.

There's multiple ways that you can avoid a `None` string, and you already discovered one of them.

Here's another that uses `{% ... %}` instead of `{{ ... }}`:

```sql
{% set a_set = [ 'one', '2' , '333'] %}
  /* HI */

{% set appends = [] %}
{% for s in a_set %}
  /* you should see this only */
  {%- do appends.append(s) -%}
{% endfor %}
```

Since this is expected behavior, I'm going to close this a not a bug.

**Closed by dbeatty10** 2023-11-27 01:40 UTC
Labels: bug, triage

**Comment by obar1** [comment] 2023-11-28 13:48
cool stuff it makes sense and I will use it for sure. Thanks

**Comment by dbeatty10** [comment] 2023-11-28 16:19
@obar1 we don't want to fully replicate the [Jinja docs](https://jinja.palletsprojects.com/en/3.0.x/templates/), but I tried to propose some light modifications to the dbt docs in https://github.com/dbt-labs/docs.getdbt.com/pull/4546.

Feel free to comment on that PR or open your own issue and/or PR to update the dbt docs [here](https://github.com/dbt-labs/docs.getdbt.com). At the bottom of each page in dbt docs, there is a link that you can click to submit a proposed change:

<img width="140" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/3a0857b5-dd30-4e5c-9710-4b3659a4ba36">
