### ISSUE TITLE
[CT-2943] [Bug] `clean` via Python API changes the working directory

### ISSUE THREAD

**Issue by sweco** [dbt-labs/dbt-core#8326] opened 2023-08-04 21:47 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running the `clean` command via the `dbt.cli.main.dbtRunner` (i.e. from a Python script) with the `--project-dir` option set to another directory changes the working directory to the directory provided via the `--project-dir` option, breaking any future `dbt` commands (and other Python code that depends on the working directory not changing).

### Expected Behavior

The working directory should not change.

### Steps To Reproduce

Minimalistic code to reproduce:

```python
import os
from dbt.cli.main import dbtRunner

dbt = dbtRunner()
print(os.getcwd())  # working/directory
dbt.invoke(["clean", "--project-dir", "jaffle_shop"])  # Has to be a real project, if it does not exist, the bug does not demonstrate
print(os.getcwd())  # working/directory/jaffle_shop
```

### Environment

```markdown
- OS: MacOS Ventura 13.5
- Python: 3.10.10
- dbt: 1.6.0
```

**Comment by dbeatty10** [comment] 2023-08-04 22:34
Thanks for reporting this @sweco !

That seems reasonable that the current working directory should be the same before and after a call to `dbtRunner().invoke()`.

The following is one option for a solution with dbt-core (that I didn't test at all). It would basically be a bandaid, so it may or may not be something we'd want to merge.

[`core/dbt/cli/main.py`](https://github.com/dbt-labs/dbt-core/blob/424c6365339c32a974ff458d01e0f9a526329861/core/dbt/cli/main.py#L74)

```python
import os
```

```python

    def invoke(self, args: List[str], **kwargs) -> dbtRunnerResult:
        # Store the initial current working directory
        initial_cwd = os.getcwd()
        try:
```
...
```python
        except BaseException as e:
            return dbtRunnerResult(
                exception=e,
                success=False,
            )
        finally:
            # Return to the initial current working directory
            os.chdir(initial_cwd)
```

**Comment by jasondamour** [comment] 2023-08-08 07:51
I just spent several hours debugging this 😑 Its pretty unintuitive for a command to leave the CWD changed, silently and implicitly. Especially when it doesn't when running from the CLI ➕**1**

**Comment by jtcohen6** [comment] 2023-12-03 14:58
I'm going to close this as a duplicate of https://github.com/dbt-labs/dbt-core/issues/8326, which is the same bug report with more recent activity.

**Closed by jtcohen6** 2023-12-03 14:58 UTC
Labels: bug, duplicate, api, backport 1.5.latest, backport 1.6.latest

**Comment by jasondamour** [comment] 2023-12-06 19:33
@jtcohen6 if I'm not mistaken, you marked this ticket as a duplicate of itself and closed it... Maybe you commented/closed the wrong tab?

**Comment by jtcohen6** [comment] 2023-12-06 19:38
@jasondamour My bad! Good catch, thank you - updated to say this is a duplicate of:
- https://github.com/dbt-labs/dbt-core/issues/8997
