### ISSUE TITLE
[CT-330] [Bug] Behaviour change in quoted columns (when `persist_docs` is enabled) in 1.0 

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#4842] opened 2022-03-08 08:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There appear to be a behaviour change in 1.0 when the following conditions are true:
* Models have column names that are quoted (e.g. `1 as "user_id"`).
* The `persist_docs` config is enabled for the project.

### Expected Behavior

Expected the behaviour to be the same as pre-1.0.

## dbt 1.0.3

1. Add a `dbt_project.yml` like so:

```yml
# dbt_project.yml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "snowflake"

models:
  +persist_docs:
    relation: true
    columns: true
  my_dbt_project:
    +materialized: view
```

2. Add two models:

```sql
-- models/my_model.sql
select 1 as "user_id"

-- models/my_model_2.sql
select "user_id" from {{ ref('my_model') }}
```

3. And define some column docs:

```yml
# models/schema.yml
version: 2

models:
  - name: my_model
    columns:
      - name: "user_id"
        description: Primary key
  - name: my_model_2
    columns:
      - name: "user_id"
        description: Primary key
```

4. `dbt run`:

```
08:06:35  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
08:06:35  Running with dbt=1.0.3
08:06:36  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 180 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
08:06:36  
08:06:42  Concurrency: 1 threads (target='dev')
08:06:42  
08:06:42  1 of 2 START view model dbt_jyeo.my_model....................................... [RUN]
08:06:45  1 of 2 OK created view model dbt_jyeo.my_model.................................. [SUCCESS 1 in 3.06s]
08:06:45  2 of 2 START view model dbt_jyeo.my_model_2..................................... [RUN]
08:06:47  2 of 2 ERROR creating view model dbt_jyeo.my_model_2............................ [ERROR in 2.60s]
08:06:47  
08:06:47  Finished running 2 view models in 11.27s.
08:06:47  
08:06:47  Completed with 1 error and 0 warnings:
08:06:47  
08:06:47  Database Error in model my_model_2 (models/my_model_2.sql)
08:06:47    000904 (42000): SQL compilation error: error line 2 at position 19
08:06:47    invalid identifier '"user_id"'
08:06:47  
08:06:47  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

5. Now remove (or comment out) the `persist_docs` configs:

```yml
# dbt_project.yml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "snowflake"

models:
  my_dbt_project:
    +materialized: view
```

6. `dbt run`:

```
08:08:25  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
08:08:25  Running with dbt=1.0.3
08:08:26  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 180 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
08:08:26  
08:08:32  Concurrency: 1 threads (target='dev')
08:08:32  
08:08:32  1 of 2 START view model dbt_jyeo.my_model....................................... [RUN]
08:08:34  1 of 2 OK created view model dbt_jyeo.my_model.................................. [SUCCESS 1 in 2.78s]
08:08:34  2 of 2 START view model dbt_jyeo.my_model_2..................................... [RUN]
08:08:37  2 of 2 OK created view model dbt_jyeo.my_model_2................................ [SUCCESS 1 in 2.84s]
08:08:37  
08:08:37  Finished running 2 view models in 11.21s.
08:08:37  
08:08:37  Completed successfully
08:08:37  
08:08:37  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

## dbt 0.21.0

1. Set it up like the example above where `persist_docs` is enabled.
2. `dbt run`:

```
Running with dbt=0.21.0
Found 2 models, 0 tests, 0 snapshots, 0 analyses, 173 macros, 0 operations, 0 seed files, 0 sources, 0 exposures

21:11:37 | Concurrency: 1 threads (target='dev')
21:11:37 | 
21:11:37 | 1 of 2 START view model dbt_jyeo.my_model............................ [RUN]
21:11:39 | 1 of 2 OK created view model dbt_jyeo.my_model....................... [SUCCESS 1 in 2.69s]
21:11:39 | 2 of 2 START view model dbt_jyeo.my_model_2.......................... [RUN]
21:11:42 | 2 of 2 OK created view model dbt_jyeo.my_model_2..................... [SUCCESS 1 in 2.62s]
21:11:42 | 
21:11:42 | Finished running 2 view models in 10.90s.

Completed successfully

Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

### Environment

```markdown
- OS: macOS 12.1
- Python: 3.9.7
- dbt: 1.0.3
```

### What database are you using dbt with?

snowflake

### Additional Context

There's some discussion about this here https://getdbt.slack.com/archives/CBSQTAPLG/p1640201894328100 - note I could not find this issue being reported when I was searching for it.

**Comment by jtcohen6** [comment] 2022-03-08 13:32
@jeremyyeo Thanks for opening with the really clear reproduction case!

This one is Snowflake-specific, and we've got an issue/comment that (partially) drives at it: https://github.com/dbt-labs/dbt-snowflake/issues/73#issuecomment-1004824012

The problem actually comes when trying to create the _second_ model, or to `select "user_id" from my_model` at all. The reason? We've created `my_model` with an explicit column list, to support its column comments at creation time, and in that list `user_id` is unquoted:
```sql
create or replace  view ad_hoc.dbt_jcohen.my_model 
( 
  user_id COMMENT $$Primary key$$
)
   as (
    select 1 as "user_id"
  );
```

The fix here just requires us to wrap `user_id` in quotes. dbt actually knows how to do this! It just requires specifying `quote: true` on the column:
```yml
# models/schema.yml
version: 2

models:
  - name: my_model
    columns:
      - name: "user_id"
        quote: true
        description: Primary key
  - name: my_model_2
    columns:
      - name: "user_id"
        quote: true
        description: Primary key
```
When I do that, both models run successfully.

Is this ideal behavior, needing to specify quotes in the query _and_ quotes in the yaml file? I don't know of another way for dbt to know this information, short of parsing SQL. The fact remains, we _highly_ discourage use of quoting on Snowflake, because it runs into these sorts of issues.

I'm going to close this one, though I think we'll continue to see tweaks come in for the logic on `dbt-snowflake`, which has been an experiment in what's possible when using `get_columns_in_query`. That includes one proposed the other day, to avoid the risk of the column list if there's no need, because the user has provided no column-level comments: https://github.com/dbt-labs/dbt-snowflake/issues/102

**Closed by jtcohen6** 2022-03-08 13:32 UTC
Labels: bug
