### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by yonatan-cohen8186** [dbt-labs/dbt-core#10497] opened 2024-07-29 08:48 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently, installing the dbt packages, results a ModuleNotFoundError: No module named 'setuptools.command.test' error.
Any solution for that?

### Expected Behavior

Installing dbt packages

### Steps To Reproduce

1. Re install the dbt packages
2. Finish successfully

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jaklan** [comment] 2024-07-29 08:50
https://github.com/pypa/setuptools/issues/4519

**Comment by bramsliepenMJ** [comment] 2024-07-29 09:43
(Temporary) Fix that worked for me was:
```
pip install --upgrade pip-tools pip wheel
pip install setuptools==71.1.0
pip install -r requirements.txt
```

**Comment by ashleemtib** [comment] 2024-07-29 12:01
> (Temporary) Fix that worked for me was:
> 
> ```
> pip install --upgrade pip-tools pip wheel
> pip install setuptools==71.1.0
> pip install -r requirements.txt
> ```

@bramsliepenMJ this does not work for me. What version of dbt-core are you installing?
Thank you!

**Comment by andreineculau** [comment] 2024-07-29 12:56
duplicate. main thread here https://github.com/dbt-labs/dbt-core/issues/10495

**Comment by manugarri** [comment] 2024-07-29 13:21
seems like the logbook 1.5.3 dependency to this repo is causing the setuptools buggy version to fail.

**Comment by dbeatty10** [comment] 2024-07-29 15:36
### Summary
`setuptools` has yanked their release and `dbt-core` can be pip installed again.

### Also
Closing as a duplicate of https://github.com/dbt-labs/dbt-core/issues/10495

**Closed by dbeatty10** 2024-07-29 15:36 UTC
Labels: bug, triage
