### ISSUE TITLE
[CT-1349] [Feature] Dynamic sources

### ISSUE THREAD

**Issue by yang6n** [dbt-labs/dbt-core#6067] opened 2022-10-14 18:41 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I love the lineage that DBT provided to us for free when using `source()`, but we have to define the source schema explicitly. 
As a Developer, I want a way to define the sources by:

- Specify the schema if not default,
- Include or exclude a list with wild card support to define the source tables.

```
version: 2

sources:
  - name: dbt_alice
    schema: dbt_alice
    include_tables: src_*
    or 
    exclude_tables: stg_*_tmp
```

### Describe alternatives you've considered

Use the codegen package to generating the source YML file before `dbt run`
https://github.com/dbt-labs/dbt-codegen/tree/0.8.1/#generate_source-source
generate

### Who will this benefit?

For developers they want lineage but want to include ALL tables as the source, they don't need to define or generate the source.yml

### Are you interested in contributing this feature?

I'd love to contribute if someone point me to the right piece of code and provide some guidance on the source code.

**Comment by yang6n** [comment] 2022-10-14 18:46
Well, the alternatives are not gonna work because if we don't have the source.yml but the models are using `source()`, then it will fail to generate the source.

**Comment by yang6n** [comment] 2022-10-15 15:52
Draft PR - https://github.com/dbt-labs/dbt-core/pull/6072

**Comment by lostmygithubaccount** [comment] 2022-10-23 15:17
thanks for the issue and potential contribution @yang6n! we've been a bit busy with our Coalesce conference this past week, and many of us on the Core team (myself and @jtcohen6 included) are still traveling this week. we'll try to get to this shortly -- you might also consider posting this PR and asking for feedback here in the meantime: https://getdbt.slack.com/archives/C50NEBJGG

**Comment by jtcohen6** [comment] 2022-10-31 04:13
@yang6n Thanks for opening up the issue, and sorry for the delay in getting back to you!

There's a hard line we draw in dbt today, and don't wish to soon erase: **dbt must know the full DAG before it connects to the database.** This is a useful abstraction and simplification for us. We can keep "control plane" code (DAG definitions) clearly separate from "data plane" code (tabular queries / dataframe manipulations). Every dbt resource maps to exactly one database object (or zero, in the case of ephemeral models, analyses, etc).

For that reason, it's essential that we **don't** require dbt to make a database connection — even if it's just a caching query — to enumerate the set of available sources.

---

At the same time, I totally see why folks want this! Source tables are (more-than-a-)a dime a dozen; they're constantly cropping up left, right, & center. Maybe it's a good thing that you have to explicitly "pull them into" your dbt project / analytical universe, and codegen can be your friend...

Still, I recently heard a compelling version of this story from our friends at Materialize, which has a tendency to accept one write-ahead log coming in (one "source"), and dynamically split it up into _many_ table-looking relations, prime for dbt modeling. @morsapaes just coined the delightful term "multiplexed relations" to discuss them over in https://github.com/dbt-labs/dbt-core/discussions/6104#discussioncomment-3957001.

---

Is there merit in the idea of a single "dynamic" source? Normally, dbt will validate that the `source()` you're asking for is actually one you've defined in your yaml files. (It actually doesn't validate that the table really exists in the database—again, because DAG nodes are defined independent on database state—a very good thing.) What if you could tell dbt, "Don't worry about this one?"

```yml
version: 2
sources:
  - name: my_dynamic_source
    database: raw
    schema: big_schema
    tables: *  # just imagining, could also be the word 'dynamic'
```
```sql
-- models/my_model.sql
select * from {{ source('my_dynamic_source', 'specific_table') }}
```
dbt would accept the second argument as the name of a table, and trust you that it exists:
```sql
-- compiled
select * from raw.big_schema.specific_table
```
In the DAG viz, you'd just see that `my_model` depends on `my_dynamic_source.*`:
```mermaid
graph LR;
    my_dynamic_source.*-->my_model;
    style my_dynamic_source.* fill:#5fb825,color:white
    style my_model fill:#0094b3,color:white;
```

---

Having written all that out - I just remembered there's a big ol' discussion about this, originally started by @fivetran-joemarkiewicz, over in https://github.com/dbt-labs/dbt-core/discussions/5686!

I'm going to close this issue as a duplicate of that larger one. I'd be happy to have your thoughts & feedback over there, along with everyone else's.

**Closed by jtcohen6** 2022-10-31 04:13 UTC
Labels: enhancement, triage

**Comment by yang6n** [comment] 2022-10-31 23:47
Thanks @jtcohen6 . 
That makes sense we don't want to have the db connection for this reason. 

The `codegen` is not gonna work, in this case, we can't run `codegen` to generate the source if we use `source()` references for anything that is NOT defined yet. It's like a chicken and egg issue here. 

But the idea of "Don't worry about this one?" you mentioned above, it's gonna work for us if we have a way to ask dbt to not validate this source.

**Comment by jtcohen6** [comment] 2022-11-01 11:33
> But the idea of "Don't worry about this one?" you mentioned above, it's gonna work for us if we have a way to ask dbt to not validate this source.

I'll open this as a new issue!
