### ISSUE TITLE
[CT-2052] [Bug] Vars compiled incorrectly when specified in the models yml file

### ISSUE THREAD

**Issue by kyle-kent** [dbt-labs/dbt-core#6880] opened 2023-02-06 22:10 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi,

I specified a var in my dbt_project.yml file with some jinja if statements to change the variable based on the target name. 
```
vars:
  source_database: |
      {% if target.name == 'dev' %} dev
      {% elif target.name == 'prod' %} prod
      {% endif %}
```
That var is then called in schema.yml to specify the source database (this is not the variables only use).
```
sources:
  - name: source_schema
    database: "{{var('source_database')}}"
    tables:
       - name: source_table
```
When the models that call `source('source_schema', 'source_table)` are run they get compiled with the jinja code, not just the specified variable
```
select *
from {% if target.name == 'dev' %} dev
 {% elif target.name == 'prod' %} prod
 {% endif %}
```
This does not happen whenever `"{{var('source_database')"}}` is called elsewhere in the project, only in the source schema.yml file. Also, the source `database:` can be defined with the jinja code and compile correctly. Something about `var()` throws it off.

### Expected Behavior

Have a `{{var()}}` call populate correctly when called in schema.yml like it does elsewhere in the project.

### Steps To Reproduce

1. Create a variable in dbt_projects.yml
2. Create a source and reference its database as `"{{ var('<variable name>')}}`
3. create a model with `from source('<source name>', '<table name>')`

### Environment

```markdown
- OS: Mac M1 Monterey 12.4
- Python: 3.8.9
- dbt: 1.3.1
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment] 2023-02-07 11:37
@lowaperture Sorry for the confusion here. The `vars` dictionary in `dbt_project.yml` is not itself Jinja-rendered. It cannot be used today as a mechanism for reusable "snippets" of conditional logic (based on other `target` or `env_var` values).

Duplicate of:
- https://github.com/dbt-labs/dbt-core/issues/3105
- https://github.com/dbt-labs/dbt-core/issues/6382

Issue to update docs, and make this limitation more clear:
- https://github.com/dbt-labs/docs.getdbt.com/issues/2828

Lengthy discussion:
- https://github.com/dbt-labs/dbt-core/discussions/6170

**Closed by jtcohen6** 2023-02-07 11:37 UTC
Labels: bug, triage
