### ISSUE TITLE
[CT-2298] [Bug] Running `dbt compile` picks up refs even when they are present in comments

### ISSUE THREAD

**Issue by pvij** [dbt-labs/dbt-core#7160] opened 2023-03-13 16:31 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If refs (`{{ ref('model-name-here') }}`) are present in comments in a model file, they are picked up as refs (in the `manifest.json` file) when `dbt compile` is run.

E.g., if there are two model files, `dummy.sql` and `another_dummy.sql`,

dummy.sql
```
select 1;
```

another_dummy.sql
```
-- {{ ref('dummy') }}

select 2;
```

The node "another_dummy" in the manifest file has refs set to [['dummy']].

This is not an issue until a file self references itself and a cycle is created. E.g., now suppose we have only one model file `dummy.sql` as follows: -

dummy.sql
```
-- {{ ref('dummy') }} dummy comment

select 1;
```

This time, on running `dbt compile`, the following error arises: -
```
❯ dbt compile
16:02:49  Running with dbt=1.4.5
16:02:50  Encountered an error:
Found a cycle: model.bug_dbt.dummy
16:02:50  Traceback (most recent call last):
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/main.py", line 136, in main
    results, succeeded = handle_and_check(args)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/main.py", line 253, in run_from_args
    results = task.run()
              ^^^^^^^^^^
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/task/runnable.py", line 454, in run
    self._runtime_initialize()
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/task/runnable.py", line 165, in _runtime_initialize
    super()._runtime_initialize()
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/task/runnable.py", line 97, in _runtime_initialize
    self.compile_manifest()
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/task/runnable.py", line 91, in compile_manifest
    self.graph = compiler.compile(self.manifest)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/compilation.py", line 486, in compile
    self.link_graph(linker, manifest, add_test_edges)
  File "/Users/prabhatikavij/personal/bug-dbt/venv/lib/python3.11/site-packages/dbt/compilation.py", line 424, in link_graph
    raise RuntimeError("Found a cycle: {}".format(cycle))
RuntimeError: Found a cycle: model.bug_dbt.dummy
```

This case arose for me when I worked on a project where a SQL query (for a single table) had to be converted to a model file and the table name was also present in the comment. The table name present in the comment was accidentally converted to a ref macro referencing the same table name. I had expected the model file to work but I got the error above.

### Expected Behavior

The refs mentioned in comments in the model files shouldn't be picked up.

### Steps To Reproduce

1. Set up a barebones dbt project as follows (in a virtual environment with python 3.11, install the dbt sqlite adapter: `pip install dbt-sqlite`): -
    ```
    ├── dbt_project.yml
    ├── models
    │   └── dummy.sql
   ├── profiles.yml
    ```
   
    dbt_project.yml
    ```
    name: bug_dbt

    config-version: 2
    version: 1.4.5

    profile: your_profile_name
    ```

    profiles.yml
    ```
    your_profile_name:
    target: dev
    outputs:
      dev:
        type: sqlite
        threads: 1
        database: 'database'
        schema: 'main'
        schemas_and_paths:
          main: 'file_path/database_name.db'
        schema_directory: 'file_path'
    ```

    dummy.sql
    ```
    -- {{ ref('dummy') }} dummy comment

    select 1;
    ```
2. After setting the above, run `dbt compile`. You should get the error `RuntimeError: Found a cycle: model.bug_dbt.dummy`.

### Relevant log output

Mentioned above

### Environment

```markdown
- OS: macOS Ventura 13.1
- Python: 3.11.0
- dbt: 1.4.5
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

SQLite adapter (https://docs.getdbt.com/reference/warehouse-setups/sqlite-setup) was used to reproduce the bug, although the choice of the adapter doesn't matter here.

**Comment by MichelleArk** [comment] 2023-03-13 18:29
Hey @pvij! Thank you for opening this issue and the thorough reproduction case.

I do believe picking up refs from comments during compilation is actually the intended behaviour. dbt parses refs from comments to enable 'forcing dependencies' in models that have no ref calls. It's documented here: https://docs.getdbt.com/reference/dbt-jinja-functions/ref#forcing-dependencies:

> In normal usage, dbt knows the proper order to run all models based on the usage of the ref function. There are cases though where dbt doesn't know when a model should be run. An example of this is when a model only references a macro. In that case, dbt thinks the model can run first because no explicit references are made at compilation time. To address this, you can use a SQL comment along with the ref function — dbt will understand the dependency, and the compiled query will still be valid:  -- depends_on: {{ ref('upstream_parent_model') }}

In terms of the specific cycle issue you're running into - you could comment `-- ref('dummy') ` instead of `-- {{ ref('dummy') }}` - that way dbt will avoid compiling the ref as a jinja function and raising the `RuntimeError`. 

Closing as not planned / wont fix.

**Closed by MichelleArk** 2023-03-13 18:29 UTC
Labels: bug, triage

**Comment by pvij** [comment] 2023-03-14 01:08
@MichelleArk Ah, missed that part of the documentation. Thank you so much for the prompt response.
