### ISSUE TITLE
[CT-245] [Bug] SQL with Japanese/Chinese characters not applied correctly in Databricks

### ISSUE THREAD

**Issue by george-zubrienko** [dbt-labs/dbt-core#4735] opened 2022-02-16 15:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Have a model like this (reduced the division list for brevity):

```
{{ config(materialized='view') }}

{% set divisions = [
    ('JP-23', 'Aichi', 'Aichi', '愛知県', 'Kanjii', 'Chūbu', 'JP'),
    ('JP-05', 'Akita', 'Akita', '秋田県', 'Kanjii', 'Tōhoku', 'JP'),
]
%}

{% for state_iso_code, state_name, state_name_2, state_name_local, state_name_local_type, region, country_code in divisions %}
select
    '{{ state_iso_code }}'        as state_iso_code
  , '{{ state_name }}'            as state_name
  , '{{ state_name_2 }}'          as state_name_2
  , '{{ state_name_local }}'      as state_name_local
  , '{{ state_name_local_type }}' as state_name_local_type
  , '{{ region }}'                as region
  , '{{ country_code }}'          as country_code
union all
{% endfor %}
select
    '-1'      as state_iso_code
  , '(Blank)' as state_name
  , '(Blank)' as state_name_2
  , '(Blank)' as state_name_local
  , '(Blank)' as state_name_local_type
  , '(Blank)' as region
  , '-1'      as country_code
```

When `dbt compile` is run, everything seems fine:

```
select
    'JP-23'        as state_iso_code
  , 'Aichi'            as state_name
  , 'Aichi'          as state_name_2
  , '愛知県'      as state_name_local
  , 'Kanjii' as state_name_local_type
  , 'Chūbu'                as region
  , 'JP'          as country_code
union all

select
    'JP-05'        as state_iso_code
  , 'Akita'            as state_name
  , 'Akita'          as state_name_2
  , '秋田県'      as state_name_local
  , 'Kanjii' as state_name_local_type
  , 'Tōhoku'                as region
  , 'JP'          as country_code

union all

select
    '-1'      as state_iso_code
  , '(Blank)' as state_name
  , '(Blank)' as state_name_2
  , '(Blank)' as state_name_local
  , '(Blank)' as state_name_local_type
  , '(Blank)' as region
  , '-1'      as country_code
```

Now when `dbt run --model administrative_divisions` is executed against Databricks profile (`type: databricks`), the resuling view is this:
```
CREATE VIEW `auto_replenishment_george_test`.`administrative_divisions` (
  `state_iso_code`,
  `state_name`,
  `state_name_2`,
  `state_name_local`,
  `state_name_local_type`,
  `region`,
  `country_code`)
TBLPROPERTIES (
  'transient_lastDdlTime' = '1645023802')
AS select
    'JP-23'        as state_iso_code
  , 'Aichi'            as state_name
  , 'Aichi'          as state_name_2
  , '???'      as state_name_local
  , 'Kanjii' as state_name_local_type
  , 'Chubu'                as region
  , 'JP'          as country_code
union all

select
    'JP-05'        as state_iso_code
  , 'Akita'            as state_name
  , 'Akita'          as state_name_2
  , '???'      as state_name_local
  , 'Kanjii' as state_name_local_type
  , 'Tohoku'                as region
  , 'JP'          as country_code

union all

select
    '-1'      as state_iso_code
  , '(Blank)' as state_name
  , '(Blank)' as state_name_2
  , '(Blank)' as state_name_local
  , '(Blank)' as state_name_local_type
  , '(Blank)' as region
  , '-1'      as country_code
```

The **???** is not what we expected to see :)

### Expected Behavior

Japanese/Chinese characters are sent correctly to the actual database, without being replaced with questionmarks.

### Steps To Reproduce

Described in Current Behaviour

### Relevant log output

```shell
Log seems to be fine:

15:03:22.101320 [debug] [Thread-1  ]: On model.auto_replenishment.administrative_divisions: /* {"app": "dbt", "dbt_version": "1.0.1", "profile_name": "auto_replenishment", "target_name": "dev", "node_id": "model.auto_replenishment.administrative_divisions"} */
create or replace view auto_replenishment_george_test.administrative_divisions
  
  as
    




select
    'JP-23'        as state_iso_code
  , 'Aichi'            as state_name
  , 'Aichi'          as state_name_2
  , '愛知県'      as state_name_local
  , 'Kanjii' as state_name_local_type
  , 'Chūbu'                as region
  , 'JP'          as country_code
union all

select
    'JP-05'        as state_iso_code
  , 'Akita'            as state_name
  , 'Akita'          as state_name_2
  , '秋田県'      as state_name_local
  , 'Kanjii' as state_name_local_type
  , 'Tōhoku'                as region
  , 'JP'          as country_code
union all
...
```
```


### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt: 1.0.1
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - databricks: 1.0.1
  - spark: 1.0.0

**Comment by jtcohen6** [comment] 2022-02-17 13:08
@george-zubrienko Thanks for the thorough bug report!

Given that the `dbt compile` result looks okay—and I assume you'd see the same thing in `logs/dbt.log`—I don't think the cause of the issue lives in `dbt-core`. I was able to run the exact same view in `dbt-postgres`, and confirm that the correct characters appear in Postgres:
```
psql (14.1)
Type "help" for help.

jerco=# select * from dbt_jcohen.my_view;
 state_iso_code | state_name | state_name_2 | state_name_local | state_name_local_type | region  | country_code
----------------+------------+--------------+------------------+-----------------------+---------+--------------
 JP-23          | Aichi      | Aichi        | 愛知県           | Kanjii                | Chūbu   | JP
 JP-05          | Akita      | Akita        | 秋田県           | Kanjii                | Tōhoku  | JP
 -1             | (Blank)    | (Blank)      | (Blank)          | (Blank)               | (Blank) | -1
```

I assume this issue is cropping up in one of three places:
- The optimizer / query rewriter for Databricks SQL endpoints (unlikely)
- [`databricks-sql-connector`](https://pypi.org/project/databricks-sql-connector/), which is used by the `dbt-databricks` plugin to send queries to Databricks SQL endpoints (my guess)
- Somewhere else in the `dbt-databricks` plugin code

So, I'm going to close this issue, and I'd ask you to reopen it in the [`dbt-databricks` repository](https://github.com/databricks/dbt-databricks). The maintainers of that repo (a team at Databricks) will be able to figure out where the fix needs to happen; it may even be in the code that lives there.

**Closed by jtcohen6** 2022-02-17 13:08 UTC
Labels: bug, Team:Adapters
