### ISSUE TITLE
[Bug] state:modified.configs selects unmodified models

### ISSUE THREAD

**Issue by davidggphy** [dbt-labs/dbt-core#10522] opened 2024-08-04 16:22 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running the command 
```dbt  run --select state:modified  --project-dir ./dbt --defer --state target``` 
or w/o --defer `dbt run --select state:modified  --project-dir ./dbt --state target`
several times in a row always selects models.

From the subselectors in `modified`, the only one selecting models is `state:modified.configs`, the rest return no items.

As many of the checks I did, some are:

```dbt run --select state:modified --exclude state:unmodified --project-dir dbt/ --state target``` selects all models in the database.

The items that are in both `dbt ls --select state:modified.configs --project-dir ./dbt --state target --defer` and `dbt ls --select state:unmodified --project-dir ./dbt --state target --defer` are the tests (unique, not null, etc).

Checking the diff among two consecutive manifest.json files, the only entries changing are
```json
"generated_at": "2024-08-04T16:14:19.114724Z",
"invocation_id": "XXXXXXXXXXXX",
```

### Expected Behavior

I would expect that, since nothing have been modified between consecutive runs, `select state:modified` will be empty.

### Steps To Reproduce

In my private environment (sorry) run
```dbt  run --select state:modified  --project-dir ./dbt --defer --state target``` 
several times.

### Environment

```markdown
- OS: macos 14.5
- Python: 3.11.9
- dbt: 1.8.4
Plugins:
  - bigquery: 1.8.2
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment] 2024-08-04 23:26
Thanks for reaching out @davidggphy !

I took a quick shot at reproducing this, but I wasn't able. Could you share example project files and all of the commands that would reproduce the behavior you are seeing? You could try tweaking the example files I tried below:

Files:

`dbt/models/my_model.sql`

```sql
select 1 as id
```

Commands I tried:

```shell
dbt compile --project-dir ./dbt --target-path target
dbt run --select state:modified --project-dir ./dbt --defer --state target
dbt run --select state:modified --project-dir ./dbt --defer --state target
dbt run --select state:modified --project-dir ./dbt --defer --state target
```

Output:

```
(dbt_1.8) $ dbt run --select state:modified --project-dir ./dbt --defer --state target

23:24:56  Running with dbt=1.8.3
23:24:57  Registered adapter: duckdb=1.8.1
23:24:57  Warning: The state and target directories are the same: 'target'. This could lead to missing changes due to overwritten state including non-idempotent retries.
23:24:57  Found 1 model, 406 macros
23:24:57  The selection criterion 'state:modified' does not match any enabled nodes
23:24:57  
23:24:57  Nothing to do. Try checking your model configs and model specification args

(dbt_1.8) $ dbt run --select state:modified --project-dir ./dbt --defer --state target

23:25:16  Running with dbt=1.8.3
23:25:16  Registered adapter: duckdb=1.8.1
23:25:16  Warning: The state and target directories are the same: 'target'. This could lead to missing changes due to overwritten state including non-idempotent retries.
23:25:16  Found 1 model, 406 macros
23:25:16  The selection criterion 'state:modified' does not match any enabled nodes
23:25:16  
23:25:16  Nothing to do. Try checking your model configs and model specification args

(dbt_1.8) $ dbt run --select state:modified --project-dir ./dbt --defer --state target

23:25:19  Running with dbt=1.8.3
23:25:19  Registered adapter: duckdb=1.8.1
23:25:19  Warning: The state and target directories are the same: 'target'. This could lead to missing changes due to overwritten state including non-idempotent retries.
23:25:19  Found 1 model, 406 macros
23:25:19  The selection criterion 'state:modified' does not match any enabled nodes
23:25:19  
23:25:19  Nothing to do. Try checking your model configs and model specification args
```

Are you also seeing the following warning in your output?

```
Warning: The state and target directories are the same: 'target'. This could lead to missing changes due to overwritten state including non-idempotent retries.
```

**Comment by davidggphy** [comment] 2024-08-05 04:28
Thanks for your quick answer @dbeatty10 :) 

Let me answer some of your questions
> Are you also seeing the following warning in your output?
Yes, I'm seeing that warning. But I can instead save the `manifest.json` file into another folder, and the problem persists.

Right now, the problem is appearing in a private repo that I can't share. I'll try to build a toy version that has the same problem.

Commands I run:
```bash
dbt compile --project-dir ./dbt --target-path target  
dbt run --select state:modified --project-dir ./dbt --defer --state target 
dbt run --select state:modified --project-dir ./dbt --defer --state target 
```

Output I get:
```bash
» dbt compile --project-dir ./dbt --target-path target                                         
04:24:22  Running with dbt=1.8.4
04:24:23  Registered adapter: bigquery=1.8.2
04:24:23  Found 53 models, 11 seeds, 53 data tests, 47 sources, 588 macros
04:24:23  
04:24:24  Concurrency: 8 threads (target='dev')
04:24:24  

» dbt run --select state:modified --project-dir ./dbt --defer --state target                   (sumauto) 00:24:25
04:24:33  Running with dbt=1.8.4
04:24:34  Registered adapter: bigquery=1.8.2
04:24:34  Warning: The state and target directories are the same: 'target'. This could lead to missing changes due to overwritten state including non-idempotent retries.
04:24:34  Found 53 models, 11 seeds, 53 data tests, 47 sources, 588 macros
04:24:34  
04:24:36  Concurrency: 8 threads (target='dev')
04:24:36  
RUN AND CREATING OF VIEWS
04:24:57  
04:24:57  Finished running 53 view models in 0 hours 0 minutes and 22.69 seconds (22.69s).
04:24:57  
04:24:57  Completed successfully
04:24:57  
04:24:57  Done. PASS=53 WARN=0 ERROR=0 SKIP=0 TOTAL=53

» dbt run --select state:modified --project-dir ./dbt --defer --state target                   (sumauto) 00:24:57
04:25:26  Running with dbt=1.8.4
04:25:26  Registered adapter: bigquery=1.8.2
04:25:27  Warning: The state and target directories are the same: 'target'. This could lead to missing changes due to overwritten state including non-idempotent retries.
04:25:27  Found 53 models, 11 seeds, 53 data tests, 47 sources, 588 macros
04:25:27  
04:25:28  Concurrency: 8 threads (target='dev')
04:25:28  
RUN AND CREATING OF VIEWS
04:25:49  
04:25:49  Finished running 53 view models in 0 hours 0 minutes and 21.67 seconds (21.67s).
04:25:49  
04:25:49  Completed successfully
04:25:49  
04:25:49  Done. PASS=53 WARN=0 ERROR=0 SKIP=0 TOTAL=53
```

**Comment by dbeatty10** [comment] 2024-08-05 13:41
Thanks for those commands and log output and confirming you get that warning as well.

> I'll try to build a toy version that has the same problem.

Awesome! Once you're able to share that, I'll take another look.

**Comment by jeremyyeo** [comment] 2024-08-23 00:05
We can repro like this:

```sql
-- macros/my_macro.sql
{% macro my_macro() %}
    {% set query %}
    select '{{ invocation_id }}' as inv_id
    {% endset %}
    {{ query }}
{% endmacro %}

-- models/foo.sql
{{ config(post_hook = my_macro()) }}
select 1 c
```

^ Important to note here that the post_hook config is not doing "jinja macro in string" like we show in our docs all the time but calling the macro like a function directly.

```sh
$ rm -rf target target_old
$ dbt run && mv target target_old

23:58:28  Running with dbt=1.8.5
23:58:28  Registered adapter: postgres=1.8.2
23:58:28  Unable to do partial parsing because saved manifest not found. Starting full parse.
23:58:28  Found 1 model, 418 macros
23:58:28  
23:58:28  Concurrency: 4 threads (target='pg')
23:58:28  
23:58:28  1 of 1 START sql table model public.foo ........................................ [RUN]
23:58:28  1 of 1 OK created sql table model public.foo ................................... [SELECT 1 in 0.07s]
23:58:29  
23:58:29  Finished running 1 table model in 0 hours 0 minutes and 0.24 seconds (0.24s).
23:58:29  
23:58:29  Completed successfully
23:58:29  
23:58:29  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

$ dbt run -s state:modified --defer --state target_old
23:58:57  Running with dbt=1.8.5
23:58:57  Registered adapter: postgres=1.8.2
23:58:57  Unable to do partial parsing because saved manifest not found. Starting full parse.
23:58:58  Found 1 model, 418 macros
23:58:58  
23:58:58  Concurrency: 4 threads (target='pg')
23:58:58  
23:58:58  1 of 1 START sql table model public.foo ........................................ [RUN]
23:58:58  1 of 1 OK created sql table model public.foo ................................... [SELECT 1 in 0.06s]
23:58:58  
23:58:58  Finished running 1 table model in 0 hours 0 minutes and 0.23 seconds (0.23s).
23:58:58  
23:58:58  Completed successfully
23:58:58  
23:58:58  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

$ dbt run -s state:modified.configs --defer --state target_old
23:59:24  Running with dbt=1.8.5
23:59:24  Registered adapter: postgres=1.8.2
23:59:24  Found 1 model, 418 macros
23:59:24  
23:59:24  Concurrency: 4 threads (target='pg')
23:59:24  
23:59:24  1 of 1 START sql table model public.foo ........................................ [RUN]
23:59:24  1 of 1 OK created sql table model public.foo ................................... [SELECT 1 in 0.07s]
23:59:24  
23:59:24  Finished running 1 table model in 0 hours 0 minutes and 0.21 seconds (0.21s).
23:59:24  
23:59:24  Completed successfully
23:59:24  
23:59:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

The post-hook `config` / `unrendered_config` is changing due to calling the macro like a function instead of a "jinja macro in string":

![image](https://github.com/user-attachments/assets/e7b98963-fd8a-4edd-bde0-8d7d25a854d6)

----

This doesn't happen if we used the recommended pattern of:

```sql
-- models/foo.sql
{{ config(post_hook = "{{ my_macro() }}") }}
select 1 c
```

```sh
(venv_dbt_1.8.latest) ➜  dbt-basic git:(main) ✗ dbt run                                                      
00:03:37  Running with dbt=1.8.5
00:03:37  Registered adapter: postgres=1.8.2
00:03:37  Unable to do partial parsing because saved manifest not found. Starting full parse.
00:03:38  Found 1 model, 418 macros
00:03:38  
00:03:38  Concurrency: 4 threads (target='pg')
00:03:38  
00:03:38  1 of 1 START sql table model public.foo ........................................ [RUN]
00:03:38  1 of 1 OK created sql table model public.foo ................................... [SELECT 1 in 0.07s]
00:03:38  
00:03:38  Finished running 1 table model in 0 hours 0 minutes and 0.23 seconds (0.23s).
00:03:38  
00:03:38  Completed successfully
00:03:38  
00:03:38  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
(venv_dbt_1.8.latest) ➜  dbt-basic git:(main) ✗ mv target target_old
(venv_dbt_1.8.latest) ➜  dbt-basic git:(main) ✗ dbt run -s state:modified --defer --state target_old
00:03:51  Running with dbt=1.8.5
00:03:51  Registered adapter: postgres=1.8.2
00:03:51  Unable to do partial parsing because saved manifest not found. Starting full parse.
00:03:51  Found 1 model, 418 macros
00:03:51  The selection criterion 'state:modified' does not match any enabled nodes
00:03:51  
00:03:51  Nothing to do. Try checking your model configs and model specification args
```

![image](https://github.com/user-attachments/assets/7f6591f7-0294-48b4-9fef-bf648d7f42a9)

**Comment by dbeatty10** [comment] 2024-08-23 23:16
@jeremyyeo Thanks for that example and all that detail! 🤩

You nailed the explanation:
- Using `post_hook="{{ my_macro() }}"` will keep things constant and not flag the model as being modified (because hooks are "late-rendered")
- Using just `post_hook=my_macro()` will flag the model as being modified if the return value of my_macro() changes at all

(There's some examples of the former [here](https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end#call-a-macro-to-grant-privileges) and [here](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook#apache-spark-analyze-tables-after-creation).)

Both of these are fully expected, so I'm going to close this as not a bug and "not planned".

**Closed by dbeatty10** 2024-08-23 23:16 UTC
Labels: bug, triage, state

**Comment by davidggphy** [comment] 2024-08-25 03:54
Hey @dbeatty10  and @jeremyyeo ,

I've tried a procedure similar to yours, this is, applying:
```bash
rm -rf target target_old
dbt run --full-refresh && mv target target_old
```
<img width="914" alt="image" src="https://github.com/user-attachments/assets/b1eb4923-3c2e-44d9-899f-18b49b7ad84d">
<img width="923" alt="image" src="https://github.com/user-attachments/assets/e74b0b80-d550-4c45-add5-f7e5b4ad4bed">


```bash
dbt run -s state:modified --defer --state target_old
```
<img width="910" alt="image" src="https://github.com/user-attachments/assets/96e76618-b3c3-4fe0-87f7-eef12045abc8">
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/8858e34f-cbcf-4ca0-ac30-b81f39652ec9">

As you can see, it goes through all 59 models again. Also, it raises the message
`Unable to do partial parsing because saved manifest not found. Starting full parse.`

Finally, I can compare both `manifest.json` files, the one in `target_old` against the one in `target`, where the only differences are in the fields: "generated_at", "invocation_id" and "created_at".

Since there are a lot of "created_at" fields, I first do a regex replacement with `"created_at": \d*\.\d*` for an empty string.

Here is a screenshot where you can check that the only diffs are in the "generated_at" and "invocation_id" fields (after removing the "creted_at" ones:
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/87e83311-ed8d-4832-b123-83be051a213a">

Sorry for the white rectangles, there were some personal names.

**Comment by jeremyyeo** [comment] 2024-08-25 23:32
@davidggphy Can you provide a minimal reproduction case like I did? A full example of a model/macro/yml required to produce the problem? My recommendation for you to do more debugging is perhaps remove all your code - add a single `foo.sql` model - do you still get the problem? 

<img width="1912" alt="image" src="https://github.com/user-attachments/assets/f038b157-9889-454e-916d-946f484c26bb">

^ When I have a completely empty BQ project - see how I only have 473 macros while you have some 700+? There's something very specific to your project - packages/macros/etc that is most likely triggering this - and we can't know more without a minimal reproduction case.

**Comment by davidggphy** [comment] 2024-08-26 03:32
@jeremyyeo after a lot debugging, both trying to simplify my project to the bare minimum and being able to reproduce the problem in your toy repo `dbt-basic`, I was able to figure out what the problem is. 

I was able to reproduce the problem (dbt things there are configs modifications) with the following `profiles.yml` file:
```yaml
name: my_dbt_project
profile: 'profile'
config-version: 2
version: "1.0.0"

models:
  +start: 2024-01-01 # needed for sqlmesh
  my_dbt_project:
    +materialized: table
```

This is, in out project there is a line after models with `+start: 2024-01-01 # needed for sqlmesh`

**Comment by jeremyyeo** [comment] 2024-08-26 23:49
@davidggphy What a strange thing hah. Defintely reproducible via:

```yaml
# dbt_project.yml
name: my_dbt_project
profile: all
config-version: 2
version: "1.0.0"

models:
  +justanotherconfig: 1970-01-01
  my_dbt_project:
    +materialized: table
```

```sh
$ rm -rf target target_old && dbt run && mv target target_old && dbt run -s state:modified --defer --state target_old

23:46:38  Running with dbt=1.8.5
23:46:39  Registered adapter: postgres=1.8.2
23:46:39  Unable to do partial parsing because saved manifest not found. Starting full parse.
23:46:39  Found 1 model, 417 macros
23:46:39  
23:46:39  Concurrency: 4 threads (target='pg')
23:46:39  
23:46:39  1 of 1 START sql table model public.foo ........................................ [RUN]
23:46:39  1 of 1 OK created sql table model public.foo ................................... [SELECT 1 in 0.05s]
23:46:39  
23:46:39  Finished running 1 table model in 0 hours 0 minutes and 0.23 seconds (0.23s).
23:46:39  
23:46:39  Completed successfully
23:46:39  
23:46:39  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
23:46:41  Running with dbt=1.8.5
23:46:41  Registered adapter: postgres=1.8.2
23:46:41  Unable to do partial parsing because saved manifest not found. Starting full parse.
23:46:42  Found 1 model, 417 macros
23:46:42  
23:46:42  Concurrency: 4 threads (target='pg')
23:46:42  
23:46:42  1 of 1 START sql table model public.foo ........................................ [RUN]
23:46:42  1 of 1 OK created sql table model public.foo ................................... [SELECT 1 in 0.05s]
23:46:42  
23:46:42  Finished running 1 table model in 0 hours 0 minutes and 0.21 seconds (0.21s).
23:46:42  
23:46:42  Completed successfully
23:46:42  
23:46:42  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

If there's a non-dbt config (full list of dbt ones are https://docs.getdbt.com/reference/model-configs) such as `+start` or like I have `+justanotherconfig` that has a date-like-value... then we get this issue.
