### ISSUE TITLE
[Bug] Test alias not working with dbt_utils.accepted_range

### ISSUE THREAD

**Issue by crystalro0** [dbt-labs/dbt-core#4549] opened 2022-01-04 21:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Customer uses `--store-failures` on some columns in the same model, multiple instances of a test with a `where` clause. For example: two different `dbt_util.accepted_range` tests on different subsets of the same column. 

```
      - name: status
        tests:
          - dbt_utils.accepted_range:
              alias: sale_placed_accepted_range
              where: "status = 'Placed'"
          - dbt_utils.accepted_range:
              alias: sale_shipped_accepted_range
              where: "status = 'Shipped'"
```

They experienced errors in v0.21 with `--store-failures` due to duplicate test names. Aliasing the tests resolved the dupe issue, but since they upgraded to 1.0, this doesn't seem to be working anymore. 

### Expected Behavior

Both tests run with the two aliases from the test config in the yml to differentiate between the two.

### Steps To Reproduce

1. Use environment on v1.0.0 or v1.0.1
2. Add 2 tests to the same column with different where clauses.
3. Run `dbt test --store-failures`
4. Error: 
```
Compilation Error
  dbt found two resources with the name "dbt_utils_accepted_range_test__0"
Since these resources have the same name,
  dbt will be unable to find the correct resource when "dbt_utils_accepted_range_test__0" is used.
```

### Environment

```markdown
- dbt: 1.0.1
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment] 2022-01-06 17:49
@crystalro0 Thanks for opening! This is a duplicate of https://github.com/dbt-labs/dbt-core/issues/4102.

It's a pretty thorny intricate thing that's happening:
- Test configs (including `where`) aren't factored into a test's unique name construction. Test arguments _are_. This gets to a philosophical question of: When is a test the same? When is it different?
- In previous versions of dbt, this didn't work either! The second test would silently _overwrite_ the first test; as a result, `dbt test` would only run one of them. In v1.0, dbt now raises an explicit error, saying it's found the same test defined twice.

I'm going to close this issue, to keep the conversation centralized over in https://github.com/dbt-labs/dbt-core/issues/4102

**Closed by jtcohen6** 2022-01-06 17:49 UTC
Labels: bug, triage, tests, Team:Language
