### ISSUE TITLE
[CT-2746] [Bug] commented out ref macro is included in final DAG

### ISSUE THREAD

**Issue by aendreas** [dbt-labs/dbt-core#7957] opened 2023-06-26 20:12 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When testing certain joins etc and some SQL code remains in the model file, the dbt generated documentation creates a reference to the commented out model.

### Expected Behavior

Commented out code should not be included in the DAG. Therefore the ref function shouldn't create a link since there is no link at that time.

### Steps To Reproduce

Running with dbt-postgres 1.5.1, create a model and comment out a link. run dbt docs generate, then dbt docs serve.

### Environment

```markdown
- OS: Ubuntu
- Python: 3.9
- dbt: 1.5.1
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment] 2023-06-26 21:17
Thank you for reaching out @aendreas !

This is actually intended and expected behavior that you are observing. In particular, it is used to [assert dependencies](https://docs.getdbt.com/reference/dbt-jinja-functions/ref#forcing-dependencies) that can't be determined otherwise.

One way to quickly comment out a reference and simultaneously keep it from showing up in the DAG is to put a space between the first two curly braces like this:
```
 -- this will show up in the DAG:  {{ ref('upstream_parent_model_2') }}
 -- but this will be ignored:      { { ref('upstream_parent_model_1') }}
 {{ your_macro('variable') }}
```

I'm going to close this since the dbt parser is behaving as expected, but I'm happy to continue the conversation within this thread if you have any thoughts or questions.

**Closed by dbeatty10** 2023-06-26 21:17 UTC
Labels: bug, triage

**Comment by aendreas** [comment] 2023-06-27 07:06
Ah I see, many thanks for the clarification!
