### ISSUE TITLE
[Bug] Special characters can appear in debug logs

### ISSUE THREAD

**Issue by BrJan** [dbt-labs/dbt-core#9442] opened 2024-01-24 21:07 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Special characters can occasionally appear in debug logs.
### Expected Behavior

Special characters shouldn’t be in debug logs.

### Steps To Reproduce

N/A

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dbeatty10** [comment] 2024-01-25 01:14
Hey @BrJan 👋 !

Are special characters at the beginning of each log line what you are referring to (like below)?

```
============================== 08:41:20.198115 | 2cece633-285c-4dfb-89c0-123c00168b1d ==============================
[0m08:41:20.198115 [info ] [MainThread]: Running with dbt=1.7.5
[0m08:41:20.203634 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/dbeatty/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt ls', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'False'}
[0m08:41:20.204469 [error] [MainThread]: Encountered an error:
```

If so, these can be suppressed using one of the [use_colors](https://docs.getdbt.com/reference/global-configs/print-output#print-color) configs.

Here's an example command:
```
dbt --no-use-colors-file list
```

You can also use an environment variable like this:
```
export DBT_USE_COLORS_FILE=false
```

If not, do you have any examples you can share?

**Comment by skondiparthigithub** [comment] 2024-03-14 17:25
Hi @dbeatty10, These special characters is showing up in console logout too. I have attached a sample screenshot with the special characters.
![image](https://github.com/dbt-labs/dbt-core/assets/77125321/84a75902-bf60-4007-ae92-ea74a494f086)

Let me know if you need any additional information.

**Comment by dbeatty10** [comment] 2024-03-14 19:18
Thanks for this screenshot @skondiparthigithub!

I haven't been able to replicate this yet.

Could you share any or all of following?
- the output of `dbt --version`
- some simplified code to replicate this issue
- the command(s) you ran
- if you are using [environment variables](https://docs.getdbt.com/reference/global-configs/about-global-configs#available-flags) to control your colorization, the value of `DBT_USE_COLORS` and/or `DBT_USE_COLORS_FILE`

**Comment by dbeatty10** [comment] 2024-03-15 13:43
@skondiparthigithub I haven't been able to replicate this, and we won't be able to do anything unless we can.

See below for what I tried using dbt 1.4.9. Can you try this out in a brand new stand-alone project and see if you can tweak it to reproduce the issue you are seeing? If you are able to reproduce it, can you share all the details similar to below?

`models/my_model.sql`

```sql
select 1 as id
```

`profiles.yml`

```yaml
config:
  use_colors: False
```

Command:
```shell
dbt run -s my_model 
```

Output:

```
$ dbt run -s my_model    
13:33:53  Running with dbt=1.4.9
13:33:53  Unable to do partial parsing because profile has changed
13:33:54  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 291 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
13:33:54  
13:33:54  Concurrency: 5 threads (target='postgres')
13:33:54  
13:33:54  1 of 1 START sql view model dbt_dbeatty.my_model ............................... [RUN]
13:33:54  1 of 1 OK created sql view model dbt_dbeatty.my_model .......................... [CREATE VIEW in 0.10s]
13:33:54  
13:33:54  Finished running 1 view model in 0 hours 0 minutes and 0.34 seconds (0.34s).
13:33:54  
13:33:54  Completed successfully
13:33:54  
13:33:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

<img width="819" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/8563d9f7-3dc3-4688-96a0-420e0d29ffcd">

I get the same result if I remove `use_colors` entirely from `profiles.yml` and run the following command instead:
```shell
dbt --no-use-colors run -s my_model    
```

**Comment by skondiparthigithub** [comment] 2024-03-18 16:30
Hi @dbeatty10, seems you are checking under debug logs, for this issue we need it from Console Logs tab. You can download the logs from Console tab.

![image](https://github.com/dbt-labs/dbt-core/assets/77125321/bb99b484-b3af-4431-b90f-1141d98179ac)

**Comment by skondiparthigithub** [comment] 2024-03-18 21:33
> @skondiparthigithub I haven't been able to replicate this, and we won't be able to do anything unless we can.
> 
> See below for what I tried using dbt 1.4.9. Can you try this out in a brand new stand-alone project and see if you can tweak it to reproduce the issue you are seeing? If you are able to reproduce it, can you share all the details similar to below?
> 
> `models/my_model.sql`
> 
> ```sql
> select 1 as id
> ```
> 
> `profiles.yml`
> 
> ```yaml
> config:
>   use_colors: False
> ```
> 
> Command:
> 
> ```shell
> dbt run -s my_model 
> ```
> 
> Output:
> 
> ```
> $ dbt run -s my_model    
> 13:33:53  Running with dbt=1.4.9
> 13:33:53  Unable to do partial parsing because profile has changed
> 13:33:54  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 291 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
> 13:33:54  
> 13:33:54  Concurrency: 5 threads (target='postgres')
> 13:33:54  
> 13:33:54  1 of 1 START sql view model dbt_dbeatty.my_model ............................... [RUN]
> 13:33:54  1 of 1 OK created sql view model dbt_dbeatty.my_model .......................... [CREATE VIEW in 0.10s]
> 13:33:54  
> 13:33:54  Finished running 1 view model in 0 hours 0 minutes and 0.34 seconds (0.34s).
> 13:33:54  
> 13:33:54  Completed successfully
> 13:33:54  
> 13:33:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
> ```
> 
> <img alt="image" width="819" src="https://private-user-images.githubusercontent.com/44704949/313210310-8563d9f7-3dc3-4688-96a0-420e0d29ffcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODk0NjgsIm5iZiI6MTcxMDc4OTE2OCwicGF0aCI6Ii80NDcwNDk0OS8zMTMyMTAzMTAtODU2M2Q5ZjctM2RjMy00Njg4LTk2YTAtNDIwZTBkMjlmZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE5MTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYjBkMTlhNjY0ZGQwNDNhN2JjZDZjZTBjNWFlYWUzYmUyOGU1MjI1MTQ1Njg4MWUxZDQxMWY2YzY5YWVkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_0Bp6pfym0nB0whMOmWbjVx5uzMWO2tsZm8OeiMEzA">
> I get the same result if I remove `use_colors` entirely from `profiles.yml` and run the following command instead:
> 
> ```shell
> dbt --no-use-colors run -s my_model    
> ```

Hi @dbeatty10, could you please download the log files into your local machine and view for special characters. In the UI these special characters may not be visible.

**Comment by dbeatty10** [comment] 2024-03-21 00:08
I see what you are saying @skondiparthigithub

<img width="934" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/114ab216-569c-4ce1-8070-ae601a222d64">

Viewing on my local machine after clicking the "Download logs" button:

<img width="903" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/bc5f3334-d51e-46b4-b37b-28aa6b22f993">

**Comment by dbeatty10** [comment] 2024-03-21 14:49
### Workaround

See below for a simple python script that will strip [ANSI/ISO control sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) from of a text file.

This can come in handy if downloading log output in dbt Cloud via a "Download Logs" button or for dbt Core users that have log files created with [`--use-colors-file`](https://docs.getdbt.com/reference/global-configs/logs#color).

It can be called like any of these variations (with the default being `logs/dbt.log`):
```shell
python csi_scrubber.py input_file.txt output_file.txt
python csi_scrubber.py input_file.txt
python csi_scrubber.py
```

Note: the latter two _will_ overwrite the previous contents of the file.

### Python script

```python
# csi_scrubber.py

import re
import sys

# Define default file paths
input_file_path = output_file_path = "logs/dbt.log"

# Compile the regular expression pattern for matching CSI sequences
csi_pattern = re.compile(r"\033\[[0-9;:<=>?]*(?:[ -/]*[@-~])?")


def remove_csi_sequences(input_path, output_path):
    try:
        with open(input_path, "r", encoding="utf-8") as file:
            content = file.read()

        # Remove all CSI sequences from the content
        cleaned_content = csi_pattern.sub("", content)

        # Write the cleaned content back to the output file
        with open(output_path, "w", encoding="utf-8") as file:
            file.write(cleaned_content)

        print(f"CSI sequences have been removed. Cleaned file saved to {output_path}.")

    except IOError as e:
        print(f"An error occurred while processing the file: {e}")


# Determine the input and output file paths based on command line parameters
if len(sys.argv) == 2:
    # One parameter provided; use it for both input and output
    input_file_path = output_file_path = sys.argv[1]
elif len(sys.argv) > 2:
    # Two or more parameters provided; use the first for input and the second for output
    input_file_path = sys.argv[1]
    output_file_path = sys.argv[2]

# Call the function with the input and output file paths
remove_csi_sequences(input_file_path, output_file_path)
```

**Comment by dbeatty10** [comment] 2024-03-22 13:28
@skondiparthigithub It sounds like you want the following:

> the terminal UI in dbt Cloud should have colorful logs, but clicking the "Download Logs" button should give those same logs _without_ color codes (or any other special characters from [ANSI/ISO control sequences](https://en.wikipedia.org/wiki/ANSI_escape_code)).

If this is indeed what you want, they my recommendation is to submit a request by reaching out to the support team via the "Leave feedback" button in dbt Cloud, making sure link to this GitHub issue. See screenshots below.

Since this is specific to dbt Cloud and not dbt Core, I'm going to close this issue as "not planned" for the dbt-core repo.

### Screenshots of making a feature request in dbt Cloud

Here's a couple screenshots of the process in dbt Cloud:

1. 
<img width="250" alt="Screenshot 2024-03-22 at 7 09 17 AM" src="https://github.com/dbt-labs/dbt-core/assets/44704949/44457c35-fc83-47d7-8737-2ceddc763042">

2. 
<img width="400" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/de9a4773-f7a7-43f3-b0de-54d4e6b21582">

**Closed by dbeatty10** 2024-03-22 13:28 UTC
Labels: bug, triage

**Comment by jeremyyeo** [comment] 2024-04-11 01:42
By setting env var `DBT_USE_COLORS` to `False` in dbt Cloud - we can get those control sequence characters to stop showing up in the downloaded logs.

![image](https://github.com/dbt-labs/dbt-core/assets/8496748/62e6cff9-1184-47c3-9987-7e36a56a252a)

![image](https://github.com/dbt-labs/dbt-core/assets/8496748/024c7390-b7df-44e3-8f6f-4006a4bde710)

![image](https://github.com/dbt-labs/dbt-core/assets/8496748/c0c6d8de-bd3b-4575-adf4-42d2c723a7c8)
