### ISSUE TITLE
[CT-2351] [Feature] Partial parsing support for jinja variables in config

### ISSUE THREAD

**Issue by reubster** [dbt-labs/dbt-core#7261] opened 2023-04-03 13:36 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, when executing any dbt operation in any context, we get the message "Unable to do partial parsing because a project config has changed"

This appears to be because we use jinja expressions to evaluate whether to turn off or on nodes depending on the target environment, leading dbt to think that the project config has 'changed'.

Ideally, dbt would be able to determine whether the project config has _actually_ changed since the last operation, enabling us to use partial parsing as intended.

### Describe alternatives you've considered

Using static project.yml. This would signficantly increase the complexity of testing for the scenarios we are running. 

### Who will this benefit?

Would increase usability of partial parsing for anyone using dynamic expressions in project.yml

**Comment by davidsr2r** [comment] 2023-04-28 00:53
We have the same issue using [dbt_ml](https://github.com/kristeligt-dagblad/dbt_ml), since it uses jinja in the dbt_project.ml file. Would be nice to allow this!

**Comment by dbeatty10** [comment] 2023-09-20 20:34
Suppose we have a `models` directory like this:

```
models
├── central
│   └── new_orleans.sql
└── pacific
    └── san_diego.sql
```

And a `dbt_project.yml` like this:

```yaml
name: my_project
version: 1.0.0

models:
    my_project:
        central:
            +enabled: "{{ target.name == 'central' }}"
        pacific:
            +enabled: "{{ target.name == 'pacific' }}"
```

This worked as expected for me across a range of dbt versions (1.6 down to 1.3):

```shell
dbt build --target central
dbt build --target central
dbt build --target pacific
dbt build --target pacific
```

So I'm going to close this as "can't repro". If someone can provide more information of a simple setup to reproduce the issue, then we can re-open this.

**Closed by dbeatty10** 2023-09-20 20:34 UTC
Labels: enhancement, triage
