### ISSUE TITLE
[CT-3562] [Feature] Catalog queries filters for > 100 nodes

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#9394] opened 2024-01-17 02:28 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Basically as soon as you hit > 100 nodes in the dbt project (regardless of schema) - the newly added functionality of filtering the catalog query (#8648) becomes moot - i.e. we revert back to the old way of retrieving metadata about all relations in a schema.

### Expected Behavior

The best case scenario is we send the list of all relations in the schema in the where clause regardless of the number of nodes in the project. 

However, since there is normally a query text size limit (for example, [Snowflake](https://docs.snowflake.com/en/user-guide/query-size-limits) and [BigQuery](https://cloud.google.com/bigquery/quotas) will only accept (or recommend) a query text size that is up to 1MB in size) - potentially we can chunk up (per schema) those catalog queries? (I guess bonus points if we can detect that the written query will be > 1MB).

The worse case scenario is probably not to revert back to old non-filtering behaviour as soon as we exceed 100 nodes but rather on a schema by schema basis - i.e. only use the non-filtering query IF there is a schema that dbt puts > 100 models into but not the others. This means that in the example below, since schema `dbt_jyeo_marts` was still < 101 models - we still should be using the catalog query that filters.

### Steps To Reproduce

dbt project setup

```yaml
# dbt_project.yml
name: my_dbt_project
profile: all
config-version: 2
version: "1.0.0"

models:
  my_dbt_project:
    +materialized: table
    marts:
      +schema: marts
    stg:
      +schema: stg
```

Add 100 toy `foo` models into `models/marts` like so:

```sql
-- models/foo_000.sql
select 1 id

-- models/foo_001sql
select 1 id

-- models/foo_0XX.sql
select 1 id

-- models/foo_099.sql
select 1 id
```

Build the models then generate docs and look at the catalog query:

```sh
$ dbt run --threads 10
...
2:16:53  93 of 100 OK created sql table model dbt_jyeo_marts.foo_092 .................... [SUCCESS 1 in 2.79s]
02:16:53  98 of 100 OK created sql table model dbt_jyeo_marts.foo_097 .................... [SUCCESS 1 in 2.94s]
02:16:53  97 of 100 OK created sql table model dbt_jyeo_marts.foo_096 .................... [SUCCESS 1 in 2.95s]
02:16:53  96 of 100 OK created sql table model dbt_jyeo_marts.foo_095 .................... [SUCCESS 1 in 2.96s]
02:16:53  95 of 100 OK created sql table model dbt_jyeo_marts.foo_094 .................... [SUCCESS 1 in 2.97s]
02:16:53  99 of 100 OK created sql table model dbt_jyeo_marts.foo_098 .................... [SUCCESS 1 in 2.97s]
02:16:53  94 of 100 OK created sql table model dbt_jyeo_marts.foo_093 .................... [SUCCESS 1 in 2.99s]
02:16:53  100 of 100 OK created sql table model dbt_jyeo_marts.foo_099 ................... [SUCCESS 1 in 2.98s]
02:16:53  
02:16:53  Finished running 100 table models in 0 hours 0 minutes and 37.98 seconds (37.98s).
02:16:53  
02:16:53  Completed successfully
02:16:53  
02:16:53  Done. PASS=100 WARN=0 ERROR=0 SKIP=0 TOTAL=100

$ dbt --debug docs generate
...
             or 
                (
                    upper("table_schema") = upper('dbt_jyeo_marts')
                    and upper("table_name") = upper('foo_003')
                )
             or 
                (
                    upper("table_schema") = upper('dbt_jyeo_marts')
                    and upper("table_name") = upper('foo_058')
                )
             or 
                (
                    upper("table_schema") = upper('dbt_jyeo_marts')
                    and upper("table_name") = upper('foo_026')
                )
             or 
                (
                    upper("table_schema") = upper('dbt_jyeo_marts')
                    and upper("table_name") = upper('foo_020')
                )
            )
        )
        select *
    from tables
    join columns using ("table_database", "table_schema", "table_name")
    order by "column_index"
02:17:31  Opening a new connection, currently in state init
02:17:39  SQL status: SUCCESS 100 in 9.0 seconds
02:17:39  On development_jyeo.information_schema: Close
02:17:40  Catalog written to /Users/jeremy/src/dbt-basic/target/catalog.json
02:17:40  Resource report: {"command_name": "generate", "command_success": true, "command_wall_clock_time": 16.56495, "process_user_time": 7.01914, "process_kernel_time": 0.883472, "process_mem_max_rss": "141221888", "process_in_blocks": "0", "process_out_blocks": "0"}
02:17:40  Command `dbt docs generate` succeeded at 15:17:40.612451 after 16.57 seconds
02:17:40  Connection 'generate_catalog' was properly closed.
02:17:40  Connection 'development_jyeo.information_schema' was properly closed.
02:17:40  Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f3306d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110b0e190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f0829d0>]}
02:17:40  Flushing usage events 
```

^ Truncated but we can see cataloging query is filtering on the 100 models.

Add a singular `bar` model to `models/stg` so we have 101 models:

```sql
-- models/stg/bar.sq
select 1 id
```

Do the above:

```sh
$ dbt run --threads 10
...
02:20:54  100 of 101 OK created sql table model dbt_jyeo_marts.foo_098 ................... [SUCCESS 1 in 2.98s]
02:20:54  95 of 101 OK created sql table model dbt_jyeo_marts.foo_093 .................... [SUCCESS 1 in 3.01s]
02:20:54  94 of 101 OK created sql table model dbt_jyeo_marts.foo_092 .................... [SUCCESS 1 in 3.01s]
02:20:54  96 of 101 OK created sql table model dbt_jyeo_marts.foo_094 .................... [SUCCESS 1 in 3.02s]
02:20:54  98 of 101 OK created sql table model dbt_jyeo_marts.foo_096 .................... [SUCCESS 1 in 3.04s]
02:20:54  97 of 101 OK created sql table model dbt_jyeo_marts.foo_095 .................... [SUCCESS 1 in 3.09s]
02:20:54  101 of 101 OK created sql table model dbt_jyeo_marts.foo_099 ................... [SUCCESS 1 in 3.10s]
02:20:54  93 of 101 OK created sql table model dbt_jyeo_marts.foo_091 .................... [SUCCESS 1 in 3.13s]
02:20:54  99 of 101 OK created sql table model dbt_jyeo_marts.foo_097 .................... [SUCCESS 1 in 3.14s]
02:20:54  
02:20:54  Finished running 101 table models in 0 hours 0 minutes and 38.28 seconds (38.28s).
02:20:54  
02:20:54  Completed successfully
02:20:54  
02:20:54  Done. PASS=101 WARN=0 ERROR=0 SKIP=0 TOTAL=101

# dbt --debug docs generate
...
2:21:50  On development_jyeo.information_schema: /* {"app": "dbt", "dbt_version": "1.7.4", "profile_name": "all", "target_name": "sf", "connection_name": "development_jyeo.information_schema"} */
with tables as (
            select
        table_catalog as "table_database",
        table_schema as "table_schema",
        table_name as "table_name",
        coalesce(table_type, 'DYNAMIC TABLE') as "table_type",
        comment as "table_comment",

        -- note: this is the _role_ that owns the table
        table_owner as "table_owner",

        'Clustering Key' as "stats:clustering_key:label",
        clustering_key as "stats:clustering_key:value",
        'The key used to cluster this table' as "stats:clustering_key:description",
        (clustering_key is not null) as "stats:clustering_key:include",

        'Row Count' as "stats:row_count:label",
        row_count as "stats:row_count:value",
        'An approximate count of rows in this table' as "stats:row_count:description",
        (row_count is not null) as "stats:row_count:include",

        'Approximate Size' as "stats:bytes:label",
        bytes as "stats:bytes:value",
        'Approximate size of the table as reported by Snowflake' as "stats:bytes:description",
        (bytes is not null) as "stats:bytes:include",

        'Last Modified' as "stats:last_modified:label",
        to_varchar(convert_timezone('UTC', last_altered), 'yyyy-mm-dd HH24:MI'||'UTC') as "stats:last_modified:value",
        'The timestamp for last update/change' as "stats:last_modified:description",
        (last_altered is not null and table_type='BASE TABLE') as "stats:last_modified:include"
    from development_jyeo.INFORMATION_SCHEMA.tables
            where (upper("table_schema") = upper('dbt_jyeo_marts') or upper("table_schema") = upper('dbt_jyeo_stg'))
        ),
        columns as (
            select
        table_catalog as "table_database",
        table_schema as "table_schema",
        table_name as "table_name",

        column_name as "column_name",
        ordinal_position as "column_index",
        data_type as "column_type",
        comment as "column_comment"
    from development_jyeo.INFORMATION_SCHEMA.columns
            where (upper("table_schema") = upper('dbt_jyeo_marts') or upper("table_schema") = upper('dbt_jyeo_stg'))
        )
        select *
    from tables
    join columns using ("table_database", "table_schema", "table_name")
    order by "column_index"
02:21:50  Opening a new connection, currently in state init
02:21:54  SQL status: SUCCESS 102 in 3.0 seconds
02:21:54  On development_jyeo.information_schema: Close
02:21:54  Catalog written to /Users/jeremy/src/dbt-basic/target/catalog.json
02:21:54  Resource report: {"command_name": "generate", "command_success": true, "command_wall_clock_time": 11.902139, "process_user_time": 7.301256, "process_kernel_time": 0.97099, "process_mem_max_rss": "141127680", "process_in_blocks": "0", "process_out_blocks": "0"}
02:21:54  Command `dbt docs generate` succeeded at 15:21:54.886059 after 11.90 seconds
02:21:54  Connection 'generate_catalog' was properly closed.
02:21:54  Connection 'development_jyeo.information_schema' was properly closed.
02:21:54  Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1109a4b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b932250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111c382d0>]}
02:21:54  Flushing usage events
```

We no longer filter in the catalog query.

If say one of the above schemas had like thousands of tables or something then we're essentially back in the place where we started prior to implementing this - which would include things like taking up too much memory for the run, etc.

### Environment

```markdown
- OS: macOS
- Python: 3.11.2
- dbt:
Core:
  - installed: 1.7.4
  - latest:    1.7.4 - Up to date!

Plugins:
  - bigquery:  1.7.2 - Up to date!
  - snowflake: 1.7.1 - Up to date!
  - redshift:  1.7.1 - Up to date!
  - postgres:  1.7.4 - Up to date!
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

I filed this here because the  logic appear to be coming from core:

https://github.com/dbt-labs/dbt-core/blob/9f0bcf5666a2b2a754c60f6ece7cc04e9ec81b80/core/dbt/adapters/base/impl.py#L1168-L1181

**Comment by dbeatty10** [comment] 2024-01-18 21:03
@jeremyyeo do you think this is a bug or a feature request?

This looks like a feature request rather than a bug to me, so I re-labeled it. i.e., it would be _nice_ if we're able to apply filtering to catalog queries even when there are more than 100 nodes, but dbt is not behaving erroneously, right?

**Comment by jeremyyeo** [comment] 2024-01-19 00:49
> @jeremyyeo do you think this is a bug or a feature request?

@dbeatty10 - I can't say for sure - we added this functionality / enhancement here to a well known problem: https://github.com/dbt-labs/dbt-core/issues/8521

So I guess if you say that that enhancement was ever only supposed to work for dbt projects with less than 101 nodes -then I guess yeah - this is a feature request.

Playing devils advocate though, I might even ask how many "real" dbt projects have that few nodes? Certainly outside of unit testing type dbt projects - most "actual" (and perhaps I dare say "small") dbt projects would contain more than 100 nodes :grin:

But it's up to ya'll to say whether this is a feature request or a bug.

**Comment by dbeatty10** [comment] 2024-01-19 19:41
Since 100 was intentionally added as a limit, I'm going to leave this as a feature request for now.

But that's a very legit point that having more than 100 nodes is common and we should take a good look at this!

**Comment by graciegoheen** [comment] 2024-01-24 18:16
Hey! 
This was by design - I'll let @peterallenwebb or @mikealfare fill in the details here - but essentially what we ran into was when you try to filter with a `where` clause with over 100 models it actually became _less_ performant than just excluding the where clause all together and getting all of the catalog info for the entire project.

I do wonder if there's a way to still filter at the end (after the query has returned the results) for selecting for greater than 100 models, so that the returned results is as expected. Curious to hear folks thoughts!

**Comment by peterallenwebb** [comment] 2024-01-24 20:38
> but essentially what we ran into was when you try to filter with a where clause with over 100 models it actually became less performant than just excluding the where clause all together and getting all of the catalog info for the entire project.

My recollection is that we just used our best judgement and picked it as a reasonable starting point. If someone did an empirical analysis, I'd love to see it.

The best way forward, in my view, would be to understand the user pain points and solve for those, rather than trying to design further solutions without that important context.

@jeremyyeo You mentioned concerns about memory consumption during docs generate. We have plans to address that in other ways which I think are likely to be much more productive. [See the details here.](https://www.notion.so/dbtlabs/2074a107c57b4adf9b8619cbe71544af?v=574ec2fe8da44559b9550fc24dfe99c8&p=ecdc66ae1da340669b8238611f7a28da&pm=s)

If there are other issues, I just want to make sure we all understand them and the practical context they are coming up in. Which users are experiencing them, and how can we reproduce the issue in order to study and solve it?

**Comment by T-Dunlap** [comment] 2024-01-25 22:41
@peterallenwebb - I ran into a customer pain point yesterday: one of our customers reached out because a user was receiving an error message when running `dbt docs generate` in the IDE. The user doesn't have read access to a specific table within a schema (Table XYZ), so when the docs generate command is run, it returns the database error saying that table XYZ doesn't exist. It caused a bit of confusion for the customer because Table XYZ doesn't exist anywhere in their project. This might also be a cause for concern from a security perspective since the users are viewing table names/info that they shouldn't have access to.

**Comment by dbeatty10** [comment] 2024-02-01 21:37
Per conversation with @graciegoheen, we're interested in two things:
1. https://github.com/dbt-labs/dbt-core/issues/9506
2. Post-processing the result of catalog queries to _only_ include the selected nodes (see [#9394 (comment)](https://github.com/dbt-labs/dbt-core/issues/9394#issuecomment-1908677418))

I've created a spike to cover the 1st part, and this issue can cover the 2nd part

### Acceptance criteria

- regardless if the catalog query itself is pre-filtered or not, post-filter its results
- i.e., `dbt docs generate -s a b c tag:one_hundred_models` should only include those 103 models within `catalog.json`, even if there are 2000 models within the project.

**Comment by graciegoheen** [comment] 2024-02-26 17:45
Closing this in favor of the 2 implementation tickets that have been opened!

**Closed by graciegoheen** 2024-02-26 17:45 UTC
Labels: enhancement

**Comment by dbeatty10** [comment] 2024-02-26 17:53
For convenience, here's links to the two implementation tickets:
1. https://github.com/dbt-labs/dbt-core/issues/9506
2. https://github.com/dbt-labs/dbt-core/issues/9666
