### ISSUE TITLE
[CT-647] [Feature] Enable default Jinja macroses include, extends, etc

### ISSUE THREAD

**Issue by SOVALINUX** [dbt-labs/dbt-core#5247] opened 2022-05-15 11:19 UTC
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Hi colleagues,

Would like to suggest enablement of Jinja FileSystem access, so it will enable such Jinja macroses as `include`, `extends`, etc.
I have several use-cases for it
1. Unit-Testing: add CSV file to the test SQL (I'm using and improving https://github.com/EqualExperts/dbt-unit-testing) - Jinja `include` works great here
2. Unit-Testing: sometimes I need to embed a model SQL into the test to properly handle commented `--depends_on: {{ref('')}}`
3. Simple include of SQL block vs macros (arguable, but still)
4. Found related issue from the past: https://github.com/dbt-labs/dbt-core/issues/1337
5. It will also be useful for workaround issues like https://github.com/dbt-labs/dbt-core/issues/4924

Since access to FileSystem might be potentially dangerous - we may add feature toggle in config for it

### Describe alternatives you've considered

For use-cases with Unit Testing simple hardcode is the workaround
for #3 I can do the same with macroses with some overhead

### Who will this benefit?

Complex use-cases
Users of unit-testing frameworks while DBT still has the open discussion of how to do unit testing

### Are you interested in contributing this feature?

Yes, PR will come soon

### Anything else?

Usage example in Unit Testing with this feature:
```
{% call dbt_unit_testing.mock_ref ('hiring_link_status_order', {"input_format": "csv", "quote_symbol_to_wrap_values": "'"}) %}
  {% include 'seeds/hiring_link_status_order.csv' %}
{% endcall %}
```

**Comment by jtcohen6** [comment] 2022-05-20 09:57
@SOVALINUX Sorry for the delay getting back to you here!

It's clear from the PR you specced out in https://github.com/dbt-labs/dbt-core/pull/5250 that the implementation here is pretty trivial—we're taking advantage of a built-in Jinja capability. So the real question, and the reason I'm responding to you here rather than there: do we _want_ to do this?

To that end, thanks for linking to #1337! These aren't brand-new ideas, and a little history goes a long way. As Drew said there a few years ago, there are two strong hesitations for doing this:
- Practically, though the implementation is quite straightforward it could have unintended implications for how dbt works behind-the-scenes, and we'd need to spend more time thinking through
- Conceptually, we'd want a _very_ clear use case to motivate doing this

I'll add two more, which we didn't have to the same degree a few years ago:
- I'm hesitant about doubling down on Jinja, given the limitations we've found (especially around performance at scale), and our desire to build other types of custom parsers in the future
- I'd like to keep tight control over how dbt interacts with local file systems, given the potential danger (which you call out), but also our colleagues' desire to build differentiated experiences for dbt development/deployment/etc that may find it necessary to jettison a "real" file system

In the words of Paul David Hewson, I still haven't found what I'm looking for. I do see one scenario in that issue which makes some sense to me:

> My use case is Snowflake has stored procedures written in javascript. It would be nice to be able to use the jinja "include" to bring in the javascript from a json file. That way when I am developing javascript in my IDE i get the benefits of all the javascript syntax highlighting and extensions.

I completely empathize with the desire to define a `.js` file, with all its attendant benefits, and pull that file's contents into a macro. It's important that seeds have actual `.csv` file extensions, and that dbt Python models (#5261) will have `.py` extensions, for a very similar reason! I still have to ask, though: Why a stored procedure written in javascript? :)

The other recent comment in the issue is about metrics—which is a thing we've decided to solve as a first-class dbt capability! If people feel _blocked_ by dbt from doing what they need to do, that's something I take seriously. But it takes time to develop the right long-term constructs. In the meantime, I really hesitate to open the door to medium-term constructs that we'll regret later on.

The use case you lay out above is all around **unit testing**, and builds on some very impressive work in the [`dbt-unit-testing`](https://github.com/EqualExperts/dbt-unit-testing) package, which implements an all-in-Jinja approach. I'm not convinced that `include` gets us anything which macros don't, today—except, being able to define CSV fixtures in actual `.csv` files. I think it's tough to have this both ways: Do the fixtures want to live in the same file, for ease of definition? Or in standalone files, for IDE niceties and ease of reuse?

To be clear, **unit testing** dbt macros / models feels like a tremendously important use case, and I care a lot about getting the developer experience here right. We recently built a `pytest` framework for ourselves (Core maintainers), and developers of adapter plugins. It can also be used by anyone who has a sufficiently complex dbt package/project, some `pytest` chops ([the docs](https://docs.pytest.org/en/6.2.x/index.html) are great), and the ability to run Python (`pytest`) commands locally. I put together an example and shared in the unit testing discussion the other day: https://github.com/dbt-labs/dbt-core/discussions/4455#discussioncomment-2766503

An approach in that vein acknowledges that the experiences of "contributor to dbt project" and "maintainer of complex dbt project/package/plugin" might be very slightly different. The holy grail here is, as always, an approach that makes it possible to unit test with just dbt project code and dbt commands. **I think we ought to take that as the end goal, rather than the starting premise.** Rather than constraining ourselves to find the square peg that fits in the squarely Jinja hole, let's figure out the right ergonomic experience first. Then, if it's worth doing, we'll find a way to make it happen out of the box.

Okay, final note: There's one use case that I still find compelling here, and it's the ability to define a "base template" model, which Jinja then `{% extends %}` into its composite models. That's doable with macros today, but sorta ugly, and you do have to pass in any dynamic values as arguments, rather than just inheriting and overriding them. (Granted, there's plenty of people I work with who will tell you that the former functional programming paradigm is preferable to the latter object-oriented paradigm, every day of the week and twice on some days.) I think the real ergonomic enhancement here doesn't look like `{% include %}` or `{% extends %}` at all, so much as the ability to define multiple models in the same file, via `{% model %}` blocks—alongside macros, even—for better visibility and fewer files.

In any case, that discussion is open in https://github.com/dbt-labs/dbt-core/discussions/5101#discussioncomment-2592174. I'd welcome you to participate there, and to respond back with more thoughts here! For now, I am going to close this issue and the PR, as something we are unlikely to implement in the short or medium term.

**Closed by jtcohen6** 2022-05-20 09:57 UTC
Labels: enhancement, triage, Team:Language
