### ISSUE TITLE
[CT-3389] [Bug] dbt cloud credentials

### ISSUE THREAD

**Issue by chihlinc** [dbt-labs/dbt-core#9086] opened 2023-11-15 17:51 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I was using dbt run locally fine. However, after updating it, it shows it requires dbt_could.yml. I have been trying to uninstall and reinstall, remove my dbt_project.yml and recreate it again. 

I do not know what to do, even my professor is a bit confused. 

Below is the code that appears in my terminal. ( I am using mac m2 )

### Expected Behavior

I expect someone to teach me how to solve this problem. 

### Steps To Reproduce

1. I create an virtual environment. 
2. In my terminal, this appears: configuration: dbt_cloud.yml credentials file for dbt Cloud not found. Download your credentials file from dbt Cloud to `/Users/chihlinc/.dbt`
3. I was using fine to set dbt run, dbt build. Suddenly, it is asking for dbt cloud. 

### Relevant log output

I tried dbt clean. it does not work.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

postgres, other (mention it in "Additional Context")

### Additional Context

No

**Comment by gshank** [comment] 2023-11-15 21:28
It sounds like you installed the dbt cloud CLI version of dbt. You probably want to install dbt-core.

**Comment by chihlinc** [comment] 2023-11-15 21:58
@gshank I uninstall dbt, and try to reinstall the dbt core. 

Here is the code I implemented. 
- pip uninstall dbt.
- pip install dbt-core. 
- dbt --version.
dbt Cloud CLI - 0.34.14 (858b40657ace09624460691ad15f62ca9fb2a393 2023-11-03T19:40:57Z)

This still appears.

**Comment by dbeatty10** [comment] 2023-11-16 05:12
@chihlinc the steps to uninstall the dbt Cloud CLI will depend on how you installed it.

For example, if you installed it using `brew install dbt`, then you can uninstall via `brew uninstall dbt`.

You can run `which dbt` to see if you have dbt installed (and where).

Once you have dbt fully uninstalled, then when reinstalling dbt-core, we recommend doing so using a virtual environment like described [here](https://docs.getdbt.com/docs/core/pip-install#using-virtual-environments).

Since this is not a bug in dbt-core but rather unintentionally installing the dbt Cloud CLI, I'm going to close this issue.

**Closed by dbeatty10** 2023-11-16 05:12 UTC
Labels: bug, wontfix
