### ISSUE TITLE
[CT-322] [Bug] run_query nested array column misinterpreted as string by Table.to_json()

### ISSUE THREAD

**Issue by brabster** [dbt-labs/dbt-core#4825] opened 2022-03-04 14:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given a query that selects a repeated column, when I run this macro:

```
{% macro export_formatted_product_tags(output_path) %}
  {% set query %}
    SELECT * FROM {{ ref('model_with_nested_column') }}
  {% endset %}

  {% set results = run_query(query) %}

  {% do results.to_json(output_path) %}
{% endmacro %}
```

I get the array column as a string, eg:
`"[\"foo\", \"bar\", \"baz\"]"`

### Expected Behavior

Array-valued column should be formatted as JSON array, not string:

``["foo", "bar", "baz"]`

### Steps To Reproduce

dbt 1.0.1

This macro:
```
{% macro export_formatted_product_tags(output_path) %}
  {% set query %}
    SELECT ["a", "b", "c"] array_col
  {% endset %}

  {% set results = run_query(query) %}

  {% do results.to_json(output_path) %}
{% endmacro %}
```
then
`dbt run-operation export_formatted_product_tags --args '{output_path: "out.json"}'`
creates file out.json, containing
`[{"array_col": "[\"a\", \"b\", \"c\"]"}]`

### Environment

```markdown
- OS: Ubuntu LTS
- Python: 3.8.10
- dbt: 1.0.1
```

### What database are you using dbt with?

BigQuery

**Comment by brabster** [comment] 2022-03-04 14:49
Tried `dbt_utils.get_query_results_as_dict`, issue seems to be present there rather than an issue with Agate.

```
  {% set results = dbt_utils.get_query_results_as_dict(query) %}

  {{ log(results, info=True) }}
```
Output
`{'col': ('[1, 2, 3]',)}`

**Comment by ChenyuLInx** [comment] 2022-03-10 19:32
Hey @brabster , thanks for opening this and sorry for getting back slow! I was able to reproduce this locally after setting up the bigqurey adaptor. I will do some digging soon to see what is causing the misinterpretation.

**Comment by ChenyuLInx** [comment] 2022-03-11 02:26
I found that [this](https://github.com/dbt-labs/dbt-core/blob/43e3fc22c4eae4d3d901faba05e33c40f1f1dc5a/core/dbt/clients/agate_helper.py#L113) is the place we converted the list to a string, then `agate.table.to_json` would take the string value and make it look like `"[\"foo\", \"bar\", \"baz\"]"`.

@jtcohen6 Do you know what's the end result we want to achieve here? As it looks like this has been what we are doing for the past 3 years. [Commit](https://github.com/dbt-labs/dbt-core/commit/22d13ba881355b6228d8aefdc17cc2610f8e336f)

**Comment by jtcohen6** [comment] 2022-03-11 04:12
@ChenyuLInx Nice digging! I have to think our reasoning, back in 2019, was that strings are an easier mode of transport for these values, rather than trying to preserve their original JSON structure.

In terms of achieving the desired behavior for this case, dbt's base context includes a `fromjson` method ([docs](https://docs.getdbt.com/reference/dbt-jinja-functions/fromjson)), which is the equivalent of Pythonic `json.loads`:
```sql
{% macro export_formatted_product_tags(output_path) %}
  {% set query %}
    SELECT ["a", "b", "c"] array_col
  {% endset %}

  {% set results = run_query(query) %}

  {% for row in results %}
  
    {% do print(row) %}
    {% do print(row[0]) %}
    {% do print(fromjson(row[0])) %}
    
    {% for entry in fromjson(row[0]) %}
      {% do print(entry) %}
    {% endfor %}
  
  {% endfor %}

{% endmacro %}
```
Terminal output:
```
<agate.Row: ('["a", "b", "c"]')>
["a", "b", "c"]
['a', 'b', 'c']
a
b
c
```

Note that this code uses the `print` method, which is new in `main` / coming in v1.1.

What I've got above isn't a complete solution to the original request, but I trust it's possible to convert the JSON-y string back to a real JSON object (in this case, a real array), recreate an agate table, write it to a file (via the built-in `agate.Table` method... not something dbt is really meant to do!)

I'm going to close this one out, given a reasonable default, and workable next steps to achieve highly custom behavior.

**Closed by jtcohen6** 2022-03-11 04:12 UTC
Labels: bug, Team:Execution

**Comment by brabster** [comment] 2022-03-15 12:22
Thanks for the help. FWIW, my usecase is building data-driven products, rather than reports and dashboards.

I build networks of views using dbt. Those views contain data that I need to pull out of BigQuery and and push over to other services like Cloud Storage or Datastore.

Being able to query a view and pull the results out, using dbt's profiles and model-awareness, is much neater than flipping to Python code or the bq cli tool at that last step. I'm not sure if that's a major deviation from dbt's core goals but happy to take guidance/share more info if helpful.
