### ISSUE TITLE
[CT-3506] [Bug] dbt-core using psycopg2-binary==2.9.6 succeeds, but psycopg2-binary==2.9.9 does not.

### ISSUE THREAD

**Issue by ooobii** [dbt-labs/dbt-core#9303] opened 2023-12-18 19:58 UTC
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

I have installed dbt-core and dbt-postgres from scratch on a fresh MacOS machine (macOS 14.2 (23C64), Darwin 23.2.0) in a virtual python environment running Python 3.10.13.

When using the command `pip3 install dbt-postgres`, followed by a `dbt debug` to confirm connectivity, aconnection error is encountered with the message attached in the log section below.

To work around this, you can run `pip3 uninstall psycopg2-binary && pip3 install psycopg2-binary==2.9.6`. Without changing network settings or profile information, the connection suceeds!

### Expected/Previous Behavior

The connection using username & password based authentication should succeed without having to install the proper version of the `psycopg2-binary` package.

### Steps To Reproduce

  1. Create a new Python environment on MacOS (ARM64) using Python version 3.10 (also tested on 3.11, same result).
  2. Activate newly-created python environment.
  3. Run standard install command: `pip3 install dbt-postgres`.
  4. Navigate terminal to known-good dbt project.
  5. Execute command `dbt debug` to confirm connectivity to database in `~/.dbt/profile.yml`.
  6. Observe connection failure due to improper authentication strategy being attempted.
  7. Uninstall `psycopg2-binary` using `pip3`: `pip3 uninstall psycopg2-binary`.
  8. Install downgraded version of `psycopg2-binary==2.9.6`.
  9. Re-execute command `dbt debug` and observe proper authentication strategy being utilized.

### Relevant log output

```shell
  ~/Documents/Development/DBT/network_data_warehouse on   KNIME-12 ❯ dbt debug     dbt-new 3.10.13 at  02:38:13 PM
19:38:19  Running with dbt=1.7.4
19:38:19  dbt version: 1.7.4
19:38:19  python version: 3.10.13
19:38:19  python path: /Users/mwendel/.pyenv/versions/3.10.13/envs/dbt-new/bin/python3.10
19:38:19  os info: macOS-14.2-arm64-arm-64bit
19:38:19  Using profiles dir at /Users/mwendel/.dbt
19:38:19  Using profiles.yml file at /Users/mwendel/.dbt/profiles.yml
19:38:19  Using dbt_project.yml file at /Users/mwendel/Documents/Development/DBT/network_data_warehouse/dbt_project.yml
19:38:19  adapter type: postgres
19:38:19  adapter version: 1.7.4
19:38:19  Configuration:
19:38:19    profiles.yml file [OK found and valid]
19:38:19    dbt_project.yml file [OK found and valid]
19:38:19  Required dependencies:
19:38:19   - git [OK found]

19:38:19  Connection:

[.......]

19:38:19  Registered adapter: postgres=1.7.4
19:38:40    Connection test: [ERROR]

19:38:40  1 check failed:
19:38:40  dbt was unable to connect to the specified database.
The database returned the following error:

>Database Error
  connection to server at "<redacted>" (<redacted>), port <redacted> failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Server not found in Kerberos database
  connection to server at "<redacted>" (<redacted>), port <redacted> failed: timeout expired
```

### Environment

```markdown
- OS: macOS 14.2 (23C64), Darwin 23.2.0
- Python: 3.11.* or 3.10.*
- dbt (working version): unknown (package dependency issue)
- dbt (regression version): unknown (package dependency issue)
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

I'm not sure when this was introduced, but a possibly relevant line can be found in this file: [dbt-core/plugins/postgres/setup.py](https://github.com/dbt-labs/dbt-core/blob/c2bc2f009bbeeb46b3c69d082ab4d485597898af/plugins/postgres/setup.py#L66C14-L66C17).

Not sure if it means anything - sorry i'm not too familiar with Python projects or this codebase 😃

**Comment by dbeatty10** [comment] 2023-12-19 13:44
Thanks for reporting this @ooobii.

How are you installing Postgres? Is it installed on your local machine, or are you using a postgres instance that is hosted somwhere?

When I tried `dbt debug` with `psycopg2-binary==2.9.9` installed when using a local postgres instance via [these](https://github.com/dbt-labs/dbt-core/blob/c2bc2f009bbeeb46b3c69d082ab4d485597898af/CONTRIBUTING.md#initial-setup) instructions, the connection succeeds.

**Comment by ooobii** [comment] 2023-12-19 14:19
Hi @dbeatty10!! 

This Postgres instance is hosted in the cloud. I see that the `setup_db.sh` test is using the latest version of PostgreSQL. I wonder if that has something to do with it? The cloud DB i'm connecting to uses the following version:

```
PostgreSQL 12.17 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), 64-bit
```

Even though the server's version is rather out of date, it is still being supported. I wonder what is causing Kerberos authentication?

After my working hours are over, I can try to spin-up a docker container using the above version of PostgreSQL and the latest version - and see if that is the culprit.

**Comment by dbeatty10** [comment] 2023-12-19 15:06
> After my working hours are over, I can try to spin-up a docker container using the above version of PostgreSQL and the latest version - and see if that is the culprit.

Sounds good 👍

### Troubleshooting

One possibility is that there's some interaction between your cloud postgres instance and one of the more recent versions of  `psycopg`.

Here are the release notes for psycopg2:
https://www.psycopg.org/docs/news.html

This issue looks similar to the one you raised: https://github.com/psycopg/psycopg2/issues/1645.

The most helpful thing would be to identify the last working version (which sounds like `2.9.6`) and confirm the first version that doesn't work (which sounds like `2.9.7`).

Once those are known, then it's possible to look at what changed between those two versions:
https://github.com/psycopg/psycopg2/compare/2.9.6...2.9.7

### Summary

Ultimately, this doesn't look like an issue in dbt-core to me but rather the version of the postgres server and/or the version of the psycopg2 driver.

**Comment by jamesrusso** [comment] 2023-12-20 17:49
Will the connection eventually succeed (after like 3 minutes?) Do you have any expired tickets in your OSX "Ticket Viewer" application. I suspect its some issue with GSSAPI interactions on OSX and the underlying postgres module.

I just experienced it again because of an expired ticket in the ticket view from me connecting from OSX to a windows file share.

**Comment by dbeatty10** [comment] 2023-12-20 18:11
@jamesrusso Great ideas 💡

Do you know how to handle expired tickets through the "Ticket Viewer" application?

Is there a way to renew it? Or does it need to be deleted?

If you can provide any screenshots or other instructions for @ooobii, that would be awesome!

**Comment by jamesrusso** [comment] 2023-12-20 18:24
For me, the ticket seems to be created when I connect via Microsoft Remote Desktop connection to a windows machine on my Mac. 

This creates a ticket in the ticket view for that authentication which will eventually expire. When I have an expired ticket psycopg will hang for a few minutes when trying to authenticate a connection like it's trying to connect to some Kerberos Server somewhere and it cannot to try and authenticate. This occurs when connecting to a local postgres instance (either in docker or on the native machine)

I'm no expert on Kerberos and maybe this is completely the wrong direction, but I'd be curious if the original reporter has the same issue with an expired kerberos identity and if removing it helps?

The ticket viewer can be found via search or from the menu option on the Keychain Access

<img width="678" alt="Screenshot 2023-12-20 at 1 20 49 PM" src="https://github.com/dbt-labs/dbt-core/assets/682807/9543b6e7-4b68-4685-9854-8d409bc27002">


<img width="990" alt="Screenshot 2023-12-20 at 1 17 54 PM" src="https://github.com/dbt-labs/dbt-core/assets/682807/f53e8241-7ad4-4c95-874c-de66b3a8c501">

**Comment by ooobii** [comment] 2023-12-21 23:08
Thank you all for your input and suggestions!! 😃  A Happy Holidays to you!!

The MacBook i'm on is Active Directory joined, and does use Kerberos for authenticating as my user & with other Windows resources (e.g. DBeaver using Kerberos to have "Windows Authentication" methods work against MSSQL databases).

> Will the connection eventually succeed (after like 3 minutes?) 

The error message in the original issue post appears after approx. 40 seconds. It was repetitive, and continued to show me an error message after 30 minutes of dog walking & coffee sipping. I let my Kerberos ticket expire, and got the same error. After testing the expired ticket, I refreshed it with the `kinit` command in my terminal, and I get the same error. 😦 

The PostgreSQL server does not have kerberos authentication enabled. I am not enabling / configuring DBT to authenticate with the remote database using Kerberos. Even if I did have an expired ticket in my MacOS keychain, `dbt` (or, really `psycopg2`), it should not be using Kerberos for PostgreSQL authentication. ☹️

**Comment by jamesrusso** [comment] 2023-12-21 23:17
I suspect that the client libraries on OSX do have some GSSAPI linkage which is causing the issue?

**Comment by dbeatty10** [comment] 2023-12-22 00:04
@ooobii this is sounding like an issue with `psycopg2` rather than dbt-core.

Do you get that same error if you bypass `dbt` altogether and try running a simple script like this instead?

`test_postgres.py`

```python
import psycopg2

# Database connection parameters
db_params = {
    'dbname': 'your_dbname',  # replace with your database name
    'user': 'your_username',  # replace with your username
    'password': 'your_password',  # replace with your password
    'host': 'localhost',  # or your database host
    'port': 5432  # or your database port
}

# Connect to the database
conn = psycopg2.connect(**db_params)
print("Connected to the database.")

# Create a cursor object
cur = conn.cursor()

# Execute a query
cur.execute("select 1 as id")

# Fetch and print the result
result = cur.fetchone()
print(f"Query Result: {result}")

# Close the cursor and connection
cur.close()
conn.close()
```

Then run it:

```shell
python test_postgres.py
```

I get this output:
```
Query Result: (1,)
```

**Comment by jamesrusso** [comment] 2023-12-22 01:16
> @ooobii this is sounding like an issue with psycopg2 rather than dbt-core.

Agree, and I actually think it's more of an issue with the underlying C library which psycopg2 links with on OSX. 

What about using the native psql client on OSX do you get the same result?

**Comment by smarko82** [comment] 2024-01-24 13:36
I am experiencing a very similar issu, with MacOS 13.6.1 (22G313) and Python 3.11.7. I was running Postgres db in Docker container on local machine.

Failure was slightly different:
```
  connection to server at "localhost" (::1), port 5432 failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Configuration file does not specify default realm
  connection to server at "localhost" (::1), port 5432 failed: timeout expired
```

@dbeatty10 example is failing in the same way.

Changing to `psycopg2-binary==2.9.6` solve issue on example code as well as dbt.

**Comment by dbeatty10** [comment] 2024-01-24 14:39
@smarko82 could you try [this python script](https://github.com/dbt-labs/dbt-core/issues/9303#issuecomment-1867068351) with a version of psycopg2-binary that does **not** work with dbt?

I would expect that script to raise an error. If so, it would confirm that this is an issue with `psycopg2` (e.g. underlying C library which `psycopg2` links with on OSX) rather than dbt-core.

**Comment by smarko82** [comment] 2024-01-24 21:53
Hi @dbeatty10 , yes, I confirm that your example doesn't work with this exception:

  connection to server at "localhost" (::1), port 5432 failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Configuration file does not specify default realm
  connection to server at "localhost" (::1), port 5432 failed: timeout expired
  
  It works if I use `psycopg2-binary==2.9.6`.
  
  The problem is about `psycopg2`. Even dbt correctly works with `psycopg2-binary==2.9.6`.

**Comment by dbeatty10** [comment] 2024-01-25 01:25
Thanks for confirming that @smarko82 ! 🙏

Since this issue is occurring independently of dbt, I'm going to close this in favor of https://github.com/psycopg/psycopg2/issues/1645

There's two known approaches in the meantime:
1. (Recommended) Remove any expired tickets via the Ticket Viewer in macOS (as described [here](https://github.com/psycopg/psycopg2/issues/1645#issuecomment-1864943524))
2. (Not recommended) Downgrade to `psycopg2-binary==2.9.6`

**Closed by dbeatty10** 2024-01-25 01:25 UTC
Labels: bug, triage

**Comment by blessedmadukoma** [comment] 2024-02-21 22:42
Still faced this issue today, this was the only fix for me. Tried connecting my Postgres DB from Docker to dbt but it did not work until I used this version of psycopg2

**Comment by ARH2608** [comment] 2024-04-19 09:40
> Still faced this issue today, this was the only fix for me. Tried connecting my Postgres DB from Docker to dbt but it did not work until I used this version of psycopg2

I am also facing the same problem i followed the steps
1. pip uninstall psycopg2-binary
2. pip install psycopg2-binary==2.9.6

but still not working, could you please help me. Thanks in advance

**Comment by ARH2608** [comment] 2024-04-19 10:05
(dbt-env) amita0@DEESCN0227:/mnt/c/Users/amita0/ETL_Project/development/github/model_project$ dbt debug
09:05:19  Running with dbt=1.7.13
09:05:19  dbt version: 1.7.13
09:05:19  python version: 3.10.12
09:05:19  python path: /mnt/c/Users/amita0/ETL_Project/development/github/dbt-env/bin/python
09:05:19  os info: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
09:05:19  Using profiles dir at /home/amita0/.dbt
09:05:19  Using profiles.yml file at /home/amita0/.dbt/profiles.yml
09:05:19  Using dbt_project.yml file at /mnt/c/Users/amita0/ETL_Project/development/github/model_project/dbt_project.yml
09:05:19  adapter type: postgres
09:05:19  adapter version: 1.7.13
09:05:19  Configuration:
09:05:19    profiles.yml file [OK found and valid]
09:05:19    dbt_project.yml file [OK found and valid]
09:05:19  Required dependencies:
09:05:19   - git [OK found]

09:05:19  Connection:
09:05:19    host: 172.99.0.2
09:05:19    port: 5432
09:05:19    user: dbt_user
09:05:19    database: analytics
09:05:19    schema: dev_amit
09:05:19    connect_timeout: 10
09:05:19    role: None
09:05:19    search_path: None
09:05:19    keepalives_idle: 0
09:05:19    sslmode: None
09:05:19    sslcert: None
09:05:19    sslkey: None
09:05:19    sslrootcert: None
09:05:19    application_name: dbt
09:05:19    retries: 1
09:05:19  Registered adapter: postgres=1.7.13
09:05:39    Connection test: [ERROR]

09:05:39  1 check failed:
09:05:39  dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "172.99.0.2", port 5432 failed: timeout expired


Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile

**Comment by dbeatty10** [comment] 2024-05-21 15:47
@gahane31 and @ARH2608 -- there are no known issues with dbt-core in relation to this error message -- it is purely a Postgres / `psycopg2` error message.

Try running [this](https://github.com/dbt-labs/dbt-core/issues/9303#issuecomment-1867068351) python script. If that script doesn't work, then you need to troubleshoot your connection to your Postgres database.

Common troubleshooting steps including making sure that:
- you don't have any expired tickets
- your username/password combination is correct
- your database is reachable from a networking standpoint and accepting connections
- etc.
