### ISSUE TITLE
[CT-967] [Feature] Hide docs using dbt_project.yml

### ISSUE THREAD

**Issue by SunriseLong** [dbt-labs/dbt-core#5591] opened 2022-08-01 19:18 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Support to hide model documentation from `dbt_project.yml`. 

This is currently possible from `schema.yml` making hiding a directory of models a repetitive and brittle task. 
This issue https://github.com/dbt-labs/dbt-core/issues/1671 originally scoped out functionality for the config at the schema and project level. This project config feature has yet to be prioritized.

I'd like something like to disable generating documentation for any model in the `intermediate` directory 

```
models:
  indigo_dbt:
    intermediate:
      docs:
        show: false
```

### Describe alternatives you've considered

The [docs](https://docs.getdbt.com/reference/resource-properties/docs) field. It must be configured per model.

### Who will this benefit?

This will allows data teams to seperate internal/staging models from the business-ready models to get clean business documentation for mart tables without intermediate models

**Comment by jtcohen6** [comment] 2022-08-02 08:55
@SunriseLong Thanks for opening! I totally agree.

I'm going to close this as a duplicate of https://github.com/dbt-labs/dbt-core/issues/5333. There's even some in-progress work to make it possible in https://github.com/dbt-labs/dbt-core/pull/5397.

**Closed by jtcohen6** 2022-08-02 08:55 UTC
Labels: duplicate, enhancement
