### ISSUE TITLE
Date_spine not working for databricks

### ISSUE THREAD

**Issue by NehaAwasthi9616** [dbt-labs/dbt-core#9420] opened 2024-01-22 16:02 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi 
I was using dbt_utils for generating date_spine in my data model. However, it has been failing since yesterday.
I found out that the date_spine has been moved to dbt_core .
I have made the adequate changes to the model still it is not working for me.
The model looks like this :

```sql
with date_spine as (
  {{ dbt.date_spine(
      start_date="to_date('2020-01-01', 'yyyy-mm-dd')",
      datepart="day",
      end_date="to_date('2050-12-31', 'yyyy-mm-dd')"
     )
  }}
)

select * from date_spine
```

Error I am getting :
 
<img width="520" alt="Screenshot 2024-01-22 204909" src="https://github.com/dbt-labs/dbt-core/assets/136068155/2941bc47-af72-4d91-844b-121c5b45c824">

 Could you please help me with this ?

### Expected Behavior

It should produce a date table with daily dates starting from '2020-01-01' to '2050-12-30'

### Steps To Reproduce

I am running it for databricks.
Version of dbt and related plugins:
DBT_Core = 1.7.5
spark: 1.7.1
databricks: 1.7.3

### Environment

```markdown
- Python:3.10.11
- dbt:1.7.5
```

### Which database adapter are you using with dbt?

spark

### Additional Context

databricks:1.7.3

**Comment by dave-connors-3** [comment] 2024-01-22 16:10
@dbeatty10 we encountered this in `dbt_project_evaluator` today as well!

**Comment by dbeatty10** [comment] 2024-01-22 19:03
Could you share more detail @dave-connors-3 ?

e.g., did you need to install everything within a fresh virtual environment to trigger the issue? Did you need to install dbt_utils to trigger it?

The following worked for me when I tried it a few minutes ago with a pre-existing installation of dbt-databricks=1.7.3 and _without_ any `dbt deps` dependencies (like dbt_utils):

`models/my_model.sql`

```sql
with date_spine as (

  {{ dbt.date_spine(
      start_date="to_date('2020-01-01', 'yyyy-mm-dd')",
      datepart="day",
      end_date="to_date('2050-12-31', 'yyyy-mm-dd')"
     )
  }}
)

select * from date_spine
```

```shell
python -m pip install dbt-core==1.7.5 dbt-postgres==1.7.5
dbt run
```

Output:

```
(dbt_1.7) $ dbt run      
18:54:55  Running with dbt=1.7.5
18:54:56  Registered adapter: databricks=1.7.3
18:54:57  Found 1 model, 1 analysis, 0 sources, 0 exposures, 0 metrics, 534 macros, 0 groups, 0 semantic models
18:54:57  
18:55:00  Concurrency: 10 threads (target='databricks')
18:55:00  
18:55:00  1 of 1 START sql view model dbt_dbeatty.my_model ............................... [RUN]
18:55:02  1 of 1 OK created sql view model dbt_dbeatty.my_model .......................... [OK in 1.78s]
18:55:02  
18:55:02  Finished running 1 view model in 0 hours 0 minutes and 5.53 seconds (5.53s).
18:55:02  
18:55:02  Completed successfully
18:55:02  
18:55:02  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

**Comment by b-per** [comment] 2024-01-23 08:39
I was able to replicate it

**tldr**: there is some incompatibility with some versions of `pandas`

### What worked

I installed the latest `dbt-core` and `dbt-databricks` in an **existing** virtual env. 

```
dbt-core                   1.7.5
dbt-databricks             1.7.3
```

Running a `dbt run -t dx -s metricflow_time_spine` worked fine.

### What didn't work

I installed the latest `dbt-databricks` in a **new** virtual env. 

```
dbt-core                   1.7.5
dbt-databricks             1.7.3
```

Running a `dbt run -t dx -s metricflow_time_spine` on the exact same project and model failed with the error:

```
08:32:37    Compilation Error in model metricflow_time_spine (models/utils/metricflow_time_spine.sql)
  int() argument must be a string, a bytes-like object or a number, not 'NoneType'
  
  > in macro default__get_intervals_between (macros/sql/date_spine.sql)
  > called by macro get_intervals_between (macros/sql/date_spine.sql)
  > called by macro default__date_spine (macros/sql/date_spine.sql)
  > called by macro date_spine (macros/sql/date_spine.sql)
  > called by model metricflow_time_spine (models/utils/metricflow_time_spine.sql)
```

### What is the fix

I then spent the time checking what differences I have in my different pip packages and downgraded the version of every package in my new venv to the version of my old venv.

After downgrading `pandas` from `2.2.0` to `1.4.2` in my new venv I can now do a successful `dbt run -t dx -s metricflow_time_spine` in my new venv as well

**Comment by b-per** [comment] 2024-01-23 08:43
This is now also [reported on the dbt-databricks ](https://github.com/databricks/dbt-databricks/pull/564)side as well and as a result they are pinning pandas to <2.2

**Comment by dbeatty10** [comment] 2024-01-23 14:09
Thanks for reproducing this issue @b-per ! 🏆 

I'm going to close this in favor of https://github.com/databricks/dbt-databricks/pull/564 since this is not a problem in dbt-core.

i.e. pandas is not a requirement of dbt-core and it is only a requirement of dbt-databricks (which was getting its required range for `pandas` [here](https://github.com/databricks/databricks-sql-python/blob/3f6834c9797503132cb0d1b9b770acc36cd22d42/pyproject.toml#L14-L16) prior to https://github.com/databricks/dbt-databricks/pull/564).

### Workaround

In the meantime, users can manually workaround the issue by installing a non-breaking version of pandas like the following:

```shell
python -m pip install "pandas<2.2.0"
```

### Reprex

Assuming a dbt project like [this](https://github.com/dbt-labs/dbt-core/issues/9420#issuecomment-1904625045), the error can be reproduced with these commands:

```shell
python -m pip install pandas==2.2.0
dbt run
```

**Closed by dbeatty10** 2024-01-23 14:09 UTC
Labels: bug, triage
