### ISSUE TITLE
[CT-1895] [Bug] Include model database in log representation or make it configurable

### ISSUE THREAD

**Issue by madhavdube** [dbt-labs/dbt-core#6712] opened 2023-01-24 18:42 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This database name is excluded by default from log representation [here](https://github.com/dbt-labs/dbt-core/blob/7b464b8a4957ec7969f19234020e110be1987923/core/dbt/task/run.py#L167-L170)

```
        # exclude the database from output if it's the default
        if self.node.database == self.config.credentials.database:
            relation = relation.include(database=False)
        return str(relation)
```
It makes it difficult if we are using logs for downstream monitoring processing and model names are not consistent. If including a database name is not ideal at the very least we should make it configurable

### Expected Behavior

It should be configurable so we have consistent model names in the logs like <generated_database_name>.<generated_schema_name>.<generated_alias_name> 

This will help if we are using logs for downstream monitoring and JSON log format is just too verbose for it. 

### Steps To Reproduce

Add target database in credentials and run any model that will get materialized in the same database. 

### Environment

```markdown
- OS:
- Python: Python 3.8.8
- dbt:1.3.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment] 2023-01-24 20:38
Thanks for reaching out @madhavdube ! And thanks for linking to the relevant portion of code you traced this back to 🤩 

Could you share a little more about how you are using the logs for downstream monitoring? (It sounds like you aren't using the JSON log format.) If you are able to provide a simplified and/or anonymized example of the part of the logs you are referring to, that would be help facilitate the discussion.

### My assumption, subject to a fact-check
I haven't confirmed this yet, but my belief is that the database is excluded from the output to make the output on the terminal shorter, like this:
```
$ dbt run -s my_model               
Running with dbt=1.3.1
Found 3 models, 0 tests, 0 snapshots, 0 analyses, 327 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics

Concurrency: 5 threads (target='postgres')

1 of 1 START sql incremental model dbt_dbeatty.my_model ....... [RUN]
1 of 1 OK created sql incremental model dbt_dbeatty.my_model .. [INSERT 0 4 in 2.94s]

Finished running 1 incremental model in 0 hours 0 minutes and 9.11 seconds (9.11s).
 
Completed successfully
 
Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

Instead of longer like:
```
1 of 1 START sql incremental model my_database_name.dbt_dbeatty.my_model ....... [RUN]
1 of 1 OK created sql incremental model my_database_name.dbt_dbeatty.my_model .. [INSERT 0 4 in 2.94s]
```

This may have even been discussed in an issue before, but I'd have to go searching to find if that is the case or not.

**Comment by jtcohen6** [comment] 2023-01-24 20:44
> Could you share a little more about how you are using the logs for downstream monitoring? (It sounds like you aren't using the JSON log format.)

Agree that structured (JSON-formatted) logs are the way to go here, for any programmatic (machine) consumer! The `database` + full `relation_name` are definitely present in the full log structure.

Docs: https://docs.getdbt.com/reference/events-logging

**Comment by madhavdube** [comment] 2023-01-24 21:19
That seems like a workaround solution. I think it will be cleaner to just have one line of code removed or make it configurable and that will be easier for our downstream application to costume.
JSON log format consists of many fields which we might not need at all and also, we are using Airflow to trigger a task so logging will become more inconsistent from message log format vs message + JSON (dbt) . So, I still think fixing the above or making it configurable will help us here.

**Comment by madhavdube** [comment] 2023-01-24 21:29
> 

Sure @dbeatty10 . We are monitoring logs for successful model execution and triggering another process downstream related to the dashboard data source update( so not related to DBT).
 So A simple log format is just enough for our use case
 ```
 OK created view model test_db.public.foo_table
 ```
 When we see a fully qualified model here which can be used in downstream applications but we cannot use it if the database name is missing and the reason is [here](https://github.com/dbt-labs/dbt-core/blob/7b464b8a4957ec7969f19234020e110be1987923/core/dbt/task/run.py#L167-L170)

**Comment by dbeatty10** [comment] 2023-01-25 15:02
Thanks for that info @madhavdube.

At this time, we aren't keen to adjust the human-readable logs because:
- Not including the database for human-readable output was an intentional choice and is long-standing
- Making it configurable would introduce additional code and documentation overhead for us to maintain
- Machine-friendly JSON logs are the path we're encouraging for automated downstream consumption

Of course the wrinkle is that the JSON logs don't have this info in dbt-core 1.4 either! 😅 

I'm going to close this issue in favor of https://github.com/dbt-labs/dbt-core/issues/6724 which I've opened  to include the `relation_name` idea from @jtcohen6. I completely understand it isn't the precise thing you are asking for, but it represents the way we believe is most sustainable for us to support the use-case you are describing.

**Closed by dbeatty10** 2023-01-25 15:02 UTC
Labels: enhancement, triage
