### ISSUE TITLE
[CT-1320] [Feature] dbt should (maybe?) run tests against its tmp table before committing

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#6035] opened 2022-10-10 03:37 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This came out of [this forum post](https://discourse.getdbt.com/t/why-doesnt-dbt-run-its-tests-against-the-tmp-table-before-committing/5027), where someone wondered why we don't test the tmp table before committing. In a `dbt build` context, that makes a reasonable amount of sense. 

### Describe alternatives you've considered

Honestly I'm not sold on this, as it would only work on table-y models - views don't get a tmp state do they? But it's a reasonable question so I figured I'd raise it. 

### Who will this benefit?

It would be tidier than the admin of a [blue-green deploy](https://discourse.getdbt.com/t/performing-a-blue-green-deploy-of-your-dbt-project-on-snowflake/1349). (Which implies that the right answer here is probably dbt Core and/or dbt Cloud makes it easier to do cross-db blue-green deploys.)

**Comment by dbeatty10** [comment] 2022-10-10 22:33
Thanks for opening @joellabes !

Closing as a duplicate of https://github.com/dbt-labs/dbt-core/issues/5660 which was moved to this discussion: https://github.com/dbt-labs/dbt-core/discussions/5687

Please let me know if this is unique or different than https://github.com/dbt-labs/dbt-core/discussions/5687 -- I can give this a deeper second look.

**Closed** 2022-10-10 22:34 UTC
Labels: enhancement, triage
