### ISSUE TITLE
[CT-2939] [Bug] Inconsistent capitalization in status messages

### ISSUE THREAD

**Issue by AaronCoquet-Easypark** [dbt-labs/dbt-core#8320] opened 2023-08-04 11:33 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When performing a `dbt build` (or other command that modifies the data warehouse), some results messages are in ALL CAPS and some are lowercase. Examples:
`X of Y START sql view model <name>  [RUN]` <-- Caps for "RUN"
`X of Y OK created sql view model <name> [SUCCESS 1 in 7.09s]` <-- Caps for view model "SUCCESS"
`X of Y START sql table model <name>  [RUN]` <-- Caps for "RUN"
`X of Y OK created sql table model <name>  [SUCCESS 1 in 7.17s]` <-- Caps for table model "SUCCESS"
`X of Y START sql incremental model <name>  [RUN]` <-- Caps for "RUN"
`X of Y OK created sql incremental model <name> . [SUCCESS 0 in 12.12s]` <-- Caps for incremental model "SUCCESS"
`X of Y START snapshot <name> ........ [RUN]` <-- Caps for "RUN"
`X of Y OK snapshotted <name>  [success in 5.33s]` <-- Lowercase for snapshot "success"

### Expected Behavior

All of the status messages should be in the same case, ideally UPPER.

### Steps To Reproduce

In Any dbt environment, run each of the following types of queries on the data warehouse:  
- view
- table
- snapshot
- incremental (with and without `--full-refresh`)
- seed
- test
- analysis
and observe whether the results are show in CAPS or not.
Situations to check:
1. START: is it `[RUN]` or `[run]`?
2. OK: is it `[SUCCESS]` or `[success]`?
3. FAIL: is it `[FAIL]` or `[fail]`?
4. ERROR: is it `[ERROR]` or `[error]`?
5. SKIP: is it `[SKIPPING]` or `[skipping]`?
6. CANCEL: is it `[CANCEL]` or `[cancel]`?

### Environment

```markdown
- OS: Windows10+WSL2+Ubuntu22.04, EKS+Debian (official image for 1.5.1)
- Python: 3.8, 3.10
- dbt: 1.5.1, 1.5.2, 1.5.3
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

This is probably the case in all versions that have snapshotting, in all supported pythons, on all supported OSs

**Comment by dbeatty10** [comment] 2023-08-04 13:55
Thanks for reporting this @AaronCoquet-Easypark 🙏

For clarity, is this creating any functional errors for you? Or is it only a visual difference? If the latter, I will switch this from a bug to a feature request.

**Comment by dbeatty10** [comment] 2023-08-04 14:51
Here's some relevant areas of the code that either apply uppercase or leave as-is (presumably lowercase):

<details>
<summary>Source code snippets</summary>

### Mixed uppercase for error and lowercase for success

https://github.com/dbt-labs/dbt-core/blob/f63709260ef5b561ebf13759adde019d2a23399e/core/dbt/events/types.py#L1612-L1617

https://github.com/dbt-labs/dbt-core/blob/f63709260ef5b561ebf13759adde019d2a23399e/core/dbt/events/types.py#L1587-L1592

### Uniform uppercase regardless of status

https://github.com/dbt-labs/dbt-core/blob/f63709260ef5b561ebf13759adde019d2a23399e/core/dbt/events/types.py#L1533-L1544

### Potential place to standardize casing

https://github.com/dbt-labs/dbt-core/blob/f63709260ef5b561ebf13759adde019d2a23399e/core/dbt/events/format.py#L7-L35

</details>

**Comment by AaronCoquet-Easypark** [comment] 2023-08-11 07:05
Hi @dbeatty10 ! Thanks for the quick response (and sorry my my slow response)!
It's not causing issues, no. It's just a visual difference.

Thanks for providing the source code references! 

Because this would be a purely visual change (thus, not functional), would a PR need to include `changie` changes and/or new tests, or could it be a "ninja change" that only affects the target file?

**Comment by jtcohen6** [comment] 2023-08-11 07:21
I think this may be a duplicate of:
- https://github.com/dbt-labs/dbt-core/issues/7583

**Comment by jtcohen6** [comment] 2023-08-15 12:52
I'm indeed going to close this as a duplicate of #7583

**Closed by jtcohen6** 2023-08-15 12:52 UTC
Labels: bug, triage
