### ISSUE TITLE
add warning for disabled models

### ISSUE THREAD

**Issue by macklin-fluehr** [dbt-labs/dbt-core#10024] opened 2024-04-24 16:00 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

if you try to directly test a disabled model, you are presented with a generic error: Nothing to do. Try checking your model configs and model specification args.'

I think it's a good feature to ignore disabled models completely when selecting multiple nodes in the dag. However, if I directly select a model, let's say for a `dbt test -s my_model`, I should not receive the generic error, but should receive a warning that this model is specifically disabled. 

### Describe alternatives you've considered

this is a 0-1 feature to me. the only workaround is pure brute-force trying to figure out if disabling the model is the reason nothing is happening

### Who will this benefit?

anyone debugging code that is for some reason, has 'nothing to do'.

**Comment by dbeatty10** [comment] 2024-04-24 17:58
Thanks for opening this issue @macklin-fluehr 💡 

Good news: great minds think alike and we recently merged https://github.com/dbt-labs/dbt-core/pull/9863 with an update to this warning message.

I'm closing this is a duplicate of https://github.com/dbt-labs/dbt-core/issues/9747, but please let us know if you think the new error message won't work for some reason.

**Closed by dbeatty10** 2024-04-24 17:58 UTC
Labels: enhancement, triage

**Comment by macklin-fluehr** [comment] 2024-04-24 18:10
oh, awesome. I did not see this ticket merged, but thanks for pointing it
out! I think the hint of 'enabled' is enough to point someone in the
right direction. Thanks!
