### ISSUE TITLE
[CT-1092] [Feature] Add support of Jinja2>=3

### ISSUE THREAD

**Issue by KulykDmytro** [dbt-labs/dbt-core#5723] opened 2022-08-27 13:41 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Support of `Jinja2` v3
Current dependency for Jinja2:2.11.3 restricts installs of Airflow:2.3.x due to version conflict (Jinja2>=3.0 expected)

### Who will this benefit?

Will provide compatibility with Airflow:2.3.x
v2 and v3 are very similar and expected that migration will be smooth

**Comment by jtcohen6** [comment] 2022-08-29 09:44
@KulykDmytro We're doing this in dbt Core v1.3!

https://github.com/dbt-labs/dbt-core/blob/49e7bdbef957c76312affb7375c3983e4a749b65/core/setup.py#L51

Closing as a duplicate of #4748

**Closed by jtcohen6** 2022-08-29 09:44 UTC
Labels: duplicate, enhancement, dependencies
