### ISSUE TITLE
[CT-1138] [Feature] Multiple VARS: blocks in the project yaml - last one overwrites first

### ISSUE THREAD

**Issue by tom-packert** [dbt-labs/dbt-core#5787] opened 2022-09-08 12:09 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I added a VARS section to an existing project.yml file.  I was adding it to the top of the file as the documentation instructed.   I kept getting errors when I would compile a DBT model that referenced the VARS.  It turned out there was a second VARS block at the bottom of the project yaml file and this one was overwriting the first VARS block where I had added my new variables.  It took about 15 minutes to figure out what was going on, but a warning about a second VARS block might save people time.

### Describe alternatives you've considered

Manually look for VARS blocks, dont assume they will be at the top.

### Who will this benefit?

Any new DBT developer

**Comment by dbeatty10** [comment] 2022-09-09 11:02
Thanks for sharing your experience @tom-packert!

Agreed that a clear warning (or error) would be helpful in this scenario. Something like "Duplicate key `vars` within dbt_project.yml".

I'm going to label this as "help_wanted" in case anyone wants to take a shot at implementing this.

### Explanation
Although the [YAML spec says that keys "must be unique"](https://yaml.org/spec/1.2.2/#321-representation-graph), many parsers [allow duplicates](https://hitchdev.com/strictyaml/why/duplicate-keys-disallowed/) including pyyaml, which is what [dbt uses](https://github.com/dbt-labs/dbt-core/blob/10b2a7e7ff906a8317c63d4a86630660729d37f8/core/setup.py#L71) currently. pyyaml has tickets open for this behavior ([here](https://github.com/yaml/pyyaml/issues/41) and [here](https://github.com/yaml/pyyaml/issues/165)). Since pyyaml allows the duplicates without warning or error, dbt inherits that behavior as-is and merrily rolls along.

### Hints for implementation
There are examples of how to enforce uniqueness with the current version of pyyaml like [this](https://stackoverflow.com/questions/33490870/parsing-yaml-in-python-detect-duplicated-keys/63215043#63215043) or [this](https://gist.github.com/pypt/94d747fe5180851196eb).

**Comment by jtcohen6** [comment] 2022-09-09 12:21
I think this issue may in fact be a duplicate of https://github.com/dbt-labs/dbt-core/issues/5114. We tried resolving it a few months ago, ran into some undesirable behaviors, and ended up reverting it rather than leave users with _more_-surprising errors.

I'm going to close it as such, to keep the conversation centralized over there.

**Closed by jtcohen6** 2022-09-09 12:21 UTC
Labels: duplicate, enhancement
