### ISSUE TITLE
[CT-3512] [Bug] Presence of `+` in `column_type` config for seeds drops leading zeroes

### ISSUE THREAD

**Issue by sophiad96** [dbt-labs/dbt-core#9314] opened 2023-12-22 15:16 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When configuring a column_type for a seed file, including the + symbol (like +column_type) causes the leading zeroes to be dropped from the values in that column (if present).

### Expected Behavior

I would expect the leading zeroes to be preserved regardless of whether or not a + is included in front of the column_types config.

### Steps To Reproduce

1. Create a seed file that contains a column with leading zeroes.

<img width="274" alt="1" src="https://github.com/dbt-labs/dbt-core/assets/68790165/376f8b0f-50ac-4bbb-a55b-3304a5929112">

2. Add properties.yml file for the seed file, and make sure to include a + in front of column_type. Set the column type to string.

<img width="274" alt="2" src="https://github.com/dbt-labs/dbt-core/assets/68790165/086fa9fc-96c8-4268-b91d-b098484d92e8">

4. Run dbt seed --full-refresh and query the seed file. 

<img width="670" alt="4" src="https://github.com/dbt-labs/dbt-core/assets/68790165/60bfec47-458b-46f1-8182-f21b42ab2492">

6. Remove the + sign and run dbt seed --full-refresh again.

<img width="670" alt="5" src="https://github.com/dbt-labs/dbt-core/assets/68790165/286cd599-3ce3-4dda-b264-013603c0bb43">

### Environment

```markdown
- OS:
- Python:
- dbt: 1.6
```

**Comment by dbeatty10** [comment] 2023-12-22 18:08
Thanks for reaching out about this @sophiad96 !

This is actually expected behavior, so I'm going to close this in favor of adding some detail to our documentation in some key locations: https://github.com/dbt-labs/docs.getdbt.com/issues/4693

Admittedly, this can be a little bit unintuitive, so I'll try to explain below.

### 💡 Key insight

The key thing to keep in mind is that the leading `+` is _only_ for setting configs within `dbt_project.yml`.

`dbt_project.yml` can have a hierarchy of folder names. It can also have configurations. In order to tell the difference between the two, we add a `+` to the front of the latter.

### `column_types` for seeds

Indeed, within `properties.yml`, adding the `+` will cause `column_types` to be unrecognized and ignored.

And that's why the example `properties.yml` file [here](https://docs.getdbt.com/reference/resource-configs/column_types#usage) doesn't include the `+`:

```yaml
version: 2

seeds:
  - name: country_codes
    config:
      column_types:
        country_code: varchar(2)
        country_name: varchar(32))
```

### Example

This is because the leading `+` is _only_ for use in `dbt_project.yml` [because](https://docs.getdbt.com/best-practices/materializations/5-best-practices#project-level-configuration):

> We demarcate between a folder name and a configuration by using a `+`, so `marketing`, `paid_ads`, and `google` below are **folder** names, whereas `+materialized` is a **configuration** being applied to those folder and all folders nested below them.
> ...
> ```yaml
> models:
>   jaffle_shop:
>     marketing:
>       +materialized: view
>       paid_ads:
>         google:
>           +materialized: table
> ```

To accomplish the same thing as above in a `properties.yml` file for a specific model, the folder structure is dropped and so is the `+`:

```yaml
version: 2

models:
  - name: some_specific_model_name
    config:
      materialized: table
```

**Closed by dbeatty10** 2023-12-22 18:08 UTC
Labels: bug, triage
