### ISSUE TITLE
[Bug] Exposures can't reference private model

### ISSUE THREAD

**Issue by dat-a-ish** [dbt-labs/dbt-core#10132] opened 2024-05-12 11:53 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Exposure cannot reference a private model although it could in the 1.6 version. 
Exposure definition:
```yml
- name: "test_dashboard"
  label: "Test Dashboard"
  type: dashboard
  maturity: medium

  depends_on:
    - ref('private_model')

  owner:
    name: Egor Tarasenko
```

`dbt ls` returns the following output: 
```
Parsing Error
  Node exposure.psdw_rs.test_dashboard attempted to reference node model.psdw_rs.private_model, which is not allowed because the referenced node is private to the 'private_group' group.
```

### Expected Behavior

Referencing a private model in exposure doesn't rise an error 

### Steps To Reproduce

1. install dbt-core, dbt-redshift >= 1.7
2. Create a private model
3. Reference it from Exposure:
```yml
- name: "test_dashboard"
  label: "Test Dashboard"
  type: dashboard
  maturity: medium

  depends_on:
    - ref('private_model')

  owner:
    name: Egor Tarasenko
```
4. Run: `dbt ls`

### Relevant log output

```shell
Parsing Error
  Node exposure.psdw_rs.test_dashboard attempted to reference node model.psdw_rs.private_model, which is not allowed because the referenced node is private to the 'private_group' group.
```

### Environment

```markdown
- Python: 3.10
- dbt: dbt-core==1.7 dbt-redshift==1.7
```

### Which database adapter are you using with dbt?

redshift

**Comment by jtcohen6** [comment] 2024-05-13 12:21
@dat-a-ish Thanks for opening - I'm going to close this as a duplicate of:
- https://github.com/dbt-labs/dbt-core/issues/9339

While it doesn't feel like a _recommended_ practice to reference a `private` model within an `exposure` — that model is definitionally not meant to be an interface for external consumption — it should still be _possible_. Similar to referencing a `source` within an `exposure`: [not encouraged, but possible](https://docs.getdbt.com/docs/build/exposures#:~:text=(While%20possible%2C%20it%20is%20highly%20unlikely%20you%20will%20ever%20need%20an%20exposure%20to%20depend%20on%20a%20source%20directly)).

**Closed** 2024-05-13 12:21 UTC
Labels: bug, duplicate
