### ISSUE TITLE
[CT-2159] [Regression] `sources.json` does not generate upon running `dbt source freshness`

### ISSUE THREAD

**Issue by elongl** [dbt-labs/dbt-core#7026] opened 2023-02-22 16:21 UTC
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Running `dbt source freshness` sometimes does not write `target/sources.json`.
I'm still not too sure what's causing this, but I think with very high probability that it's related to dbt 1.5.0.
Our [CI tests](https://github.com/elementary-data/elementary/actions/workflows/test-all-warehouses.yml) were passing until dbt-1.5.0b1 was released in which case running `dbt source freshness` stopped generating the `sources.json` file.

I was wondering if you have any idea what might be causing it and if you made certain changes in that area of the code.

Here's an example of [a run using dbt-1.4.2rc1](https://github.com/elementary-data/elementary/actions/runs/4205432794/jobs/7297518721) in which it works, and [the one after which is 1.5.0b1](https://github.com/elementary-data/elementary/actions/runs/4208586844/jobs/7304761705) where it stops working.

### Expected/Previous Behavior

I expect running `dbt source freshness` to always generate a `sources.json` file in the `target` directory.

### Steps To Reproduce

`dbt source freshness`

### Environment

```markdown
- OS: Linux
- Python: 3.7.5
- dbt (working version): 1.4.2
- dbt (regression version): 1.5.0
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

As I previously said, I'm not entirely sure under what conditions it generates and under which it doesn't.
It does seem to work on the other runs and I was wondering if you have an idea of what might be causing it.

**Comment by jtcohen6** [comment] 2023-02-22 16:50
@elongl I haven't dug in deep here, I just tried reproducing locally and I wasn't able to. Even when I have zero `sources` defined, I still see `sources.json` showing up:
```
$ dbt source freshness
16:47:24  Running with dbt=1.5.0-b1
...
16:47:25  Nothing to do. Try checking your model configs and model specification args
16:47:25  Done.

$ ls -1 target/
graph.gpickle
manifest.json
partial_parse.msgpack
sources.json

$ cat target/sources.json | jq
{
  "metadata": {
    "dbt_schema_version": "https://schemas.getdbt.com/dbt/sources/v3.json",
    "dbt_version": "1.5.0b1",
    "generated_at": "2023-02-22T16:47:25.339139Z",
    "invocation_id": "6c902312-ead2-4a7b-a8a1-8e61a5665081",
    "env": {}
  },
  "results": [],
  "elapsed_time": 0
}
```

**Comment by jtcohen6** [comment] 2023-04-11 19:09
I'm going to close this one for now, as we weren't able to get enough clues to point to a root cause or clear reproduction case.

**Closed by jtcohen6** 2023-04-11 19:09 UTC
Labels: bug, regression, Team:Execution, awaiting_response

**Comment by mike-bolshakov** [comment] 2023-05-09 07:59
@jtcohen6 i observe the same - `sources.json` artifact is not being generated after running `dbt source freshness`. Using dbt 1.3.0 installed in venv, Python 3.9.16
![image](https://user-images.githubusercontent.com/112561315/237031958-76a5bab5-9816-40bd-8032-b90838202636.png). Tried deleting `target` dir and running `dbt source freshness` - a single file `partial_parse.msgpack` was created.
