### ISSUE TITLE
[CT-682] [Feature] Overriding temp table name 

### ISSUE THREAD

**Issue by yoavo-datricks** [dbt-labs/dbt-core#5291] opened 2022-05-23 07:42 UTC
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

We are executing DBT models via RPC with an external orchestrator.
We need to execute the same model multiple times in a parallel - each would create a different table with an alias.
However, since the temp tables name is determined via the model's name and not the alias the different executions crash.
Is it possible to add a way to manipulate the temp table's name at the model scope or make it based on the alias by the default?

### Describe alternatives you've considered

I can execute the models sequentially but that would take much more time.

### Who will this benefit?

Everyone who is interested in executing the same model multiple times in parallel and assuring different names via aliases.

**Comment by jtcohen6** [comment] 2022-05-31 12:15
Hey @yoavo-datricks, thanks for opening!

> We need to execute the same model multiple times in a parallel - each would create a different table with an alias.

Could you tell me more about your use case here? I have some guesses, but it would be worth understanding further, since we generally say that running the same dbt model concurrently is an anti-pattern.

That being said, we did just do a bunch of work around cleaning up and consolidating the logic for temp relations within materializations (https://github.com/dbt-labs/dbt-core/pull/4921, https://github.com/dbt-labs/dbt-core/pull/5221). I have a hunch that this might be resolved by that work: we're now using a suffixed version of `{{ this.identifier }}` for the temp table, which should account for the model `alias`, rather than the model `name`.

Any chance you could try installing `dbt-core` from the `main` branch, to see if the issue is resolved?

**Comment by yoavo-datricks** [comment] 2022-06-02 05:37
Hi @jtcohen6. After having multi models almost identical to each other, we were able to create a more generic model based on parameters and aliases. However, we use airflow to execute the models and are interested in having them created concurrently, mostly because of time consideration.

**Comment by jtcohen6** [comment] 2022-11-15 14:34
@meisam-napster As stated above, running the same dbt model multiple times concurrently is an anti-pattern and officially unsupported. That said, based on the refactoring work we did in v1.2, it should be simple enough to reimplement the [`make_intermediate_relation` and `make_temp_relation`](https://github.com/dbt-labs/dbt-core/blob/aeee1c23a6826aa1d254a939655cb514f38db649/core/dbt/include/global_project/macros/adapters/relation.sql#L1-L19) macros in your own project, and use (e.g.) the current timestamp to create disambiguated identifiers.

**Closed** 2022-11-15 14:34 UTC
Labels: enhancement, wontfix, Team:Adapters

**Comment by meisam-napster** [comment] 2022-11-15 14:53
@jtcohen6 - So I'd like to give a bit more clarity on the use case here / reasons for wanting this, then we can call it off as anti-pattern or maybe you have another approach...

By default and what's been recommended by DBT is that an incremental model on its first run, will do a full-refresh and on subsequent runs it will run daily, one execution at a time per day. Which is great and makes sense if you're dealing with a small amount of data.

However, problems arise when you're dealing with a lot more data to transform in BQ and the full-refresh which will run on the entire underlying table's data will exhaust resources / take too long and not complete.

Then instead of the first run being the full-refresh "full historical" one, we need to run day by day to backfill all the historical data. So far we've managed to achieve this, by doing something like this in our model:

```
    {% if is_incremental() %} -- applies on incremental runs
      AND ingestion_date = '{{ dbt_airflow_macros.ds() }}'
    {% else %} -- added this condition so that the first time an incremental model is run or a full-refresh is invoked, it doesn't attempt to run on ALL historical data, instead on the execution date it will create the table
      AND ingestion_date = '{{ dbt_airflow_macros.ds() }}'
    {% endif %}
```

Now this works fine, but we cannot as stated by others above and myself run multiple concurrent runs of these, even though each run would be a new execution date, which produces different idempotent data. To call this "anti-pattern" is confusing.

We don't want to do anything "anti-pattern" we want to do what's recommended here, but if this is being deemed as "anti-pattern" what is the actual solution to this scenario?
