### ISSUE TITLE
[Bug] Unique test errors when testing an expression on BigQuery

### ISSUE THREAD

**Issue by tracy-u** [dbt-labs/dbt-core#4264] opened 2021-11-10 15:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to run a unique test using an expression concatenating two columns in BigQuery [as described here](https://docs.getdbt.com/faqs/uniqueness-two-columns#2-test-an-expression), I get an unexpected error.  

```
Database Error in test {name}
  SELECT list expression references column {first_column_name} which is neither grouped nor aggregated at [12:6]
 ```
I get the same error when running the compiled SQL directly in BigQuery, and I am able to get the query to run as expected three ways: 
1. Using a `group by 1` statement
2. Removing the `unique_field` alias, OR
3. grouping by the `unique_field` alias (instead of the expression)

### Expected Behavior

The test should run (and pass in this case.)

### Steps To Reproduce

1. Create a unique test using an expression with two columns in BigQuery [as described here](https://docs.getdbt.com/faqs/uniqueness-two-columns#2-test-an-expression), and run.

**Test Snippet**
```
version: 2

models:
    - name: customer_ltv_by_week
      tests:
        - unique:
            column_name: "(customer_id || '-' || week)" 
```
**Compiled SQL:** 

```
select
    (customer_id || '-' || week) as unique_field,
    count(*) as n_records

from `aec-2021-10-thursdays`.`dbt_tracyu`.`customer_ltv_by_week`
where (customer_id || '-' || week) is not null
group by (customer_id || '-' || week)
having count(*) > 1
```

**Error:** 
```
Completed with 1 error and 0 warnings:

Database Error in test unique_customer_ltv_by_week__customer_id_week_ (models/marts/schema.yml)
  SELECT list expression references column customer_id which is neither grouped nor aggregated at [12:6]
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt: 0.21.0
```

### What database are you using dbt with?

bigquery

**Comment by jtcohen6** [comment] 2021-11-12 14:34
@tracy-u Thank you for the detailed report! You're spot on with your assessment. In fact, we raised the same issue in https://github.com/dbt-labs/dbt-bigquery/issues/35, and we've already merged a fix via https://github.com/dbt-labs/dbt-bigquery/pull/10.

The issue is, unlike the majority of other databases, BigQuery does not support grouping by a column expression if that column expression is also aliased. At the same time, many databases do not have support for `group by 1`. We decided that the right approach here was to reimplement the `unique` test query for BigQuery, via a `bigquery__test_unique` macro in the adapter plugin. That fix is now available in v1 prereleases (v1.0.0-rc1 most recently).

You can fix this in the meantime (while using v0.21) by copying the [BigQuery-specific SQL](https://github.com/dbt-labs/dbt-bigquery/blob/bb9caab8fd771d72bafdcfffb1ae72459ad704a2/dbt/include/bigquery/macros/adapters.sql#L198-L216) into a macro in your own project:

```sql
{% macro test_unique(model, column_name) %} 
  
 with dbt_test__target as ( 
    
   select {{ column_name }} as unique_field 
   from {{ model }} 
   where {{ column_name }} is not null 
    
 ) 
  
 select 
     unique_field, 
     count(*) as n_records 
  
 from dbt_test__target 
 group by unique_field 
 having count(*) > 1 
  
 {% endmacro %} 
 ```

**Closed by jtcohen6** 2021-11-12 14:34 UTC
Labels: bug, duplicate

**Comment by tracy-u** [comment] 2021-11-14 14:02
Ah, thanks for the update, @jtcohen6, and apologies I didn't find that issue in my search!

**Comment by clrcrl** [comment] 2021-11-14 14:52
ah @jtcohen6 , I helped Tracy search and _totally forgot_ that the repos have been split up! Maybe a hint on the issue template to search other repos would be useful? 🙏

**Comment by jtcohen6** [comment] 2021-11-15 12:43
@clrcrl Totally. We tried something in that vein, with these prompts when someone clicks the button to create a new issue (https://github.com/dbt-labs/dbt-core/issues/new/choose):

<img width="1168" alt="Screenshot 2021-11-15 at 13 43 06" src="https://user-images.githubusercontent.com/13897643/141784112-a25e0465-432e-4646-b787-2a9fb9163e5d.png">
