### ISSUE TITLE
[CT-2512] [Regression] profiles-dir - No such option

### ISSUE THREAD

**Issue by mk-oliver-s** [dbt-labs/dbt-core#7490] opened 2023-05-03 00:00 UTC
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

use `dbt --profiles-dir .. run` and I get an error

```
Usage: dbt [OPTIONS] COMMAND [ARGS]...
Try 'dbt -h' for help.

Error: No such option: --profiles-dir
```

The workaround now is to run `dbt run --profiles-dir ..` 

### Expected/Previous Behavior

Expected the run to work using the `..` as the profiles dir. 

### Steps To Reproduce

1. Install `dbt-core==1.5.0`
2. run `dbt --profiles-dir .. run`

### Environment

```markdown
- OS:Ubuntu 20.04
- Python: 3.10
- dbt (working version): 1.4.5
- dbt (regression version):1.5.0
```

**Comment by dbeatty10** [comment] 2023-05-03 01:45
Thanks for reaching out @mk-oliver-s 🙏 !

Indeed, the workaround you provided is actually our intended usage:
```shell
dbt run --profiles-dir path/to/directory
```

We switched to a [`click`](https://click.palletsprojects.com/)-based CLI, and our top-level options are specified like [this](https://github.com/dbt-labs/dbt-core/blob/f1dddaa6e96b743498440925a55e66a7d5cdacfa/core/dbt/cli/main.py#L153-L158) whereas our command parameters are like [this](https://github.com/dbt-labs/dbt-core/blob/f1dddaa6e96b743498440925a55e66a7d5cdacfa/core/dbt/cli/main.py#L543-L560).

I'm going to close this as `wont_fix` since this is the intended behavior, but I've opened [this](https://github.com/dbt-labs/docs.getdbt.com/pull/3329) PR to update our [1.5 migration guide](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5).

**Closed by dbeatty10** 2023-05-03 01:45 UTC
Labels: bug, triage, regression

**Comment by mk-oliver-s** [comment] 2023-05-03 05:13
ok, no worries! Thanks for the quick reply :D

**Comment by dbeatty10** [comment] 2023-05-03 16:51
Sure thing @mk-oliver-s 👍

**Comment by pdebelak** [comment] 2023-06-08 14:54
Just ran into this as well when trying out dbt-redshift 1.5.4 and didn't see this documented as a breaking change anywhere.
