### ISSUE TITLE
[CT-1132] [Feature] Jinja2 version update to 3.x

### ISSUE THREAD

**Issue by oonisim** [dbt-labs/dbt-core#5777] opened 2022-09-06 22:20 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

# Request
Allow Jinja2 version 3.x.

# Background
Trying to use DBT 1.x which is used organisation-wide. We also need to use Flask 2.x but they have conflict.
```
flask 2.1.2 depends on Jinja2>=3.0
dbt-core 1.2.1 depends on Jinja2==2.11.3
```

# Related

Googled related topics.

* https://github.com/dbt-labs/dbt-core/actions/runs/1309852354/workflow

### Describe alternatives you've considered

Could not find.

### Who will this benefit?

Flask 2 is widely used, hence should benefit the Python community.

### Are you interested in contributing this feature?

NA

### Anything else?

NA

**Comment by jaypeedevlin** [comment] 2022-09-07 00:30
This is a dupe of https://github.com/dbt-labs/dbt-core/issues/5723 which is a dupe of https://github.com/dbt-labs/dbt-core/issues/4748, which is closed because this has been done and is in the upcoming release 1.3!

_I don't work for dbt, I just follow the issues closely and chip in from time to time_

**Comment by lostmygithubaccount** [comment] 2022-09-07 02:53
@jaypeedevlin appreciate it! 

@oonisim closing as duplicate; you can try v1.3 out in beta now!

**Closed by lostmygithubaccount** 2022-09-07 02:53 UTC
Labels: enhancement
