### ISSUE TITLE
[CT-2291] {{ this }} not using custom generate_alias_name when called in a sql header

### ISSUE THREAD

**Issue by louis-vines** [dbt-labs/dbt-core#7151] opened 2023-03-10 13:20 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

(Note I believe this may be related to: https://github.com/dbt-labs/dbt-core/issues/2793)

When trying to set a variable in a sql header block like so:

```
{%- call set_sql_header(config) -%}
    declare max_date date default (
      select max(date_) from {{ this }} where date_ is not null and date_ >= '2023-01-01'
    );
{%- endcall %}
```
{{ this }} is not respecting the custom `generate_alias_name`  logic that I've created to strip the schema prefix from my models:

```
{% macro generate_alias_name(custom_alias_name=none, node=none) -%}
    {%- if custom_alias_name is not none -%}
        {{ return(custom_alias_name | trim) }}
    {%- elif node.schema == node.name.split('__')[0] -%} {# remove name prefix if it matches schema #}
        {{ return(node.name.split('__', maxsplit=1)[1]) }}
    {%- else -%}
        {{ return(node.name) }}
    {%- endif -%}
{%- endmacro -%}
```
(Note: I only need this custom alias macro because dbt needs unique file names and doesn't respect folders in model naming).

here is an example sql query I'm using:

```
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        partition_by={
            "field": "date_",
            "data_type": "date",
            "granularity": "day",
        },
        cluster_by=['token_address'],
    )
}}


{%- call set_sql_header(config) -%}
    declare _my_max_date date default (
      select max(date_) from {{ this }}
    );
{%- endcall %}

with what_i_want as (
    select * from {{ source('ethereum', 'token_transfers') }}
    {%- if is_incremental() %}
    where date(block_timestamp) >= _my_max_date
    {%- endif %}
)

, naive_approach as (
    -- shows how { this } should render but of course doesn't prune
    -- because bigquery doesn't support dynamic pruning:
    select * from {{ source('ethereum', 'token_transfers') }}
    {%- if is_incremental() %}
    where date(block_timestamp) >= ( select max(date_) from {{ this }} )
    {%- endif %}
)

, _dbt_max_partition_approach as (
    -- this is dbt's approach which does render correctly in the header,
    --  but still is a full scan of date_ ~= 10gb of data!
    select * from {{ source('ethereum', 'token_transfers') }}
    {%- if is_incremental() %}
    where date(block_timestamp) >= _dbt_max_partition
    {%- endif %}
)

select
    date(block_timestamp) as date_,
    *
from _dbt_max_partition_approach
```

and the version from `target/run`:

```

      -- generated script to merge partitions into `eunice-data-dev-louis`.`base`.`bug_example`
      declare dbt_partitions_for_replacement array<date>;



        declare _dbt_max_partition date default (
      select max(date_) from `eunice-data-dev-louis`.`base`.`bug_example`
      where date_ is not null
    );

        -- 1. create a temp table


    declare _my_max_date date default (
      select max(date_) from `eunice-data-dev-louis`.`__schema_not_set__`.`base__bug_example`
    );

    create or replace table `eunice-data-dev-louis`.`base`.`bug_example__dbt_tmp`
    partition by date_
    cluster by token_address
    OPTIONS(
      description="""""",

      expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 hour)
    )
    as (


with what_i_want as (
    select * from `bigquery-public-data`.`crypto_ethereum`.`token_transfers`
    where date(block_timestamp) >= _my_max_date
)

, naive_approach as (
    -- shows how { this } should render but of course doesn't prune
    -- because bigquery doesn't support dynamic pruning:
    select * from `bigquery-public-data`.`crypto_ethereum`.`token_transfers`
    where date(block_timestamp) >= ( select max(date_) from `eunice-data-dev-louis`.`base`.`bug_example` )
)

, _dbt_max_partition_approach as (
    -- this is dbt's approach which does render correctly in the header,
    --  but still results in a full scan of date_ ~= 10gb of data
    select * from `bigquery-public-data`.`crypto_ethereum`.`token_transfers`
    where date(block_timestamp) >= _dbt_max_partition
)

select
    date(block_timestamp) as date_,
    *
from _dbt_max_partition_approach
    );
```

Note: I've set `dataset:__schema_not_set ` in my `profiles.yml` to highlight the issue

### Expected Behavior

`{{ this }}` should be using my custom `generate_alias_name` when inside a sql header so should compile to ``dev`.`base`.`bug_example``

### Steps To Reproduce

1. use a custom `generate_alias_name` macro like the one I've provided
2. reference {{ this }} in sql_header block
3. you should see that {{ this }} is not using the custom `generate_alias_name` macro.

### Environment

```markdown
- OS: macos
- Python: Python 3.10.6
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment] 2023-03-14 00:41
Thanks for opening this up and giving such a nice write-up @louis-vines !

Agreed that you are asking for the same thing as https://github.com/dbt-labs/dbt-core/issues/2793 (or https://github.com/dbt-labs/dbt-bigquery/issues/286).

Basically, #2793 is asking for `sql_header` to be "late-rendered" (or re-rendered) similarly to how pre-hooks and post-hooks are rendered at execution time.

Your custom `generate_alias_name` would take effect if `sql_header` were also late-rendered (but it isn't).

A different issue + PR that seems similar to what you are trying to do:
- https://github.com/dbt-labs/dbt-bigquery/issues/286
- https://github.com/dbt-labs/dbt-bigquery/pull/285

I'm going to close this as a duplicate of https://github.com/dbt-labs/dbt-core/issues/2793 and/or https://github.com/dbt-labs/dbt-bigquery/issues/286. But if you feel there's something unique/different about this one, please let me know and we can re-open this one.

### Workaround

If I understood your example properly, you can try overriding the [declare_dbt_max_partition](https://github.com/dbt-labs/dbt-bigquery/blob/463a292f9e77fe36ee410fd5a2029e9c9b42070d/dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql#L10-L22) macro and peel out this part:
```
where {{ partition_by.field }} is not null
```

e.g., add your custom logic in a macro like this within your dbt project:
```sql
{% macro declare_dbt_max_partition(relation, partition_by, compiled_code, language='sql') %}

  {%- if '_dbt_max_partition' in compiled_code and language == 'sql' -%}

    declare _dbt_max_partition {{ partition_by.data_type }} default (
      select max({{ partition_by.field }}) from {{ this }}
    );
  {%- endif -%}
{% endmacro %}
```

Caveats:
- I don't know if this will be "safe" for you or not.
- Also, it will apply to every model in your project, which may or may not be what you want.

**Closed by dbeatty10** 2023-03-14 00:41 UTC
Labels: bug, triage

**Comment by louis-vines** [comment] 2023-03-14 10:40
Thanks for the swift response @dbeatty10. I think https://github.com/dbt-labs/dbt-bigquery/issues/286 does what I need, I'll take a look at implementing this as my `declare_dbt_max_partition` macro today
