### ISSUE TITLE
Support Materialized Views

### ISSUE THREAD

**Issue by clausherther** [dbt-labs/dbt-core#1162] opened 2018-12-03 16:51 UTC
Docs: https://docs.snowflake.net/manuals/sql-reference/sql/create-materialized-view.html

Ideally this would also support the `cluster by` keyword:
```
create materialized view "schema"."my_mview"
cluster by ( id ) 
as 
select 1 as id,
         2 as name
```

**Comment by clausherther** [comment] 2019-05-13 19:53
Looks like this was added in 0.13.1
(PR #1432 )

**Comment by drewbanin** [comment] 2019-05-13 20:10
@clausherther not so! #1432 fixed a problem where dbt couldn't run _if a materialized view lived in the dbt schema_. dbt still does not support the _creation_ of materialized views on Snowflake, though it is something I've been experimenting with recently.

In your mind, what's the advantage of using a materialized view over a dbt `table` model that's refreshed with some cadence? I seem to recall some pre-release Snowflake functionality that would auto-update materialized views, but I'm struggling to find that info presently

**Comment by clausherther** [comment] 2019-05-13 20:35
Ah, I misread this in the release notes: "Add "MaterializedView" relation type to the Snowflake adapter"

Personally, I don't think I have a good use case for MVs in Snowflake, that need has really been largely replaced by dbt. I think I opened the issue alongside the one for _transient_ tables, to keep track of new Snowflake features you potentially want to support.

**Comment by drewbanin** [comment] 2019-05-13 20:41
alright, thanks for the additional context! Happy to leave this open to track the Snowflake feature, but also welcome input from anyone who 👍'd the issue to chime in with some use cases!

**Comment by jrandrews** [comment] 2019-06-07 16:30
I'm trying to think how we would deal with MViews in dbt. You don't really want to drop and recreate them every time because then there would be a lot of extra time and cost by Snowflake bringing them up-to-speed with the underlying data. They do act like views when they are "stale" or not completely refreshed so at least there wouldn't be any problems with what happens if they are queried if not completely rebuilt:

`Data accessed through materialized views is always current, regardless of the amount of DML that has been performed on the base table. If a query is run before the materialized view is up-to-date, Snowflake either updates the materialized view or uses the up-to-date portions of the materialized view and retrieves any required newer data from the base table.` 
https://docs.snowflake.net/manuals/user-guide/views-materialized.html

Perhaps they would be like incremental tables where they are only re-created when a) they don't exist or b ) when forcing a full refresh?

There is also the potential for a lot of run-time error with MViews in Snowflake because they are limited in what they support from a SQL perspective. My concern is that it would be pretty difficult for dbt to parse and do a compile-time validation of what is not legitimate for an MView which would lead in many cases to dbt runs failing if the MView gets compiled but then fails creation or update at run-time. The list of things is too long for me to write here but see link above.

**Comment by drewbanin** [comment] 2019-09-11 19:00
Thanks @mike-weinberg! I don't think it would be too challenging to create a `materialized_view` materialization in dbt. I think the logic would look like:
- if the relation doesn't exist
   - create a materialized view
- else if the relation exists but is not a materialized view:
   - drop the existing relation
   - create a materialized view
- else if the relation exists and is a materialized view and dbt is in `full-refresh` mode:
   - replace the materialized view
- else:
    - no-op

I still think that [the list of caveats](https://docs.snowflake.net/manuals/user-guide/views-materialized.html#limitations-on-creating-materialized-views) are too restrictive for most modeling use cases (no window functions, no unions, limited aggregates, can't query views, etc etc etc). Still, happy to support these as I do think the first use-case you've pointed out here @mike-weinberg is good and legitimate. Plus, I imagine that these materialized views will only become more capable over time.

If someone is interested in creating this materialization, it all should be pretty doable in user-space! Would love to discuss the implementation further if anyone picks it up :)

**Comment by automagic** [comment] 2020-01-23 15:58
Redshift is also planning on supporting materialized views (in preview):

https://docs.aws.amazon.com/redshift/latest/dg/mv.html

It appears that many of the same limitations apply as with Snowflake materialized views.

In addition, Redshift appears to keep the data static until a refresh command is issued at which time it either incrementally updates the data if certain conditions are met, or does a full rebuild.

While I agree that there will be limited cases where this makes sense in modeling, surely there are valid and interesting use cases.

**Comment by drewbanin** [comment] 2020-01-23 16:28
Thanks @automagic! I used to be not-so-bullish on Materialized views, but the idea of these incremental refreshes is really appealing. One thing I particularly like about them: refreshing a table can happen concurrently with external queries. When dbt replaces tables, it currently blocks if there are long-running select statements hitting the table.

The one challenge here is going to be knowing when dbt should rebuild the MV, vs. just refresh it. We can leverage the `--full-refresh` flag, but that feels a little heavy handed. It would certainly be pretty cool if dbt could check if the columns in the view have changed, a la #320. Even better would be some sort of logical comparison (eg. check the hash of the SQL that created the model against the hash of the new model).... but that could be something for a separate issue :)

**Comment by jonah-juul** [comment] 2020-04-08 16:14
BigQuery has a similar feature https://cloud.google.com/bigquery/docs/materialized-views-intro

Would definitely be useful

**Comment by bashyroger** [comment] 2020-06-17 08:34
Even with the limitations native Snowflake MV's have, supporting them in DBT will become more useful once the **Transparent MV usage** functionality has been released _(in private preview at the moment of writing this)_. Basically this is functionality akin to Oracle's QUERY_REWRITE.
See my write up on this new feature (and others) and the SF new features video that mentions it:
https://www.linkedin.com/pulse/my-pov-new-snowflake-features-announced-june-2020-werschkull-/

**Comment by jtcohen6** [comment] 2020-06-17 16:23
Hey @bashyroger, check out:
* Initial work on a `materialized_view` dbt materialization in [this repo](https://github.com/fishtown-analytics/dbt-labs-experimental-features)
* Yesterday's dbt community office hours ([youtube](https://www.youtube.com/watch?v=awj-5aYXZnc)). I mentioned the functionality akin to Oracle's `QUERY_REWRITE `, as it's the biggest feature currently supported for BigQuery's MVs ([docs](https://cloud.google.com/bigquery/docs/materialized-views)). I don't know as much about Snowflake's support for this, it sounds like it's TK.

**Comment by mike-weinberg** [comment] 2020-06-17 23:15
Since this thread is warming up, let's make it spicy 🌶️ !

Snowflake recently announced a clever feature they're calling "transparent materialized views". 

In the future, if a plan node of a query is equivalent to or is a subset of the plan node of a materialized view, then the materialized view will be used, even if it isn't referenced, because it is provably equal. 

So, if you identify common aggregations, and build materialized views for those aggregations, then queries which have steps which are equivalent to those materialized views will be rewritten by the planner to use those materialized views. Alternatively, you could maintain multiple copies of the same table, but with different clustering keys, and snowflake will automatically pick the best one. This is analogous to Vertica's concept of projections. 

Personally, I think this is a big deal, and if snowflake expands support to include INNER JOIN and UNION ALL clauses, then chains of MV's might become the best way to express many dags. Even in the absence of that, the ability to maintain copies of tables with various clustering keys means that MVs could accelerate regular views enough to enable decent-performing low latency reporting when combined with a CDC ELT vendor.

**Comment by nareshkumaryadav** [comment] 2020-09-16 10:28
What is the latest state on this one ? Is this issue still open ?

**Comment by kamleshsinhchauhan** [comment] 2020-09-17 10:35
I also want to know this as I am going to source control snowflake and views also need to source control like tables.

**Comment by jtcohen6** [comment] 2020-09-21 20:08
Hey @nareshkumaryadav, this issue is definitely still open.
- I played around with materialized views on the Core Four databases back in June, so there's code available if you want to implement a halfway-decent version in your own project.
- There are some _small_ changes we'd want to make in dbt to include database metadata on MVs, specifically in Postgres + Redshift. Almost all the other code required here is SQL + Jinja, meaning that you have full power to try it, test it, and adapt it yourself.
- Eventually, I imagine we'll want to define MVs as a native dbt materialization. We haven't yet for a couple of reasons:
    - Unlike `view`, `table`, `ephemeral`, and `incremental`—which, with some small exceptions, have the same functionality across all four databases—a `materialized_view` necessarily means something quite different on each of Postgres, Redshift, Snowflake, and BigQuery.
    - That functional variance also exists over time, as each warehouse continues to expand the footprint of its MV implementation. We're still not sure what we _want_ to do with MVs—real-time aggregation of event streams? rollup cubes for BI query rewrite?—and dbt has an opinionated modeling framework. We definitely don't want to constrain the bounds of what's _possible_ in dbt, but at the same time we don't want to write a bunch of code into dbt-core without having some strong recommendations for when to leverage that code.

All of which is to say: I'd find it really valuable to hear more about what you're thinking of doing with MVs in your own project.

@kamleshsinhchauhan It sounds like what you're after may be slightly different: we have long supported `view` and `table` as materialization types on Snowflake. Check out [the docs on materializations](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/materializations/#section-materializations). If you are thinking about [Snowflake materialized views](https://docs.snowflake.com/en/user-guide/views-materialized.html), then this is the right thread!

**Comment by fairchild** [comment] 2021-02-01 05:31
I thought I'd share another use case.  We are considering use of materialized views in snowflake.  Our use case is to load [Debezium cdc data](https://debezium.io/documentation/reference/connectors/postgresql.html#postgresql-events) to a staging table with variant column that accumulates the stream.  Materialized views would be created from the staging table to a history table for the corresponding source table.  We could create the materialized views out of band from DBT and then treat them as DBT sources, but would prefer to have it all in DBT if possible.    

It would be great to hear if folks are having success with the [experimental](https://github.com/fishtown-analytics/dbt-labs-experimental-features/tree/master/materialized-views/macros/snowflake) implementation, and/or if that is likely to make its way into a dbt release in the near future.

**Comment by tomharrisonjr** [comment] 2021-02-24 16:46
> Thanks @automagic! I used to be not-so-bullish on Materialized views, but the idea of these incremental refreshes is really appealing. One thing I particularly like about them: refreshing a table can happen concurrently with external queries. When dbt replaces tables, it currently blocks if there are long-running select statements hitting the table.
> 
> The one challenge here is going to be knowing when dbt should rebuild the MV, vs. just refresh it. We can leverage the `--full-refresh` flag, but that feels a little heavy handed. It would certainly be pretty cool if dbt could check if the columns in the view have changed, a la #320. Even better would be some sort of logical comparison (eg. check the hash of the SQL that created the model against the hash of the new model).... but that could be something for a separate issue :)

Not sure I understand why this is an issue?  Redshift does support MVs now, including automated refresh, and internally knows whether they can be incrementally updated or require a full update.  The refresh occurs asynchronously (scheduled to avoid conflict with other uses).  dbt should simply recognize that when a view is MV, it simply needs to leave it alone unless the query itself has changed.

**Comment by tomharrisonjr** [comment] 2021-02-24 19:07
Our analytics team is suffering with poor performance of `dbt` generated views.  We have confirmed that a redshift-managed materialized view runs in a second or two compared to the standard view created by `dbt` which now takes several minutes to run (so: 2 orders of magnitude faster in this case).  They have tried `dbt` options, but the tradeoffs are poor for their use-case.  Is there any update or plan to support redshift (and bigtable and snowflake) materialized views soon?

**Comment by jtcohen6** [comment] 2021-02-26 11:36
> including automated refresh

I didn't know this! I just updated the sample code in https://github.com/fishtown-analytics/dbt-labs-experimental-features/pull/11 to add an `auto_refresh` config on Redshift. That's really compelling; in my anecdotal experience, the manual `refresh materialized view` statement was quite slow to run.

The question at this point isn't, Can you use materialized views with dbt? You absolutely can, by including some custom macros and materializations in your project. The question is, Do we have a recommended implementation of MVs we feel great about, such that we want to set it as the standard for all new projects going forward?

Materialized views have come a long way in just the past year, but they still have significant limitations. Particularly on Redshift, MVs do not support late binding, and they can't be identified in `pg_depend` (https://github.com/awslabs/amazon-redshift-utils/issues/499), so it's impossible for dbt to know when they've been cascade-dropped. When an MV needs to be replaced (whether because its definition has updated, or the schema of the underlying table has changed), I don't see a way to do this both reliably and atomically.

**Comment by LoekL** [comment] 2021-04-27 09:08
We support a large number of event types which we split out in separate tables (one for each event) for a variety of reasons. Currently we keep all these up-to-date by running hourly incremental updates. When moving this part of our setup to materialized views:

1. We have way less moving parts / stuff to maintain. I also suspect, though depending on your pricing model, it can be cheaper.
2. We get side-benefits like "smart tuning" on BigQuery ([reference](https://cloud.google.com/bigquery/docs/materialized-views-intro)).
3. Our DBT pipeline has to take care of way less models which means it'll be done quicker with the models that aren't suitable for MV's.

**Comment by bytekast** [comment] 2021-06-17 21:29
+1 Would really love to see this implemented. Auto refreshed materialized views in Redshift are much more performant and efficient than an incremental materialization based on my tests.

**Comment by kristiyan-dimitrov** [comment] 2021-06-24 19:20
Adding my +1 for materialized views. Would be great to have, we're using Postgres.

**Comment by poudrouxj** [comment] 2021-06-30 12:17
+1 following

**Comment by maver1ck** [comment] 2021-06-30 19:56
Guys,
How this one is working ?
https://materialize.com/dbt-materialize-jaffle-shop-demo/

**Comment by amychen1776** [comment] 2021-08-25 16:49
@maver1ck 
> Guys,
> How this one is working ?
> https://materialize.com/dbt-materialize-jaffle-shop-demo/

I'm aware of 2 people using the Materialize adapter in production. Check out the #db-materialize channel in slack to keep up to date/engage with others interested in the adapter.

**Comment by raajpackt** [comment] 2021-09-28 14:49
+1 for redshift materialized views

**Comment by benjaminwootton1981** [comment] 2021-11-18 14:55
Materialised Views have definite uses in anything latency sensitive.  The warehouse will update the MV on insert into the underlying table rather than waiting for DBT to run.  

It would be great to create these from DBT and then create references to them for downstream batch DBT runs.  

Another +1 for this feature, Snowflake primarily.

**Comment by ckaiser-graniterock** [comment] 2021-12-07 21:31
+1 MV's Snowflake

**Comment by grimwm** [comment] 2022-01-28 18:08
+1 MVs in Postgres

**Comment by sql-dr-watson** [comment] 2022-02-01 19:34
+1 MV's in Snowflake

**Comment by cwelton** [comment] 2022-03-10 04:06
+1 for MVs in general, but given this has been open since 2018 and still no MVs... not so hopeful.

**Comment by smitsrr** [comment] 2022-03-24 08:32
At this point we might need a community contributor to write the custom materialization with the logic @drewbanin outlined above. https://github.com/dbt-labs/dbt-core/issues/1162#issuecomment-530519585

**Comment by ybressler** [comment] 2022-03-25 17:49
+1 for MVs

Would help solve this issue with cloning: https://github.com/dbt-labs/dbt-snowflake/issues/118

**Comment by hsenger-tiger** [comment] 2022-04-13 18:52
Any update here from the DBT side? This would be very helpful for the performance reasons mentioned many times earlier.

**Comment by jspreddy** [comment] 2022-05-16 19:11
+1 really need this for performance.

**Comment by simonmd** [comment] 2022-06-02 19:49
+1 MVs in Postgres

**Comment by kgeis** [comment] 2022-06-07 00:14
I am using PostgreSQL, and when I started using dbt, I really wanted it to support MVs in PostgreSQL. That was when my thinking was to run dbt on demand to create the structure of my data mart. Since then I think I've come more to the "dbt way" where I run dbt on a schedule in order to populate my data mart.

In PG, there is no standard way to schedule MV refreshes and no support for log-based refresh of MVs. This says to me that an MV in PG is equivalent to materializing a dbt model as a table and then scheduling a dbt run at the OS level to refresh it.

I see the value of MV support for platforms with either internal scheduling (e.g. Oracle REFRESH clause) or incremental refresh (e.g. Oracle FAST clause) of MVs based on underlying changes, such as Oracle or I think Snowflake. I no longer feel like I need this for PG.

**Comment by leahtessem** [comment] 2022-06-07 14:53
@drewbanin I have a draft version of adding in MVs for Snowflake, but am hoping to get some assistance with adding tests. Can you point me to someone who could help?

**Comment by mike-luabase** [comment] 2022-07-14 18:56
+1 for clickhouse MV's!

**Comment by Bruno1298** [comment] 2022-07-20 12:21
+1 for MV BigQuery and Snowflake

**Comment by MarcinZegar** [comment] 2022-10-31 21:13
Any updates on this ticket?

**Comment by willbryant** [comment] 2022-10-31 21:42
Use https://github.com/dbt-labs/dbt-labs-experimental-features/tree/main/materialized-views and give feedback there.

**Comment by wmoustafa** [comment] 2023-05-26 00:42
This is some early work on integrating DBT, [Coral](https://github.com/linkedin/coral), and Spark to implement materialized views and incremental view maintenance on various engines, but starting with Spark. This DBT extension defines a new materialization mode called `incremental_maintenance` that automatically evaluates the query incrementally. Source code can be found under [coral-dbt](https://github.com/linkedin/coral/tree/master/coral-dbt) and [coral-incremental](https://github.com/linkedin/coral/tree/master/coral-incremental). There are also some [slides](https://www.slideshare.net/walaa_eldin_moustafa/incremental-view-maintenance-with-coral-dbt-and-iceberg) going through the design/implementation. Please feel free to test it, try it, or extend it.

**Comment by dbeatty10** [comment] 2023-05-26 13:24
Thank you for sharing @wmoustafa ! The slides were well-written and explained a couple big ideas (transpilation via [Coral](https://github.com/linkedin/coral) and `incremental_maintenance` as a drop-in replacement for the `table` materialization).

**Comment by dbeatty10** [comment] 2024-04-03 01:20
Closing in favor of:
- https://github.com/dbt-labs/dbt-core/issues/6911

**Closed by dbeatty10** 2024-04-03 01:20 UTC
Labels: help_wanted, redshift, snowflake, bigquery, postgres, materialized_views
