### ISSUE TITLE
[CT-2444] [ADAP-466] [Bug] using grant config with a group doesn't work

### ISSUE THREAD

**Issue by stevenayers-tvx** [dbt-labs/dbt-core#7421] opened 2023-04-20 15:02 UTC
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When adding a group as a grantee, it throws a "user 'group_name' does not exist"

### Expected Behavior

It should be able to handle groups

### Steps To Reproduce

1. Create a group in redshift
2. add the group to grant config on a model

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-redshift:
```

**Comment by dbeatty10** [comment] 2023-04-20 16:36
Thanks for reaching out @stevenayers-tvx !

Are you trying to do something like the following with the new [groups](https://docs.getdbt.com/docs/build/groups) coming out in Core 1.5 in combination with [grants](https://docs.getdbt.com/reference/resource-configs/grants#configuring-grants)?

If so, then you are observing expected behavior; by defining a group, dbt is **not** creating any users or roles in your database. Rather, dbt model groups are intended to indicate which models can [access](https://docs.getdbt.com/docs/collaborate/govern/model-access) other models.

If you want to tie together your dbt model groups with [RBAC](https://en.wikipedia.org/wiki/Role-based_access_control) in your data platform, then that portion is up to you to accomplish.

### Example

`models/_groups.yml`
```
groups:
  - name: finance
    owner:
      email: finance@jaffleshop.com
```

This won't work unless you _independently_ create the `finance` user (or role) in your data platform:

`models/_models.yml`
```
models:
  - name: transactions
    config:
      grants:
        select: ['finance']
```

Since this is intended behavior, I'm going to close this as "not planned". But please let me know if I misunderstood at all.

**Closed by dbeatty10** 2023-04-20 16:36 UTC
Labels: bug, triage
