### ISSUE TITLE
[CT-2571] [Tech debt] Remove old docker cruft

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#7610] opened 2023-05-11 21:29 UTC
I made a few inquiries, and it _appears_ that the `docker-compose.yml` and `Dockerfile.test` files found at the root of the repo may no longer be in use.  The Makefile references them for people who might do local dev in docker (currently no one, I think) and the adapters used them for testing at one point, but that may have been moved (or should be moved).

Obviously a low priority, but having a cleaner-looking repo root would be nice. 
:)

Context-- these docker files were never meant to be used as a general use container.  That lives at `/docker`.

**Comment by dbeatty10** [comment] 2023-05-11 21:42
I frequently use the instructions within the [contributing](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#initial-setup) file in order to spin up a local postgres instance to run integration tests against. I use the same postgres instance to run small dbt projects against when reproducing bug reports.

Its fine with me if these files are deleted or moved as long as we retain some kind of cross-platform instructions for developing against (e.g., a postgres instance running within a Docker container).

**Comment by dbeatty10** [comment] 2023-05-22 17:36
Since our [contributing](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#initial-setup) instructions either directly or indirectly rely on `Makefile`, `docker-compose.yml` and `Dockerfile.test`, I'm going to close this as "not planned".

We can re-open if anyone proposes a cross-platform approach for developing that is superior to the current contributing instructions.

**Closed by dbeatty10** 2023-05-22 17:36 UTC
Labels: oss_tooling
