### ISSUE TITLE
[CT-2438] [Bug] Unable to use an overridden `ref` in the schema.yaml file 

### ISSUE THREAD

**Issue by jsnb-devoted** [dbt-labs/dbt-core#7410] opened 2023-04-19 17:47 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This could be completely unsupported so this very well might not be a bug. I'll try my best to characterize it. 

We override the ref in our project with the macro `dbt/macros/ref.sql` -- a simplified/psuedocode version looks like :
```
{% macro ref(model_name, final=None) %}
  {% if final == False %}
    {% do return(builtins.ref(model_name)) %}
  {% else %}
    {% do return(builtins.ref(model_name).replace_path(schema="final_schema")) %}
  {% endif %}
{% endmacro %}
```
When we use it in our sql models it works as expected. In certain cases the ref resolves to the default transform schema in others it resolves to a "final" schema. We have been using it for a year or so and it works great. The result is we effectively have 2 copies of every model: a "transform" version and "final" version.

Recently I've been looking into how we can write tests that compare the 2 versions of the table. For example when we do a `dbt run` I want to know if the model increased the row count by a certain factor since the previous run. I tried using the [expect_table_row_count_to_equal_other_table_times_factor](https://github.com/calogica/dbt-expectations/tree/main#expect_table_row_count_to_equal_other_table_times_factor) test and using _our_ ref as the compare model:
```
models:
  - name: sample_model
    description: Fake model - strictly used for testing
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table_times_factor:
          compare_model: ref("sample_model", final=True)
          factor: .01
    columns:
      - name: col_a
        data_type: NUMBER(1,0)
```
I was hoping that the ref in this case would behave the same way but the run command fail in the parsing step (I think?) with a traceback that ends with:
```
TypeError: BaseRefResolver.__call__() got an unexpected keyword argument 'final'
```
I've tried tinkering with a few things but it is feeling like the usage of `ref` in the schema is limited to the `builtins.ref` and that is why the function signature doesn't have our `final` kwarg.

### Expected Behavior

I would expect that using `ref` in a schema.yaml file would be the same `ref` that gets resolved in the SQL. I _think_ that isn't happening but this could easily be user error.

### Steps To Reproduce

1. Override the ref
2. Use it in the a yaml file for a test
3. Run the mode / test or parse/compile

### Relevant log output

```shell
BaseRefResolver.__call__() got an unexpected keyword argument 'final'
22:52:19  Traceback (most recent call last):
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/main.py", line 136, in main
    results, succeeded = handle_and_check(args)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/main.py", line 253, in run_from_args
    results = task.run()
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/task/parse.py", line 82, in run
    self.get_full_manifest()
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/task/parse.py", line 63, in get_full_manifest
    manifest = loader.load()
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/parser/manifest.py", line 359, in load
    self.parse_project(
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/parser/manifest.py", line 466, in parse_project
    parser.parse_file(block, dct=dct)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/parser/schemas.py", line 498, in parse_file
    self.parse_tests(test_block)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/parser/schemas.py", line 475, in parse_tests
    self.parse_test(block, test, None)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/parser/schemas.py", line 468, in parse_test
    self.parse_node(block)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/parser/schemas.py", line 409, in parse_node
    node = self._parse_generic_test(
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/parser/schemas.py", line 338, in _parse_generic_test
    self.render_test_update(node, config, builder, schema_file_id)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/parser/schemas.py", line 395, in render_test_update
    add_rendered_test_kwargs(context, node, capture_macros=True)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/clients/jinja.py", line 652, in add_rendered_test_kwargs
    kwargs = deep_map_render(_convert_function, node.test_metadata.kwargs)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/utils.py", line 228, in deep_map_render
    return _deep_map_render(func, value, ())
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/utils.py", line 194, in _deep_map_render
    ret = {k: _deep_map_render(func, v, (keypath + (str(k),))) for k, v in value.items()}
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/utils.py", line 194, in <dictcomp>
    ret = {k: _deep_map_render(func, v, (keypath + (str(k),))) for k, v in value.items()}
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/utils.py", line 196, in _deep_map_render
    ret = func(value, keypath)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/clients/jinja.py", line 646, in _convert_function
    value = get_rendered(value, context, node, capture_macros=capture_macros, native=True)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/clients/jinja.py", line 590, in get_rendered
    return render_template(template, ctx, node)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/clients/jinja.py", line 545, in render_template
    return template.render(ctx)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/clients/jinja.py", line 186, in render
    return self.environment.handle_exception()
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/dbt/clients/jinja.py", line 143, in quoted_native_concat
    head = list(islice(nodes, 2))
  File "<template>", line 1, in top-level template code
  File "/home/jbrownstein/.pyenv/versions/3.10.9/envs/dbt/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
TypeError: BaseRefResolver.__call__() got an unexpected keyword argument 'final'
```

### Environment

```markdown
- OS:Ubuntu 20.04.6
- Python: 3.10.9
- dbt: 1.4.5
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Could be similar to [this issue](https://github.com/dbt-labs/dbt-core/issues/4491)

**Comment by dbeatty10** [comment] 2023-04-24 20:37
Thanks for reaching out @jsnb-devoted !

I think you are right that usage of `ref` in your `schema.yml` example is limited to the `builtins.ref` [[1](https://github.com/dbt-labs/dbt-core/blob/d07603b288eddbc474b9f6fdbe8c82105ae5f856/core/dbt/context/providers.py#L844-L845), [2](https://github.com/dbt-labs/dbt-core/blob/d07603b288eddbc474b9f6fdbe8c82105ae5f856/core/dbt/context/providers.py#L461), [3](https://github.com/dbt-labs/dbt-core/blob/d07603b288eddbc474b9f6fdbe8c82105ae5f856/core/dbt/context/providers.py#L216)] and that is why the function signature doesn't have your `final` kwarg.

I didn't fully confirm, but I think this is known and expected behavior.

Does this work for you, by any chance?

```
models:
  - name: sample_model
    description: Fake model - strictly used for testing
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table_times_factor:
          compare_model: "{{ ref('sample_model', final=True) }}"
          factor: .01
```

**Comment by jsnb-devoted** [comment] 2023-04-24 21:41
Thanks for jumping in @dbeatty10. Looks like the same traceback with the syntax you suggested.

Do you think anyone else would want this feature or are we a bit of an edge case here? I suspect the number of folks that override the `ref` **and** use the `ref` in schema files is pretty small. I do have to think that other folks would find value in testing their data between runs? For example: "model_a's row count should be greater than the row count from the previous run"
Is there another way to achieve that type of testing?

**Comment by dbeatty10** [comment] 2023-04-25 02:58
I just tried your custom `ref` macro using dbt 1.5.0rc2 and it worked 🤷 It gave that stacktrace when I switched back to 1.4.

Do you want to give 1.5 a shot?

Here's a quick way to to spin up a disposable virtual environment with the most recent pre-release of dbt 1.5.0 (just replace `dbt-postgres` with your desired adapter and run `deactivate` when you are done using it):
```shell
python3 -m venv env
source env/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade --pre dbt-postgres~=1.5.0.dev0 dbt-core~=1.5.0.dev0
source env/bin/activate
dbt --version
```

### But if the above doesn't work...

It does seem like many folks would find value in testing two different variants of the "same" model, but I'm not aware of a recommended approach.

A couple cases that come to mind (both related to testing equality):
- significant refactor of dbt logic; test that they both match
- data migration to dbt where there's a table being produced by some non-dbt process and the logic is being re-written in dbt; test that they both match

It sounds like you have additional use-case(s) for this too.

Some ideas how to approach this:
1. define each of your final versions as a source
1. hard-code `compare_model: final_schema.sample_model` instead of `compare_model: ref("sample_model", final=True)`
1. model versions
1. make a separate copy of each model to be tested in this manner

None of these ideas feel great. Idea 1 is the one I've used personally before.

### Model versions
Here's how it could look using [model versions](https://docs.getdbt.com/docs/collaborate/govern/model-versions) (being introduced in 1.5):
```yaml
  - name: dim_customers
    versions:
      - v: 2
        defined_in: dim_customers  # keep original file name of dim_customers.sql -- make sure to define an `alias` config in that file too!
      - v: 1
        tests:
          - dbt_expectations.expect_table_row_count_to_equal_other_table:
              compare_model: ref("dim_customers", v=2)  # or just ref("dim_customers") to get the latest one
```
Downsides:
- It would take two different .sql files for each model
- not really what dbt model versions are designed for

**Comment by jsnb-devoted** [comment] 2023-04-25 16:49
hi @dbeatty10 -- working in 1.5 sounds promising! We have it on our roadmap to upgrade shortly after 1.5 is released. I'll definitely test it out as soon as we upgrade.

Appreciate you thinking through some of the alternative options for testing. I agree that they don't _feel_ great but they seem doable. I think defining them as a source could potentially be interesting especially if we code generate the sources. I wouldn't want people to have to define sources manually any time they want to use this functionality. It feels like it would be functional but our dependency graph might look a little funky:
```
source:model_a_final -> model:model_a
```
If it doesn't work in 1.5 then we'll explore some more options. Most of all we just want it to look and feel like dbt tests. We really enjoy having a single "data quality" framework integrated with the model development.

### Swap tables
I feel like I've asked this elsewhere so feel free to swat this one away but is there any considerations for a materialization that would persist the previous version of the table? Thinking of a "swap" pattern where `dbt run` creates your model `CREATE TABLE model_a_swp` _then_ `dbt test` will test the `_swp` table eg (`SELECT id, COUNT(*) FROM model_a_swp...`) _then_ if tests pass replace `model_a` with `model_a_swp` either with `ALTER TABLE model_a RENAME...`. It doubles the storage footprint but for folks on cloud data warehouse's that cost would be nominal.

**Comment by dbeatty10** [comment] 2023-06-08 16:53
> Most of all we just want it to look and feel like dbt tests. We really enjoy having a single "data quality" framework integrated with the model development.

I'm with you on wanting an experience where you are using single thing that is simple to use and reason about 🧠

It's just the devil in the details to achieve something like that.

> is there any considerations for a materialization that would persist the previous version of the table?

Thank you for the thought leadership you've already contributed in https://github.com/dbt-labs/dbt-core/discussions/5687 🏆 That's definitely the place for that discussion!

> If it doesn't work in 1.5 then we'll explore some more options.

Since I believe the original reported issue related to `ref` overrides is addressed in 1.5, I'm going to close  this as "completed".

@jsnb-devoted Could you reach out if this doesn't work in 1.5 and we can re-assess from there?

**Closed by dbeatty10** 2023-06-08 16:53 UTC
Labels: bug, triage, Team:Language

**Comment by jsnb-devoted** [comment] 2023-06-08 17:03
hi @dbeatty10 -- I lost track of this a while ago. There was some interest in looking at the row count changes over more than just the previous run (eg - is this row count within x standard deviations of the last n runs?). I kludged something together that tracked the row counts in a separate table and then created a generic test that analyzed the row counts in that table. It hasn't actually gained any traction so I might revisit just the "is this row count within x% of the last run" using this method. I'll reach out if the 1.5 updates didn't solve this. Thanks so much!

**Comment by dbeatty10** [comment] 2023-06-08 17:34
Sounds great @jsnb-devoted !
