### ISSUE TITLE
[CT-399] [Bug] seed : value made of underscore-separated numbers gets detected as int ("integer out of range" error)

### ISSUE THREAD

**Issue by mdutoo** [dbt-labs/dbt-core#4740] opened 2022-02-17 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On dbt 1.0.1 / Python 3.8.10 / Ubuntu 20.04, running dbt seed on the following file :
[seed_underscore_detected_as_int_example.csv](https://github.com/dbt-labs/dbt-core/files/8089654/seed_underscore_detected_as_int_example.csv)

raises the following error:
14:59:39  Database Error in seed seed_underscore_detected_as_int_example (seeds/seed_underscore_detected_as_int_example.csv)
14:59:39    integer out of range

The reason seems to be that the "29051_00040" value is wrongly read as "2905100040" and the  column type wrongly detected as integer.

Workaround : enforcing the column type as text solves it.

### Expected Behavior

Type of a column with value "29051_00040" should be detected as text.

### Steps To Reproduce

See above

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt: 1.0.1
```

### What database are you using dbt with?

postgres

**Comment by ChenyuLInx** [comment] 2022-03-01 21:36
Hey @mdutoo , thanks for submitting this, and sorry for getting back to you late! 
I think this might be a known issue for seed.
We use `agate` to infer the column types for seeds [here](https://github.com/dbt-labs/dbt-core/blob/8f50eee330ea34dd6aaba40993a01a380373fa32/core/dbt/clients/agate_helper.py#L143). And somehow it decided to cut the `_` in the example you provided and convert it to an integer. One quick way to get around this is to define the column type in `dbt_project.yml` in your project repo following the guide [here](https://docs.getdbt.com/faqs/seed-datatypes)

This is what I had locally that solves the issue
```
seeds:
  toy: # you must include the project name
    seed_underscore_detected_as_int_example:
      +column_types:
        underscore_detected_as_int: varchar(32)
```

@jtcohen6  One thing I noticed is that we get the agate table from the CSV, but looks like we just used the column type but not the value from it when running the seed. Is this the intended behavior?

**Comment by jtcohen6** [comment] 2022-03-02 14:55
This is a weird one indeed. The cause for this issue seems to lie in `agate.Table.from_csv()`:
```python
ipdb> with open(path) as csvfile:
        reader = csv.reader(csvfile)
        for row in reader:
            print(", ".join(row))
underscore_detected_as_int
29051_00040
```
```python
ipdb> import agate
ipdb> table = agate.Table.from_csv(path)
ipdb> table.print_table()
| underscore_detect... |
| -------------------- |
|        2,905,100,040 |
```

**Comment by iknox-fa** [comment] 2022-04-11 15:16
@jtcohen6 This ticket came up in BLG today, but it seems that adding an explicit `+column_types` to the project config fixes this specific case.  Do we want to make explicit changes to the codebase so this happens automatically?  We're concerned it may cause other mis-identified column types.

**Comment by jtcohen6** [comment] 2022-04-21 10:29
@mdutoo Thanks for the response!

> And BTW I don't like putting configuration in dbt_project.yml and prefer YAML config files.

Good news: Since v0.21, you can also specify this config in a one-off yaml file:
```yml
# seeds/config.yml
version: 2

seeds:
  - name: seed_underscore_detected_as_int_example
    config:
      column_types:
        underscore_detected_as_int: varchar(32)
```

> So the easiest solution is probably merely to tell developers in the documentation that type autodetection is there to help developers start out faster, but beyond that enforcing column types is strongly advised because type autodetection it is notoriously not reliable (and then see how to make that easier as said).

I agree with this! Would you be up for opening an issue (or even a PR) over at https://github.com/dbt-labs/docs.getdbt.com/issues? The [current docs on the `column_types` config](https://docs.getdbt.com/reference/resource-configs/column_types) understate this a bit:

> Without specifying this, dbt will infer the datatype based on the column values in your seed file.

In the meantime, I'm going to close the issue. We know that `agate` can be... interesting, in undesirable ways: #3413

**Closed by jtcohen6** 2022-04-21 10:29 UTC
Labels: bug, seeds, Team:Execution, jira
