### ISSUE TITLE
[CT-2633] [Feature] Contract explanations

### ISSUE THREAD

**Issue by elyobo** [dbt-labs/dbt-core#7775] opened 2023-06-04 03:13 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Contract enforcement is great, but I would like a standard way to provide context to developers around _why_ contract enforcement is turned on. Developers may think to look for notes in the YAML or possibly exposures, but I think that we could make this better by default and possibly better still with additional config in a couple of ways.

* I think it's a reasonable to infer that if a model that has a contract has an exposure that depends on it that it's likely related; listing associated exposures as context when a contract failure occurs is almost certainly going to be helpful.
* It would also be useful in the contract section to configure some of `enforcement_failure_explanation` message that could be output when a contract failure occurs.

Both of these would provide context to developers in the place that the test is failing (during development, ci, whatever) that tells them what they should do, e.g. to point them in the right direction if there is actually a contract violating schema change required.

### Describe alternatives you've considered

Notes in the YAML, process documentation (both of which may also be helpful, but both of which are easier to miss).

### Who will this benefit?

Developers, data consumers.

### Are you interested in contributing this feature?

If given guidance; I don't write much python!

**Comment by jtcohen6** [comment] 2023-07-10 13:47
@elyobo I really like the spirit of this issue!

The underlying motivation — finding ways to surface information about a model's contract to developers, so they have visibility into (& empathy for) the other dbt projects & non-dbt processes that are depending on a stable upstream interface — in short, I'm all about it.

If it's natural to ask the question, "Which exposures depend on this contracted model?" — we should solve for that with interactive experiences for lineage & documentation that are embedded in the development workflow

If the desire is to provide some additional context on the importance of this model, and its intended use — why not include that in the `description`? Again, if the problem is that it's too many clicks to get from "model failed to build with contract error" to "read the model's description" — we should solve for that within the development experience, by doing a better job of surfacing that metadata in more places more easily.

All of which is to say, while I share the goals, I'm not convinced that surfacing additional information in the error message is the best way to accomplish it:

```
20:53:45  Compilation Error in model dim_customers (models/dim_customers.sql)
20:53:45    This model has an enforced contract that failed.
            >>>>
            And that's important because ... !!
            {read the description, check downstream exposures}
            <<<<
20:53:45    Please ensure the name, data_type, and number of columns in your contract match the columns in your model's definition.
20:53:45
20:53:45    | column_name | definition_type | contract_type | mismatch_reason    |
20:53:45    | ----------- | --------------- | ------------- | ------------------ |
20:53:45    | customer_id | TEXT            | INT           | data type mismatch |
20:53:45
20:53:45
20:53:45    > in macro assert_columns_equivalent (macros/materializations/models/table/columns_spec_ddl.sql)
```

I'm going to close this as a feature request for now, but I really like the topic of conversation, and I'm very curious to hear if you think of more we could be doing here!

**Closed by jtcohen6** 2023-07-10 13:47 UTC
Labels: enhancement, wontfix, model_contracts
