### ISSUE TITLE
[CT-2276] [Bug] `dbt docs` home and package level pages show `(loading)` rather than standard text

### ISSUE THREAD

**Issue by rlh1994** [dbt-labs/dbt-core#7132] opened 2023-03-07 10:35 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using dbt docs with the latest version of dbt the main home page and any package level pages all show `(loading)` instead of the standard text or package overview code.

### Expected Behavior

Pages would show standard overview text as has done in previous versions.

### Steps To Reproduce

1. Create a new project with `dbt init` and ensure it has a valid profile
2. Run `dbt docs generate`
3. Run `dbt docs serve` 
4. View the rendered page

### Environment

```markdown
- OS: Ubuntu 22.04.2
- Python: 3.8.16
- dbt: 1.4.0 upwards, confirmed working as expected on 1.3.3
```

### Which database adapter are you using with dbt?

postgres, snowflake

### Additional Context

Live example can be seen here: https://snowplow.github.io/dbt-snowplow-web/#!/overview

![image](https://user-images.githubusercontent.com/8260415/223397584-4b3268f6-544b-4822-8f50-cf6e536d5412.png)

**Comment by emmyoop** [comment] 2023-03-07 14:04
@rlh1994 thanks for writing up this issue with a reproduction case.  That's always useful!  Can you confirm the exact version of dbt you are on with `dbt --version`?

This was a known regression (see https://github.com/dbt-labs/dbt-core/issues/6801) that was patched in 1.4.2 via `dbt-docs` PR [#367](https://github.com/dbt-labs/dbt-docs/pull/367).  I just verified that this works with the latest patch (`1.4.4`).

**Comment by rlh1994** [comment] 2023-03-07 16:53
Hey @emmyoop thanks for that, I was running 1.4.1 locally where I first tested the issue, and can see when upgrading to 1.4.4 this is somewhat fixed. I had been testing with 1.4.4 on a github action but we weren't copying the `index.html` file over to the github pages folder as it doesn't seem to change, but in this case it needed to!

I've got one remaining difference I'm still seeing compared to before. While the pages are now displaying text, each package is displaying the same default overview - it used to be that is we created a docblock in a package with the name of the package (i.e. `{% docs __snowplow_web__ %}`) that this would render as the welcome page for that package when clicked on. At the moment every package on the served docs site has the same welcome page.

**Comment by emmyoop** [comment] 2023-03-07 17:17
@rlh1994 one tip for detecting changes to the index.html short of doing a file diff is that anytime we have changes in our `CHANGELOG.md` under Docs ([example](https://github.com/dbt-labs/dbt-core/blob/1.4.latest/CHANGELOG.md#docs)) the `index.html` is changing.  This section of the changelog is dedicated to the docs we serve up.

Running on `dbt-postgres` v1.4.4 I am unable to reproduce the issue you're experiencing.

When I have this defined in `models/overview.md`
```md
{% docs __dbt_utils__ %}
# Utility macros
Our dbt project heavily uses this suite of utility macros, especially:
- `surrogate_key`
- `test_equality`
- `pivot`
{% enddocs %}
```
It overrides the docs to show this custom page, as expected

![Screen Shot 2023-03-07 at 11 06 26 AM](https://user-images.githubusercontent.com/7070049/223495903-da22acc7-ee69-4793-b6f4-364ed4c05875.png)

I also tried this with multiple packages and all custom welcome pages still rendered correctly.   I'm going to close this as it is functioning as expected.

**Closed by emmyoop** 2023-03-07 17:17 UTC
Labels: bug, triage

**Comment by dbeatty10** [comment] 2023-03-10 21:22
@rlh1994 thank for you reporting this in https://github.com/dbt-labs/dbt-docs/issues/390 ❤️ 

@emmyoop and I worked together to solve it in https://github.com/dbt-labs/dbt-docs/pull/391, and it will be included in our next patch release of dbt-core.
