### ISSUE TITLE
[CT-3433] [Feature] Prioritize view creation before table materialization

### ISSUE THREAD

**Issue by rchui** [dbt-labs/dbt-core#9175] opened 2023-11-29 19:01 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When a table is reset it executes a DROP TABLE CASCADE that also drops any downstream views that depend on the table. When the DBT graph is large and concurrency is limited, this can cause periods of time where the table has been reset but the view on top of it does not exist.

Take an example of concurrency of 1 with TableA, ViewA, and TableB, where ViewA references TableA. If the order is
1. TableA
1. ViewA
1. TableB

Then you will not have any issues. If instead the order is
1. TableA
1. TableB
1. ViewA

ViewA is not populated until TableB is completed. If TableB takes a long time to materialize, then ViewA will not be present for that period. This causes problems for downstream consumers that depend on those views existing.

I'd like (either by default or configuration) to favor the creation of views before tables all dependencies being equal.

### Describe alternatives you've considered

None that I can think of. I would love if this already existed and just isn't documented clearly somewhere in the DBT docs.

### Who will this benefit?

This will benefit users that operate in non data warehouse environments that have constrained concurrency and large numbers of models to evaluate. In general it will reduce the downstream impact on consumers that depend on views in order to query data sources.

### Are you interested in contributing this feature?

I can, but wouldn't know where to start.

**Comment by dbeatty10** [comment] 2023-12-06 21:21
Thanks for reporting this @rchui !

### Big picture

I think the root cause is that both Postgres and Redshift have early-binding views that are coupled with the underlying datasets they select from.

Redshift provided a work-around for this issue when they introduced [late-binding views](https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-redshift-now-supports-late-binding-views-referencing-amazon-redshift-and-redshift-spectrum-external-tables/) in late 2017. These were [supported in dbt](https://www.getdbt.com/blog/using-redshift-s-late-binding-views-with-dbt) shortly thereafter.

But it sounds like there's still no way to directly support [late-binding views in postres](https://eradman.com/posts/late-binding-views.html).

### Blue/green deployments to the rescue?

Using a blue/green deployment using [`dbt clone`](https://docs.getdbt.com/reference/commands/clone) wouldn't help in this case because cloning in dbt-postgres relies on views, so we'd just run into the same problem as above.

### Our recommendation
- In Postgres, use [tables](https://docs.getdbt.com/docs/build/materializations#table) (rather than [views](https://docs.getdbt.com/docs/build/materializations#view)) for any data sets that are exposed to consumers

### Summary

Since this is primarily driven by the design choices of Postgres and we don't plan on implementing work-arounds, I'm going to close this as "not planned".

I've opened https://github.com/dbt-labs/docs.getdbt.com/issues/4602 to give clearer guidance about how to avoid this in Postgres.

**Closed by dbeatty10** 2023-12-06 21:21 UTC
Labels: enhancement, triage, postgres
