### ISSUE TITLE
[CT-3359] [Bug] A snapshot block with no name fails without providing the offending file path

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#9033] opened 2023-11-08 02:31 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I was testing some snapshot behaviour and freewheeled the first bit:

```sql
{% snapshot %}

{% endsnapshot %}
```

before remembering that there was a chunk of config I needed to copy-paste, so I went and grabbed that from the docs and wound up with:

```sql
{% snapshot %}
{{
    config(
      target_database='analytics',
      target_schema='snapshots',
      unique_key='id',

      strategy='check',
      check_cols='all'
    )
}}
select 1 as id
{% endsnapshot %}
```

I added some other sql model and yaml files, and then tried to do a `dbt run`, where I got this error: 
```
01:40:21  Encountered an error:
Parsing Error
  at path ['name']: None is not of type 'string'
```

I couldn't work out what was missing, and spent 10mins doing a global search for `name` and deleting files to try and track down the issue. 

It turns out that I didn't provide a name for the snapshot. 
```
{% snapshot like_this %}

{% endsnapshot %]
```

### Expected Behavior

The error message to indicate where the snapshot was missing. 

Minimum: 

```
              ↓     this bit is new!        ↓
Parsing Error in snapshots/first_snapshot.sql
  at path ['name']: None is not of type 'string'
```

Ideally: 

```
Parsing Error in snapshots/first_snapshot.sql
  A snapshot block does not include a name. See https://docs.getdbt.com/docs/build/snapshots
```

Better still: 
In dbt v2, let's make snapshots behave like every other node type, with only one per file and no opening/closing snapshot blocks. 

### Steps To Reproduce

```sql
--snapshots/my_snapshot.sql
{% snapshot %}

select 1 as id

{% endsnapshot %}
```

### Environment

```markdown
- OS:
- Python:
- dbt: 1.7.0
```

**Comment by dbeatty10** [comment] 2023-11-08 14:42
Yeah!

In an ideal world, you could freewheel and the dbt error messages would give the same experience as [bumper bowling](https://www.latimes.com/archives/la-xpm-1989-10-28-vw-730-story.html) and help you ~knock down the pins~ build your snapshot. 🎳 

I've added your suggested syntax to the acceptance criteria for this preexisting issue:
- https://github.com/dbt-labs/dbt-core/issues/8276#issuecomment-1801998599

Also added your particular situation to something to consider when creating the functional tests.

I'm going to close this as a duplicate of https://github.com/dbt-labs/dbt-core/issues/8276. Feel free to add any relevant commentary that I missed into that issue.

**Closed by dbeatty10** 2023-11-08 14:42 UTC
Labels: bug, snapshots, triage
