### ISSUE TITLE
[Bug] "at" operator does not take into account relationships data tests

### ISSUE THREAD

**Issue by jdimmerman** [dbt-labs/dbt-core#10648] opened 2024-08-30 15:28 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Consider
* Model1 has no other model dependencies
* Model2 has no other model dependencies but has a relationships data_test that references Model1
* Model3 depends on Model2 via a ref in a FROM clause

If I run `dbt build --select @Model3` against a database without any models yet created, I'll get an exception `relation "Model1" does not exist` when dbt evaluates Model2's relationships.

This makes managing relationships tests when using a CI environment much less efficient or automated.

### Expected Behavior

The "at" (@) operator evaluates relationship tests when determining the dependency graph and includes the dependent relationships models in the build.

### Steps To Reproduce

1. Model1 has no other mode dependencies
2. Model2 has no other mode dependencies but has a relationships data_test that references Model1
3. Model3 depends on Model2 via a ref in a FROM clause
4. Run `dbt build --select @Model3` against a database without any models yet created

### Environment

```markdown
- OS: Debian GNU/Linux 12 (bookworm)
- Python: 3.12.2
- dbt: 1.8.5
```

### Which database adapter are you using with dbt?

postgres, snowflake

### Additional Context

Thanks!

**Comment by dbeatty10** [comment] 2024-09-03 21:52
Thanks for reaching out about this @jdimmerman !

The default of [`indirect_selection`](https://docs.getdbt.com/reference/global-configs/indirect-selection) is [`eager`](https://docs.getdbt.com/reference/global-configs/indirect-selection#eager-mode), and it has the behavior you observed.

But if you use `buildable` or `eager` (or `empty`), it won't run that particular `relationships` data test. Using one of these other options lines up with our [recommended approach](https://docs.getdbt.com/reference/global-configs/indirect-selection#eager-mode):

<img width="700" alt="image" src="https://github.com/user-attachments/assets/4ea5ec64-b027-4b68-95e5-0ce6cbcb9429">

So you can do something like this instead:

```shell
dbt build --select @Model3 --indirect-selection buildable
```

You might wonder why an option like `buildable` isn't the default -- this is because we added this new method relatively recently, and we didn't want to make any breaking changes for pre-existing projects.

Since this is expected behavior, and you can configure this, I'm going to close this as not planned.

**Closed by dbeatty10** 2024-09-03 21:52 UTC
Labels: bug, triage, dbt tests

**Comment by jdimmerman** [comment] 2024-09-04 13:17
@dbeatty10  - Thank you! This is very helpful and the `indirect-selection` flag of course solves my issue. To confirm, is the following statement correct?
> There is no way to automatically include in the build those models referenced by tests.

**Comment by dbeatty10** [comment] 2024-09-04 14:42
That is correct 👍

The "ancestors and descendants" for the ["at" operator](https://docs.getdbt.com/reference/node-selection/graph-operators#the-at-operator) are exclusively models, seeds, and snapshots, and do not include data tests. While we wouldn't be eager to add it, we could imagine a new operator ("star"?) that counted data tests as a descendant. Ex. `dbt run --select "*my_model"`. Alternatively, we could add a global flag that allowed configuring the "at" operator to consider data tests also. Again, neither sound like something we'd be interested in actually doing.

👉 Rather, if you want to run the data tests for unbuilt models that weren't selected via [`indirect_selection = "eager"`](https://docs.getdbt.com/reference/global-configs/indirect-selection#eager-mode), then [deferral](https://docs.getdbt.com/reference/node-selection/defer) is the way to go!

**Comment by jdimmerman** [comment] 2024-09-04 16:01
OK great, definitely understood on the "not something we plan on doing" piece, just wanted to confirm I was on the same page. Thanks!
