### ISSUE TITLE
[CT-416] [Bug] Under certian circumstances releases can be tagged incorrectly without raising errors/warnings

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4945] opened 2022-03-23 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During the ill-fated release of 1.1.0b1 we ran into an issue where the github action used in the release process, `softprops/action-gh-release@v1`, did not return any indicator that the tag it was trying to push already existed due to an earlier failed release.  This left us with a mismatched release/tag that pointed to different commit shas and it also broke docker image builds because they rely on accurate tags.

My initial thought is that we need to ensure the tag doesn't exist before running `action-gh-release`, however there may be better ways to address the problem.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by iknox-fa** [comment] 2022-05-18 19:09
@emmyoop 
This came up in our core BLG meeting.  Given that you're doing release work, would this be included in what you're planning?  If not let us know so we can point it for future sprints.

**Comment by emmyoop** [comment] 2022-05-18 20:52
@iknox-fa yes, this is covered by https://github.com/dbt-labs/actions/issues/16.

**Comment by emmyoop** [comment] 2023-08-01 15:23
duplicate of https://github.com/dbt-labs/actions/issues/16 which is already done

**Closed by emmyoop** 2023-08-01 15:23 UTC
Labels: tech_debt, release
