### ISSUE TITLE
[CT-2407] [Bug] dbt can't find snapshots using their filenames if mixed cased but only if inside a subfolder

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#7346] opened 2023-04-13 01:48 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This one is really strange - for some reason dbt can't find snapshots via their mixedCased file names if inside a subfolder. 

Note for readers of this issue - you are encouraged to follow `snake_case` when naming stuff (for example: https://github.com/dbt-labs/docs.getdbt.com/discussions/1659) which would avoid a scenario like this.

### Expected Behavior

dbt should find `snappy_2` / `snaPPy_2.sql` just like it did for model `bAr.sql`.

### Steps To Reproduce

Project setup:

```yaml
# dbt_project.yml
name: my_dbt_project
profile: snowflake
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table
```

Nodes (**pay close attention to the filenames**):

```sql
-- models/in_sub/bAr.sql
select 1 as id

-- snapshots/snaPPy_1.sql
{% snapshot snappy_1 %}
{{ config(target_schema='snapshots', unique_key='id', strategy='check', check_cols='all') }}
select 1 as id
{% endsnapshot %}

-- snapshots/in_subfolder/snaPPy_2.sql
{% snapshot snappy_2 %}
{{ config(target_schema='snapshots', unique_key='id', strategy='check', check_cols='all') }}
select 1 as id
{% endsnapshot %}

-- snapshots/in_subfolder/snappy_3.sql
{% snapshot snappy_3 %}
{{ config(target_schema='snapshots', unique_key='id', strategy='check', check_cols='all') }}
select 1 as id
{% endsnapshot %}
```

```sh
$ dbt ls -s bAr
my_dbt_project.in_sub.bAr

$ dbt ls -s snaPPy_1
my_dbt_project.snaPPy_1.snappy_1

$ dbt ls -s snaPPy_2
01:43:49  The selection criterion 'snaPPy_2' does not match any nodes
01:43:49  No nodes selected!

$ dbt ls -s snappy_3
my_dbt_project.in_subfolder.snappy_3.snappy_3
```

### Environment

```markdown
- OS: macOS
- Python: 
Python 3.10.10
- dbt:
Core:
  - installed: 1.4.5
  - latest:    1.4.5 - Up to date!

Plugins:
  - snowflake: 1.4.2 - Up to date!
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

For more info on why this was brought up - basically the Cloud IDE uses the syntax:

```
2+<active_file_name>+2
```

To draw the lineage on an active file/node. Due to this issue - the snapshot `snaPPy_2.sql` / `snappy_2` isn't rendered in the Cloud IDE when it is the active file - unless you tweak the selection to be the string `"snappy_2"` (as opposed to it's default selection when you open up the file `"2+snaPPy_2+2"`) - then it's okay.

Internal JIRA: https://dbtlabs.atlassian.net/browse/XP-2094

**Comment by markproctor1** [comment] 2023-04-14 20:43
@dbeatty10 I didn't understand your last comment when you said "before I close" do you mean close the bug report?

We noticed this behavior because the snapshots are showing up in the DAG sometimes and not others. We suspected it had something to do with subfolders but couldn't nail down what (we're very new to dbt).

Are you saying if they're snake case it works so it's not a bug?

**Comment by dbeatty10** [comment] 2023-04-15 00:09
@markproctor1 We're going to do an update to fix this for you, we're just going to make that update in our Cloud software (which we track in Jira tickets) rather than Core (which we track in GitHub issues like this one).

The root cause is when the filename differs from the name of the snapshot. In the example below, if you change the filename to be the same as the snapshot name, it should work:
```
-- snapshots/in_subfolder/oops_this_name_is_different.sql
{% snapshot this_is_the_snapshot_name %}
{{ config(target_schema='snapshots', unique_key='id', strategy='check', check_cols='all') }}
select 1 as id
{% endsnapshot %}
```

I'm going to close _this_ issue, but please don't think we are closing this altogether: our Cloud team still has visibility on this.

And please feel free to ask any follow-up questions -- although this issue is labeled as "closed", we're listening and will respond 😄

**Closed by dbeatty10** 2023-04-15 00:09 UTC
Labels: bug, triage
