### ISSUE TITLE
[CT-1364] [Bug] profiles.yml in project dir doesn't work when running dbt from outside with --project-dir

### ISSUE THREAD

**Issue by seub** [dbt-labs/dbt-core#6092] opened 2022-10-18 15:03 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Assume your `profiles.yml` is located at the root of your project's directory. Since dbt 1.3, this is supposed to be the first location dbt looks in. However, running dbt from outside with:

```
dbt run --project-dir /path/to/project
```
returns a "profile not found" error.

### Expected Behavior

dbt should look for `profiles.yml` in the project's root directory, regardless of whether dbt is ran from the directory itself or from outside.

### Steps To Reproduce

1. Put profiles.yml in project's directory
2. `dbt run --project-dir /path/to/project`

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by seub** [comment] 2022-10-19 15:05
Oh, alright then, so it appears that behavior is intentional and not a bug. For what it's worth, I would not have made this choice.

Of course in 95% of the cases, users will run dbt from the project's root directory, so it doesn't matter; we are only talking about the 5% remaining cases. Of course, one can always specify the `profiles.yml` location explicitly with the `--profiles-dir` flag; we are only talking about what happens if one doesn't.

Does it make more sense that profiles.yml is _by default_ located in the current working directory, or in the project's root directory? What is the most common use case? In my humble opinion, it's the second one. 

The flags `--project-dir` and `--profiles-dir` can still be independent when they are both used. However when the second flag isn't used, it doesn't have to default to `.`, and could default to the project dir, I don't see a contradiction there. By definition, anything "typically" located in the project's root directory (`target`, `logs`, etc) is not independent from the location of `dbt_project.yml`. Just my two cents :)

**Comment by dbeatty10** [comment] 2022-10-19 15:21
Thank you for opening this @seub !

@jtcohen6 stated it perfectly: we did consider making the default profiles directory dependent on the project directory like you expected, but ultimately decided to make them fully independent.

There's a couple ways to get the behavior you described:

### Option 1

Just like @jtcohen6 said:
```
dbt run --project-dir /path/to/project --profiles-dir path/to/project
```

### Option 2

In zsh and bash (and maybe other shells), you can also do the following:
```shell
(cd /path/to/project && dbt build)
```

This will temporarily move you into the project directory, run dbt, and then return back to your original directory that you ran the command from.

I'm going to close this since the the implementation is as intended and there are ways to use the profiles.yml specified in your project directory.

You're welcome to continue the conversation here and provide feedback if you feel we made the wrong design decision!

**Closed by dbeatty10** 2022-10-19 15:21 UTC
Labels: bug, triage

**Comment by seub** [comment] 2022-10-19 15:28
Thank you for your reply! I expressed my humble opinion in my second message above, I think our messages probably got crossed :)
