### ISSUE TITLE
[CT-1699] [Feature] Expose `custom_name` as part of a test's node.

### ISSUE THREAD

**Issue by elongl** [dbt-labs/dbt-core#6470] opened 2022-12-21 09:14 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I'd like to be able to distinct whether a custom name (`name` property) was defined on a test.
Our [report](https://storage.googleapis.com/elementary_static/elementary_demo.html#/test-results) is heavily based on dbt's `graph` within the context.
We'd like to be able to show the custom name of a test if provided, else use the test's name.

However, at the moment, I couldn't find a way to distinguish whether a custom name is defined or not.
On the test's node, `name`, `alias`, and `unique_id` all change according to it so there's no way to differ between them.

### Describe alternatives you've considered

I tried to re-calculate the logic that generates the alias and figure out if it's equal.
I tried to analyze a test's node and find patterns by which it could be possible to deduce whether a custom name is defined or not.

Both options ended up being too unreliable.

Here's a test without a custom name:
```py
{'alias': 'relationships_stg_orders_order_id__order_id__ref_orders_',
 'build_path': None,
 'checksum': {'checksum': '', 'name': 'none'},
 'column_name': 'order_id',
 'columns': {},
 'compiled_path': None,
 'config': {'alias': None,
            'database': None,
            'enabled': True,
            'error_if': '!= 0',
            'fail_calc': 'count(*)',
            'limit': None,
            'materialized': 'test',
            'meta': {},
            'schema': 'dbt_test__audit',
            'severity': 'ERROR',
            'store_failures': None,
            'tags': [],
            'warn_if': '!= 0',
            'where': None},
 'config_call_dict': {},
 'created_at': 1671612547.613791,
 'database': 'ELEMENTARY_TESTS',
 'deferred': False,
 'depends_on': {'macros': ['macro.dbt.test_relationships',
                           'macro.dbt.get_where_subquery'],
                'nodes': ['model.playground.orders',
                          'model.playground.stg_orders']},
 'description': '',
 'docs': {'node_color': None, 'show': True},
 'file_key_name': 'models.stg_orders',
 'fqn': ['playground',
         'relationships_stg_orders_order_id__order_id__ref_orders_'],
 'language': 'sql',
 'meta': {},
 'metrics': [],
 'name': 'relationships_stg_orders_order_id__order_id__ref_orders_',
 'original_file_path': 'models/schema.yml',
 'package_name': 'playground',
 'patch_path': None,
 'path': 'relationships_stg_orders_order_id__order_id__ref_orders_.sql',
 'raw_code': '{{ test_relationships(**_dbt_generic_test_kwargs) }}',
 'refs': [['orders'], ['stg_orders']],
 'resource_type': 'test',
 'root_path': '/Users/egk/work/dbt/dbt-playground',
 'schema': 'elon_test_dbt_test__audit',
 'sources': [],
 'tags': [],
 'test_metadata': {'kwargs': {'column_name': 'order_id',
                              'field': 'order_id',
                              'model': '{{ '
                                       "get_where_subquery(ref('stg_orders')) "
                                       '}}',
                              'to': "ref('orders')"},
                   'name': 'relationships',
                   'namespace': None},
 'unique_id': 'test.playground.relationships_stg_orders_order_id__order_id__ref_orders_.6d96672978',
 'unrendered_config': {}}

```

Here's a test with a custom name:
```py
{'alias': 'Test the relationship between orders and stg_orders',
 'build_path': None,
 'checksum': {'checksum': '', 'name': 'none'},
 'column_name': 'order_id',
 'columns': {},
 'compiled_path': None,
 'config': {'alias': None,
            'database': None,
            'enabled': True,
            'error_if': '!= 0',
            'fail_calc': 'count(*)',
            'limit': None,
            'materialized': 'test',
            'meta': {},
            'schema': 'dbt_test__audit',
            'severity': 'ERROR',
            'store_failures': None,
            'tags': [],
            'warn_if': '!= 0',
            'where': None},
 'config_call_dict': {},
 'created_at': 1671612547.605803,
 'database': 'ELEMENTARY_TESTS',
 'deferred': False,
 'depends_on': {'macros': ['macro.dbt.test_relationships',
                           'macro.dbt.get_where_subquery'],
                'nodes': ['model.playground.orders',
                          'model.playground.stg_orders']},
 'description': '',
 'docs': {'node_color': None, 'show': True},
 'file_key_name': 'models.stg_orders',
 'fqn': ['playground', 'Test the relationship between orders and stg_orders'],
 'language': 'sql',
 'meta': {},
 'metrics': [],
 'name': 'Test the relationship between orders and stg_orders',
 'original_file_path': 'models/schema.yml',
 'package_name': 'playground',
 'patch_path': None,
 'path': 'Test the relationship between orders and stg_orders.sql',
 'raw_code': '{{ test_relationships(**_dbt_generic_test_kwargs) }}',
 'refs': [['orders'], ['stg_orders']],
 'resource_type': 'test',
 'root_path': '/Users/egk/work/dbt/dbt-playground',
 'schema': 'elon_test_dbt_test__audit',
 'sources': [],
 'tags': [],
 'test_metadata': {'kwargs': {'column_name': 'order_id',
                              'field': 'order_id',
                              'model': '{{ '
                                       "get_where_subquery(ref('stg_orders')) "
                                       '}}',
                              'to': "ref('orders')"},
                   'name': 'relationships',
                   'namespace': None},
 'unique_id': 'test.playground.Test the relationship between orders and '
              'stg_orders.b0acc6f96f',
 'unrendered_config': {}}
```

### Are you interested in contributing this feature?

Yes.

### Anything else?

I'd love to be pointed to the part in the code that generates the `alias` / `name` / `unique_id` in the first place.

**Comment by dbeatty10** [comment] 2022-12-22 00:21
Hey @elongl ! Thanks for all the detailed examples 🤩 

Let's suppose the user has a `relationships` test. It sounds like you are trying to determine if they have specified an `alias` for this test or not?

If provided, you want to show the value of the alias and otherwise show "relationships"?

Using dbt-core 1.3.1, it looks like it shows up (or not) as you'd want under the `config` key. I wonder if using an earlier version of dbt might explain the difference?

## Steps to reproduce

### Schema YAML

```yaml
version: 2

models:
  - name: orders
    columns:
      - name: id
        tests:
          - relationships:
              alias: Test the relationship between orders and stg_orders
              to: ref('stg_orders')
              field: id
```

### Steps to execute

Run the test:

```shell
dbt test --select orders
```

Finally, pretty print the manifest and look just at the part related to our test:

```shell
jq . target/manifest.json --sort-keys
```

### Without alias
```json
"test.my_dbt_project.relationships_orders_id__id__ref_stg_orders_.d0933588ce": {
    "alias": "relationships_orders_id__id__ref_stg_orders_",
    "build_path": "target/run/my_dbt_project/models/_models.yml/relationships_orders_id__id__ref_stg_orders_.sql",
    "checksum": {
      "checksum": "",
      "name": "none"
    },
    "column_name": "id",
    "columns": {},
    "compiled": true,
    "compiled_code": "\n    \n    \n\nwith child as (\n    select id as from_field\n    from `dbt-test-env`.`dbt_dbeatty`.`orders`\n    where id is not null\n),\n\nparent as (\n    select id as to_field\n    from `dbt-test-env`.`dbt_dbeatty`.`stg_orders`\n)\n\nselect\n    from_field\n\nfrom child\nleft join parent\n    on child.from_field = parent.to_field\n\nwhere parent.to_field is null\n\n\n",
    "compiled_path": "target/compiled/my_dbt_project/models/_models.yml/relationships_orders_id__id__ref_stg_orders_.sql",
    "config": {
      "alias": null,
      "database": null,
      "enabled": true,
      "error_if": "!= 0",
      "fail_calc": "count(*)",
      "limit": null,
      "materialized": "test",
      "meta": {},
      "schema": "dbt_test__audit",
      "severity": "ERROR",
      "store_failures": null,
      "tags": [],
      "warn_if": "!= 0",
      "where": null
    },
    "created_at": 1671667661.5697532,
    "database": "dbt-test-env",
    "deferred": false,
    "depends_on": {
      "macros": [
        "macro.dbt.test_relationships",
        "macro.dbt.get_where_subquery",
        "macro.dbt.should_store_failures",
        "macro.dbt.statement"
      ],
      "nodes": [
        "model.my_dbt_project.stg_orders",
        "model.my_dbt_project.orders"
      ]
    },
    "description": "",
    "docs": {
      "node_color": null,
      "show": true
    },
    "extra_ctes": [],
    "extra_ctes_injected": true,
    "file_key_name": "models.orders",
    "fqn": [
      "my_dbt_project",
      "relationships_orders_id__id__ref_stg_orders_"
    ],
    "language": "sql",
    "meta": {},
    "metrics": [],
    "name": "relationships_orders_id__id__ref_stg_orders_",
    "original_file_path": "models/_models.yml",
    "package_name": "my_dbt_project",
    "patch_path": null,
    "path": "relationships_orders_id__id__ref_stg_orders_.sql",
    "raw_code": "{{ test_relationships(**_dbt_generic_test_kwargs) }}",
    "refs": [
      [
        "stg_orders"
      ],
      [
        "orders"
      ]
    ],
    "relation_name": null,
    "resource_type": "test",
    "root_path": "/Users/dbeatty/projects/dbt-sandcastles/dbt/bigquery",
    "schema": "dbt_dbeatty_dbt_test__audit",
    "sources": [],
    "tags": [],
    "test_metadata": {
      "kwargs": {
        "column_name": "id",
        "field": "id",
        "model": "{{ get_where_subquery(ref('orders')) }}",
        "to": "ref('stg_orders')"
      },
      "name": "relationships",
      "namespace": null
    },
    "unique_id": "test.my_dbt_project.relationships_orders_id__id__ref_stg_orders_.d0933588ce",
    "unrendered_config": {}
  }
```

### With alias
```json
    "test.my_dbt_project.relationships_orders_id__id__ref_stg_orders_.d0933588ce": {
      "alias": "Test the relationship between orders and stg_orders",
      "build_path": "target/run/my_dbt_project/models/_models.yml/relationships_orders_id__id__ref_stg_orders_.sql",
      "checksum": {
        "checksum": "",
        "name": "none"
      },
      "column_name": "id",
      "columns": {},
      "compiled": true,
      "compiled_code": "\n    \n    \n\nwith child as (\n    select id as from_field\n    from `dbt-test-env`.`dbt_dbeatty`.`orders`\n    where id is not null\n),\n\nparent as (\n    select id as to_field\n    from `dbt-test-env`.`dbt_dbeatty`.`stg_orders`\n)\n\nselect\n    from_field\n\nfrom child\nleft join parent\n    on child.from_field = parent.to_field\n\nwhere parent.to_field is null\n\n\n",
      "compiled_path": "target/compiled/my_dbt_project/models/_models.yml/relationships_orders_id__id__ref_stg_orders_.sql",
      "config": {
        "alias": "Test the relationship between orders and stg_orders",
        "database": null,
        "enabled": true,
        "error_if": "!= 0",
        "fail_calc": "count(*)",
        "limit": null,
        "materialized": "test",
        "meta": {},
        "schema": "dbt_test__audit",
        "severity": "ERROR",
        "store_failures": null,
        "tags": [],
        "warn_if": "!= 0",
        "where": null
      },
      "created_at": 1671666629.884358,
      "database": "dbt-test-env",
      "deferred": false,
      "depends_on": {
        "macros": [
          "macro.dbt.test_relationships",
          "macro.dbt.get_where_subquery",
          "macro.dbt.should_store_failures",
          "macro.dbt.statement"
        ],
        "nodes": [
          "model.my_dbt_project.stg_orders",
          "model.my_dbt_project.orders"
        ]
      },
      "description": "",
      "docs": {
        "node_color": null,
        "show": true
      },
      "extra_ctes": [],
      "extra_ctes_injected": true,
      "file_key_name": "models.orders",
      "fqn": [
        "my_dbt_project",
        "relationships_orders_id__id__ref_stg_orders_"
      ],
      "language": "sql",
      "meta": {},
      "metrics": [],
      "name": "relationships_orders_id__id__ref_stg_orders_",
      "original_file_path": "models/_models.yml",
      "package_name": "my_dbt_project",
      "patch_path": null,
      "path": "relationships_orders_id__id__ref_stg_orders_.sql",
      "raw_code": "{{ test_relationships(**_dbt_generic_test_kwargs) }}{{ config(alias=\"Test the relationship between orders and stg_orders\") }}",
      "refs": [
        [
          "stg_orders"
        ],
        [
          "orders"
        ]
      ],
      "relation_name": null,
      "resource_type": "test",
      "root_path": "/Users/dbeatty/projects/dbt-sandcastles/dbt/bigquery",
      "schema": "dbt_dbeatty_dbt_test__audit",
      "sources": [],
      "tags": [],
      "test_metadata": {
        "kwargs": {
          "column_name": "id",
          "field": "id",
          "model": "{{ get_where_subquery(ref('orders')) }}",
          "to": "ref('stg_orders')"
        },
        "name": "relationships",
        "namespace": null
      },
      "unique_id": "test.my_dbt_project.relationships_orders_id__id__ref_stg_orders_.d0933588ce",
      "unrendered_config": {
        "alias": "Test the relationship between orders and stg_orders"
      }
    }
```

### diff
```diff
2c2
<     "alias": "relationships_orders_id__id__ref_stg_orders_",
---
>     "alias": "Test the relationship between orders and stg_orders",
14c14
<       "alias": null,
---
>       "alias": "Test the relationship between orders and stg_orders",
29c29
<     "created_at": 1671667661.5697532,
---
>     "created_at": 1671666629.884358,
64c64
<     "raw_code": "{{ test_relationships(**_dbt_generic_test_kwargs) }}",
---
>     "raw_code": "{{ test_relationships(**_dbt_generic_test_kwargs) }}{{ config(alias=\"Test the relationship between orders and stg_orders\") }}",
90c90,92
<     "unrendered_config": {}
---
>     "unrendered_config": {
>       "alias": "Test the relationship between orders and stg_orders"
>     }
```

**Comment by elongl** [comment] 2022-12-22 07:25
@dbeatty10 Apologies! I wasn't clear.
I was actually referring to the `name` property rather than `alias`.
For instance:
```yml
models:
  - name: stg_orders
    columns:
      - name: order_id
        description: The order ID
        tests:
          - relationships:
              name: test the relationship between orders and stg_orders.    <----------------------
              to: ref('orders')
              field: order_id
```

**Comment by dbeatty10** [comment] 2022-12-22 15:46
Ah, I see what you mean now @elongl

> I'd love to be pointed to the part in the code that generates the `alias` / `name` / `unique_id` in the first place.

I didn't know where this was located beforehand, so did a bunch of `grep`ing -- there's a _lot_ of string matches for `alias` / `name` / `unique_id` !

Ultimately, `git grep '"__"' .` gave a promising lead:
https://github.com/dbt-labs/dbt-core/blob/304797b099d3c7150ddd8ecc425ac5e872e0410b/core/dbt/parser/generic_test_builders.py#L40

Is this what you were looking for?

**Comment by elongl** [comment] 2022-12-28 11:41
I mostly want the place where the node is built so that both the test's custom name is accessible so that we can add the custom name property to the node (graph). Also, would you be on-board for adding it?

**Comment by jtcohen6** [comment] 2023-01-02 11:19
@elongl The current behavior is, if a user defines a custom `name` for a generic test, dbt will use it; otherwise, dbt will use some built-in rules to synthesize a `name` (via the method @dbeatty10 linked above) that should be both (a) unique and (b) not too long.

Are you looking for the ability to tell which of those two things has happened for a given test? Either the user configured a custom name, or they didn't and dbt synthesized one?

Also, we're at risk of confusing two things here: the `name` of _this specific instance of a generic test_ (unique in this project!), with the `test_name` property, which is the name of the generic test macro used for this test: `unique`, `relationships`, `something_custom`, ... (appears on many tests).

> We'd like to be able to show the custom name of a test if provided, else use the test's name.

It sounds like you're after some logic like: `name IF [is_custom_name_defined] ELSE test_name`, and there isn't currently a flag/property to the effect of `[is_custom_name_defined]`.

While I appreciate that this would enable you to display something nicer in the Elementary UI (looks very cool btw!), I'm not convinced this logic makes sense, given the risk of confusion mentioned above.

**Comment by elongl** [comment] 2023-01-03 09:42
Hi @jtcohen6 ! Thanks for the response.

I'd like to step-back from the technicality and explain my end-goal.
What I'd like is to be able to get from the _Jinja context_ the custom name that was defined on a _specific instance of a generic test_ like so:

```yml
- name: stg_orders
  columns:
    - name: order_id
      description: The order ID
      tests:
        - relationships:
            name: Test the relationship between orders and stg_orders     <------ Goal
            to: ref('orders')
            field: order_id
```

As with most other things about nodes in the project, I tried to extract this data from the `graph`.
However, given that there's currently no such property,
I tried to somewhat _calculate_ it based on the properties that I do have available.

Regarding the questions,

> Are you looking for the ability to tell which of those two things has happened for a given test? Either the user configured a  custom name, or they didn't and dbt synthesized one?

So yeah, this is one of my attempted solutions but I'm definitely open to alternatives.
The rational is that if I just know that a custom name is defined, I'll use `test_node.name` (which would be the custom name), otherwise I'll use `test_node.test_metadata.name` (test's class name like `relationships`).

Hopefully that clears things a bit.
Thanks a lot.

**Comment by jtcohen6** [comment] 2023-01-03 13:14
@elongl Appreciate the context! It's the first time I've heard this request, so while I don't think it's completely unreasonable, it does feel quite 

Here's an approach that, while imperfect and not guaranteed to work forever, does get you what you're after, by mocking the logic of `synthesize_generic_test_names`:
```sql
{% macro get_test_names() %}
  {% if execute %}
    {% for node in graph.nodes.values() %}
      {% if node.resource_type == 'test' and 'test_metadata' in node.keys() %}
        {% set generic_test_name = node.test_metadata.name %} {# 'unique', 'relationships', etc #}
        {% set this_test_name = node.name %}
        {% set nice_name =
                  generic_test_name if (
                    this_test_name.startswith(generic_test_name)
                    or this_test_name.startswith('source_' + generic_test_name)
                  ) else this_test_name
        %}
        {% do log(nice_name + ' (actual: ' + this_test_name + ')', info = true) %}
      {% endif %}
    {% endfor %}
  {% endif %}
{% endmacro %}
```

For example:
```yml
version: 2

models:
  - name: my_model
    columns:
      - name: id
        tests:
          - unique
          - not_null:
              name: cool_custom_name

sources:
  - name: my_src
    tables:
      - name: src_tbl
        columns:
          - name: id
            tests:
              - not_null
              - unique:
                  name: another_custom_name
```
```
$ dbt run-operation get_test_names
13:14:27  Running with dbt=1.4.0-b1
13:14:27  unique (actual: unique_my_model_id)
13:14:27  cool_custom_name (actual: cool_custom_name)
13:14:27  not_null (actual: source_not_null_my_src_src_tbl_id)
13:14:27  another_custom_name (actual: another_custom_name)
```

**Comment by Maayan-s** [comment] 2023-03-23 12:04
Hi, 
We implemented the logic you suggested and we agree it's an imperfect but certainly good enough solution.
As far as we are concerned, you can close the issue. 
Thanks for the help @jtcohen6 and @dbeatty10!

**Comment by dbeatty10** [comment] 2023-03-23 13:03
It's fantastic to hear about your implementation, @Maayan-s, and you are most welcome!

**Closed by dbeatty10** 2023-03-23 13:03 UTC
Labels: enhancement, triage, dbt tests, Team:Language
