### ISSUE TITLE
[CT-55] [Bug] var not injected in dbt run snapshot from dbt run invocation in 1.0.0+

### ISSUE THREAD

**Issue by saraleon1** [dbt-labs/dbt-core#4583] opened 2022-01-18 17:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In 1.0.0+ it appears that we are no longer able to inject var values into a dbt snapshot like so:

```
dbt snapshot --select dummy_snapshot --vars 'run_date: "2021-11-11"'
```

where the snapshot is defined as follows:

```
{% snapshot dummy_snapshot %}

{{
    config(


        target_schema = 'potato',
        unique_key = 'uniqueid',
        strategy = 'check',
        check_cols = 'all',
        updated_at = "cast ('{}' as timestamp)".format(var('run_date')),
        file_format = 'delta',
        invalidate_hard_deletes = true
    )
}}

select 1 as uniqueid, current_timestamp() as ts

{% endsnapshot %}
```

the logs confirm that a 'none' is being injected rather than the value passed ("2021-11-11").

However, creating the same snapshot and running it the same way in an environment on 0.21.0 works (the date is injected)

[snapshot_logs_100.txt](https://github.com/dbt-labs/dbt-core/files/7891328/snapshot_logs_100.txt)
[snapshot_logs_0210.txt](https://github.com/dbt-labs/dbt-core/files/7891329/snapshot_logs_0210.txt)

### Expected Behavior

specified var is injected to the snapshot the same in 0.21.0 as in 1.0.0

### Steps To Reproduce

1. go to dbt environment on 1.0.0+
2. create a snapshot as follows:

```
{% snapshot dummy_snapshot %}

{{
    config(
        target_schema = 'potato',
        unique_key = 'uniqueid',
        strategy = 'check',
        check_cols = 'all',
        updated_at = "cast ('{}' as timestamp)".format(var('run_date')),
        file_format = 'delta',
        invalidate_hard_deletes = true
    )
}}

select 1 as uniqueid, current_timestamp() as ts

{% endsnapshot %}
```

3. invoke the snapshot using this command:

```
dbt snapshot --select dummy_snapshot --vars 'run_date: "2021-11-11"'
```

4. observe 'none' being injected in the logs rather than the run_date passed in the dbt run call

### Relevant log output

```shell
2022-01-18T17:40:30.685676Z: 17:40:30  On snapshot.my_new_project.dummy_snapshot: /* {"app": "dbt", "dbt_version": "1.0.1", "profile_name": "user", "target_name": "default", "node_id": "snapshot.my_new_project.dummy_snapshot"} */

      

      create or replace transient table DEMO_DB.potato.dummy_snapshot  as
      (

    select *,
        md5(coalesce(cast(uniqueid as varchar ), '')
         || '|' || coalesce(cast(cast ('None' as timestamp) as varchar ), '')
        ) as dbt_scd_id,
        cast ('None' as timestamp) as dbt_updated_at,
        cast ('None' as timestamp) as dbt_valid_from,
        nullif(cast ('None' as timestamp), cast ('None' as timestamp)) as dbt_valid_to
    from (
        



select 1 as uniqueid, current_timestamp() as ts

    ) sbq



      );
```

Versus:

```
2022-01-18T17:51:04.596006Z: On snapshot.jaffle_shop.dummy_snapshot: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "user", "target_name": "default", "node_id": "snapshot.jaffle_shop.dummy_snapshot"} */

      

      create or replace transient table DEMO_DB.potato.dummy_snapshot  as
      (

    select *,
        md5(coalesce(cast(uniqueid as varchar ), '')
         || '|' || coalesce(cast(cast ('2021-11-11' as timestamp) as varchar ), '')
        ) as dbt_scd_id,
        cast ('2021-11-11' as timestamp) as dbt_updated_at,
        cast ('2021-11-11' as timestamp) as dbt_valid_from,
        nullif(cast ('2021-11-11' as timestamp), cast ('2021-11-11' as timestamp)) as dbt_valid_to
    from (
        



select 1 as uniqueid, current_timestamp() as ts

    ) sbq


      );
```

### Environment

```markdown
- OS:
- Python:
- dbt: 1.0.0 vs 0.21.0
dbt cloud
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment] 2022-01-19 14:08
Here's what I know about this issue:
- This is an issue with the RPC server + partial parsing
- @jeremyyeo detailed the same issue over in https://github.com/dbt-labs/dbt-rpc/issues/48#issuecomment-997537912
- This represents a regression in v1.0 for folks who use the dbt Cloud IDE, which relies on the RPC server
- The RPC server _should_ be fully re-parsing all project files whenever `--vars` are passed into a `cli_args` method, and storing the new values of `config()`. That's what happens on the CLI, and why we're returning the correct results there—but it clearly isn't happening here.
- We're not planning to support `dbt-rpc` for the indefinite future. I believe that this won't be an issue for the new Server, given how it will work with parsing in particular. But it would _not_ feel good to document this as a known limitation, given that it's a regression from functionality that worked in previous versions.

Here's what I don't know:
- What's causing the mismatch between `dbt-core` and `dbt-rpc`, as far as triggering that full re-parse?
- How big of a lift would it be to fix?
- How big is that lift, compared to the lift of improving the behavior of `--vars` + partial parsing in ways we know we want to? Namely, only files that call a changed `var()` should actually need to be re-parsed, rather than triggering a full re-parse any time any `--vars` are passed — i.e. exactly the same as the improvement we made for `env_var()` + partial parsing

@leahwicz @gshank Given the unknowns here, I think we need a time-boxed investigation, to try to answer the question of what would be required to fix this.

---

_Putting all that aside, and returning to the specifics of this bug report_

@saraleon1 Could you say a bit more about the actual use case here? Based on the dummy example, it looks like the user wants to run the snapshot multiple times in sequence, once for each day of (historical?) data. Is the mismatch between `ts` and `updated_at` intentional? Would it be possible to refactor the snapshot code to simply be:
```sql
{% snapshot dummy_snapshsot %}

{{
    config(
        target_schema = 'potato',
        unique_key = 'uniqueid',
        strategy = 'check',
        check_cols = 'all',
        updated_at = 'updated_at',
        file_format = 'delta',
        invalidate_hard_deletes = true
    )
}}

select 1 as uniqueid, cast({{ var('run_date', 'current_timestamp') }} as timestamp) as updated_at

{% endsnapshot %}
```
If that accomplishes the use case, I believe that _should_ work. Only `config()` values are resolved at parse time, and will be affected by this partial parsing + RPC bug. Compiled SQL for nodes (including snaphots) is always re-rendered when the node is actually executed.

**Comment by gshank** [comment] 2022-01-19 17:50
When vars are passed to dbt-rpc, they ought to be updated in dbt_rpc/task/cli.py, 'handle_request', where they are copied into config.vars, and then used in ManifestStateCheck to determine whether a full-reparse is necessary. I don't yet see where this process has changed, so I'll have to do some more investigation.

**Comment by gshank** [comment] 2022-01-19 17:55
So it seems that in ManifestStateCheck we're looking at config.args.vars, not config.cli_vars, and in the rpc_server we're only updating config.cli_vars. Still not sure what changed between 0.21 and 1.0.0.

**Comment by gshank** [comment] 2022-01-19 18:14
I suspect that what probably changed was copying the args that are being passed in in a different place because of another bug that we add. Probably originally the args were the same args structure in the config and now they're not. To fix this we need to either change ManifestStateCheck to use cli_vars, or change task.cli.handle_request to also update the config.args.vars. Either of these is pretty simple. Eventually we want to handle the vars like we do env_vars as far as re-parsing, but that's a substantially bigger effort.

**Comment by jtcohen6** [comment] 2022-01-20 10:00
Thanks for the speedy investigation! I'd be in favor of one of the simpler fixes, and defer to you on which one — whichever is clearer to understand / adds less tech debt for the future

**Comment by saraleon1** [comment] 2022-01-27 10:59
Sorry this is late but an update from the user on the workaround:

> When strategy = 'check' and check_cols = 'all', the ‘updated_at’ column would flag every new row as changed from the previous. So it would only work when excluding ‘updated_at’ from check_cols. But that requires explicitly listing all columns by name in check_cols, which is not ideal. However, we are already using a similar workaround.

Thanks for all your help on this!

**Comment by jtcohen6** [comment] 2022-02-09 12:34
This one will be resolved by https://github.com/dbt-labs/dbt-rpc/pull/70

**Comment by leahwicz** [comment] 2022-02-15 23:28
@gshank let's hand this change off to @stu-k to shepherd in. Let's sync the 3 of us on where this is and next steps. I think we need testing and then actual release to GitHub, Pypi, and then to Cloud. 

CC: @kwigley who could be a resource when it comes to the RPC release

**Comment by jtcohen6** [comment] 2022-03-15 13:53
Closing since https://github.com/dbt-labs/dbt-rpc/pull/70 was merged! Let's open a new issue to track `dbt-rpc==0.1.2` release

**Closed by jtcohen6** 2022-03-15 13:53 UTC
Labels: bug, rpc, regression, vars, Team:Language
